# Generated by Django 5.1.2 on 2024-11-07 04:59

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name_last', models.CharField(max_length=30, verbose_name='名前(姓)')),
                ('name_first', models.CharField(max_length=30, verbose_name='名前(名)')),
                ('name_kana_last', models.CharField(max_length=30, verbose_name='カナ(姓)')),
                ('name_kana_first', models.CharField(max_length=30, verbose_name='カナ(名)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性別')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号')),
                ('address_kana', models.TextField(blank=True, null=True, verbose_name='住所カナ')),
                ('address1', models.TextField(blank=True, null=True, verbose_name='住所１')),
                ('address2', models.TextField(blank=True, null=True, verbose_name='住所２')),
                ('address3', models.TextField(blank=True, null=True, verbose_name='住所３')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='電話番号')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-MAIL')),
                ('regist_form_code', models.IntegerField(blank=True, null=True, verbose_name='登録区分')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'db_table': 'apps_staff',
            },
        ),
    ]
