# Generated by Django 5.2.8 on 2026-02-01 21:55

import apps.staff.models_other
import apps.staff.models_staff
import concurrency.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("name_last", models.CharField(max_length=30, verbose_name="名前(姓)")),
                (
                    "name_first",
                    models.CharField(max_length=30, verbose_name="名前(名)"),
                ),
                (
                    "name_kana_last",
                    models.CharField(max_length=30, verbose_name="カナ(姓)"),
                ),
                (
                    "name_kana_first",
                    models.CharField(max_length=30, verbose_name="カナ(名)"),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="名前")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生年月日"),
                ),
                (
                    "sex",
                    models.IntegerField(blank=True, null=True, verbose_name="性別"),
                ),
                ("age", models.PositiveIntegerField(default=0, verbose_name="年齢")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address_kana",
                    models.TextField(blank=True, null=True, verbose_name="住所カナ"),
                ),
                (
                    "address1",
                    models.TextField(blank=True, null=True, verbose_name="住所１"),
                ),
                (
                    "address2",
                    models.TextField(blank=True, null=True, verbose_name="住所２"),
                ),
                (
                    "address3",
                    models.TextField(blank=True, null=True, verbose_name="住所３"),
                ),
                (
                    "phone",
                    models.TextField(blank=True, null=True, verbose_name="電話番号"),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="E-MAIL",
                    ),
                ),
                (
                    "employee_no",
                    models.CharField(
                        blank=True,
                        help_text="半角英数字10文字まで",
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="社員番号",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入社日"),
                ),
                (
                    "resignation_date",
                    models.DateField(blank=True, null=True, verbose_name="退職日"),
                ),
                (
                    "department_code",
                    models.CharField(
                        blank=True,
                        help_text="会社部署の部署コードを参照",
                        max_length=20,
                        null=True,
                        verbose_name="所属部署コード",
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.employmenttype",
                        verbose_name="雇用形態",
                    ),
                ),
                (
                    "regist_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.staffregiststatus",
                        verbose_name="登録区分",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staffs",
                        to="master.stafftag",
                        verbose_name="タグ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ",
                "db_table": "apps_staff",
            },
        ),
        migrations.CreateModel(
            name="StaffBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        help_text="4桁の数字で入力",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="銀行コードは4桁の数字で入力してください",
                                regex="^\\d{4}$",
                            )
                        ],
                        verbose_name="銀行コード",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        help_text="3桁の数字で入力",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="支店コードは3桁の数字で入力してください",
                                regex="^\\d{3}$",
                            )
                        ],
                        verbose_name="支店コード",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        help_text="普通、当座など",
                        max_length=10,
                        verbose_name="口座種別",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="1-8桁の数字で入力",
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="口座番号は1-8桁の数字で入力してください",
                                regex="^\\d{1,8}$",
                            )
                        ],
                        verbose_name="口座番号",
                    ),
                ),
                (
                    "account_holder",
                    models.CharField(
                        help_text="口座名義人の名前",
                        max_length=100,
                        verbose_name="口座名義",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ銀行情報",
                "verbose_name_plural": "スタッフ銀行情報",
                "db_table": "apps_staff_bank",
            },
        ),
        migrations.CreateModel(
            name="StaffContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="緊急連絡先"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="続柄"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="郵便番号（住民票）",
                    ),
                ),
                (
                    "address1",
                    models.TextField(
                        blank=True, null=True, verbose_name="住所１（住民票）"
                    ),
                ),
                (
                    "address2",
                    models.TextField(
                        blank=True, null=True, verbose_name="住所２（住民票）"
                    ),
                ),
                (
                    "address3",
                    models.TextField(
                        blank=True, null=True, verbose_name="住所３（住民票）"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_staff_contact_set_staff_app",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_staff_contact_set_staff_app",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ連絡先情報",
                "verbose_name_plural": "スタッフ連絡先情報",
                "db_table": "apps_staff_contacts",
            },
        ),
        migrations.CreateModel(
            name="StaffContacted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("contacted_at", models.DateTimeField(verbose_name="連絡日時")),
                ("content", models.CharField(max_length=255, verbose_name="対応内容")),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="対応詳細"),
                ),
                (
                    "contact_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.staffcontacttype",
                        verbose_name="連絡種別",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacted_histories",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ連絡履歴",
                "verbose_name_plural": "スタッフ連絡履歴",
                "db_table": "apps_staff_contacted",
                "ordering": ["-contacted_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffContactSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("contact_date", models.DateField(verbose_name="連絡日")),
                ("content", models.CharField(max_length=255, verbose_name="対応内容")),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="対応詳細"),
                ),
                (
                    "contact_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.staffcontacttype",
                        verbose_name="連絡種別",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_schedules",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ連絡予定",
                "verbose_name_plural": "スタッフ連絡予定",
                "db_table": "apps_staff_contact_schedule",
                "ordering": ["-contact_date"],
            },
        ),
        migrations.CreateModel(
            name="StaffDisability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "disability_type",
                    models.CharField(
                        help_text="障害の種類を入力してください",
                        max_length=100,
                        verbose_name="障害の種類",
                    ),
                ),
                (
                    "disability_grade",
                    models.CharField(
                        blank=True,
                        help_text="障害の等級を入力してください",
                        max_length=100,
                        null=True,
                        verbose_name="等級",
                    ),
                ),
                (
                    "disability_severity",
                    models.CharField(
                        blank=True,
                        help_text="障害の重度を入力してください",
                        max_length=100,
                        null=True,
                        verbose_name="重度",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disability",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ障害者情報",
                "verbose_name_plural": "スタッフ障害者情報",
                "db_table": "apps_staff_disability",
            },
        ),
        migrations.CreateModel(
            name="StaffEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "evaluation_date",
                    models.DateField(
                        default=django.db.models.functions.datetime.Now,
                        verbose_name="評価日",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        help_text="1(悪い) - 5(良い)",
                        verbose_name="評価",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="コメント"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評価者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ評価",
                "verbose_name_plural": "スタッフ評価",
                "db_table": "apps_staff_evaluation",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="StaffFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="フラッグに関する詳細情報",
                        null=True,
                        verbose_name="詳細",
                    ),
                ),
                (
                    "company_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社組織",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companydepartment",
                        verbose_name="会社組織",
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社担当者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companyuser",
                        verbose_name="会社担当者",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "flag_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグのステータス",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.flagstatus",
                        verbose_name="フラッグステータス",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフフラッグ",
                "verbose_name_plural": "スタッフフラッグ",
                "db_table": "apps_staff_flag",
            },
        ),
        migrations.CreateModel(
            name="StaffInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "inquiry_from",
                    models.CharField(
                        choices=[("staff", "スタッフ"), ("company", "会社")],
                        default="staff",
                        max_length=10,
                        verbose_name="問い合わせ元",
                    ),
                ),
                (
                    "last_message_by",
                    models.CharField(
                        choices=[("staff", "スタッフ"), ("company", "会社")],
                        default="staff",
                        max_length=10,
                        verbose_name="最終投稿者",
                    ),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        help_text="接続承認済みクライアントの法人番号",
                        max_length=13,
                        verbose_name="あて先法人番号",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="件名")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="inquiry_attachments/%Y/%m/%d/",
                        verbose_name="添付ファイル",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "受付中"), ("completed", "完了")],
                        default="open",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ問い合わせ・ご連絡",
                "verbose_name_plural": "スタッフ問い合わせ・ご連絡",
                "db_table": "apps_staff_inquiry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffInquiryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("content", models.TextField(verbose_name="メッセージ内容")),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="チェックを入れるとスタッフに表示されません（社内メモ用）",
                        verbose_name="非表示",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="既読日時"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="inquiry_attachments/%Y/%m/%d/",
                        verbose_name="添付ファイル",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="staff.staffinquiry",
                        verbose_name="問い合わせ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ問い合わせメッセージ",
                "verbose_name_plural": "スタッフ問い合わせメッセージ",
                "db_table": "apps_staff_inquiry_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffInternational",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "residence_card_number",
                    models.CharField(
                        help_text="在留カード番号を入力してください",
                        max_length=20,
                        verbose_name="在留カード番号",
                    ),
                ),
                (
                    "residence_status",
                    models.CharField(
                        help_text="在留資格を入力してください",
                        max_length=100,
                        verbose_name="在留資格",
                    ),
                ),
                (
                    "residence_period_from",
                    models.DateField(
                        help_text="在留許可の開始日を入力してください",
                        verbose_name="在留許可開始日",
                    ),
                ),
                (
                    "residence_period_to",
                    models.DateField(
                        help_text="在留期間の終了日（在留期限）を入力してください",
                        verbose_name="在留期限",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="international",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ外国籍情報",
                "verbose_name_plural": "スタッフ外国籍情報",
                "db_table": "apps_staff_international",
            },
        ),
        migrations.CreateModel(
            name="StaffMynumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "mynumber",
                    models.CharField(
                        help_text="マイナンバーを12桁の数字で入力してください",
                        max_length=12,
                        validators=[
                            apps.staff.models_other.validate_mynumber,
                            django.core.validators.RegexValidator(
                                message="マイナンバーは12桁の数字で入力してください",
                                regex="^\\d{12}$",
                            ),
                        ],
                        verbose_name="マイナンバー",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mynumber",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフマイナンバー",
                "verbose_name_plural": "スタッフマイナンバー",
                "db_table": "apps_staff_mynumber",
            },
        ),
        migrations.CreateModel(
            name="StaffPayroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "health_insurance_join_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="健康保険加入日"
                    ),
                ),
                (
                    "health_insurance_non_enrollment_reason",
                    models.TextField(
                        blank=True,
                        help_text="健康保険に加入しない場合の理由を入力してください",
                        null=True,
                        verbose_name="健康保険非加入理由",
                    ),
                ),
                (
                    "welfare_pension_join_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="厚生年金加入日"
                    ),
                ),
                (
                    "pension_insurance_non_enrollment_reason",
                    models.TextField(
                        blank=True,
                        help_text="厚生年金に加入しない場合の理由を入力してください",
                        null=True,
                        verbose_name="厚生年金非加入理由",
                    ),
                ),
                (
                    "employment_insurance_join_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="雇用保険加入日"
                    ),
                ),
                (
                    "employment_insurance_non_enrollment_reason",
                    models.TextField(
                        blank=True,
                        help_text="雇用保険に加入しない場合の理由を入力してください",
                        null=True,
                        verbose_name="雇用保険非加入理由",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ給与",
                "verbose_name_plural": "スタッフ給与",
                "db_table": "apps_staff_payroll",
            },
        ),
        migrations.CreateModel(
            name="StaffFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="添付ファイル（最大10MB）",
                        upload_to=apps.staff.models_staff.staff_file_upload_path,
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="アップロード時の元のファイル名",
                        max_length=255,
                        verbose_name="元ファイル名",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="バイト単位", verbose_name="ファイルサイズ"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="ファイルの説明（任意）",
                        max_length=255,
                        null=True,
                        verbose_name="説明",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="アップロード日時"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフファイル",
                "verbose_name_plural": "スタッフファイル",
                "db_table": "apps_staff_file",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["staff"], name="apps_staff__staff_i_a20af1_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="apps_staff__uploade_31db21_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "acquired_date",
                    models.DateField(blank=True, null=True, verbose_name="取得日"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="有効期限"),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="証明書番号"
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="TOEICの点数など",
                        null=True,
                        verbose_name="点数",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.qualification",
                        verbose_name="資格",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ資格",
                "verbose_name_plural": "スタッフ資格",
                "db_table": "apps_staff_qualification",
                "ordering": ["-acquired_date"],
                "indexes": [
                    models.Index(
                        fields=["staff"], name="apps_staff__staff_i_cfa200_idx"
                    ),
                    models.Index(
                        fields=["qualification"], name="apps_staff__qualifi_cfa892_idx"
                    ),
                    models.Index(
                        fields=["acquired_date"], name="apps_staff__acquire_a827de_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="apps_staff__expiry__480291_idx"
                    ),
                ],
                "unique_together": {("staff", "qualification")},
            },
        ),
        migrations.CreateModel(
            name="StaffSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "acquired_date",
                    models.DateField(blank=True, null=True, verbose_name="習得日"),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(blank=True, null=True, verbose_name="経験年数"),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.skill",
                        verbose_name="技能",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ技能",
                "verbose_name_plural": "スタッフ技能",
                "db_table": "apps_staff_skill",
                "ordering": ["-acquired_date"],
                "indexes": [
                    models.Index(
                        fields=["staff"], name="apps_staff__staff_i_e07a67_idx"
                    ),
                    models.Index(
                        fields=["skill"], name="apps_staff__skill_i_1e0d1f_idx"
                    ),
                    models.Index(
                        fields=["acquired_date"], name="apps_staff__acquire_bc2d06_idx"
                    ),
                ],
                "unique_together": {("staff", "skill")},
            },
        ),
    ]
