# Generated by Django 5.1.2 on 2024-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='E-MAIL'),
        ),
    ]
