# Generated by Django 5.2.8 on 2026-02-06 13:09

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_stafffavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='テナントID')),
                ('grade_code', models.CharField(help_text='スタッフ等級マスタのコード', max_length=20, verbose_name='等級コード')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='有効期間開始')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='有効期間終了')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ等級',
                'verbose_name_plural': 'スタッフ等級',
                'db_table': 'apps_staff_grade',
                'ordering': ['-valid_from'],
            },
        ),
    ]
