# Generated by Django 5.2.8 on 2026-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_stafffavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="grade",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="等級"
            ),
        ),
    ]
