# Generated by Django 5.2.1 on 2025-07-12 14:57

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_name_alter_staff_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='年齢'),
        ),
        migrations.CreateModel(
            name='StaffContacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contacted_at', models.DateTimeField(auto_now_add=True, verbose_name='連絡日時')),
                ('content', models.TextField(verbose_name='対応内容')),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='連絡種別')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_histories', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ連絡履歴',
                'verbose_name_plural': 'スタッフ連絡履歴',
                'db_table': 'apps_staff_contacted',
                'ordering': ['-contacted_at'],
            },
        ),
    ]
