# Generated by Django 5.2.7 on 2025-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffpayroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayroll',
            name='employment_insurance_non_enrollment_reason',
            field=models.TextField(blank=True, help_text='雇用保険に加入しない場合の理由を入力してください', null=True, verbose_name='雇用保険非加入理由'),
        ),
        migrations.AddField(
            model_name='staffpayroll',
            name='health_insurance_non_enrollment_reason',
            field=models.TextField(blank=True, help_text='健康保険に加入しない場合の理由を入力してください', null=True, verbose_name='健康保険非加入理由'),
        ),
        migrations.AddField(
            model_name='staffpayroll',
            name='pension_insurance_non_enrollment_reason',
            field=models.TextField(blank=True, help_text='厚生年金に加入しない場合の理由を入力してください', null=True, verbose_name='厚生年金非加入理由'),
        ),
    ]
