# Generated by Django 5.2.8 on 2026-02-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='grade',
        ),
    ]
