# Generated by Django 5.2.1 on 2025-07-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_age_staffcontacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontacted',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='対応詳細'),
        ),
        migrations.AlterField(
            model_name='staffcontacted',
            name='content',
            field=models.CharField(max_length=255, verbose_name='対応内容'),
        ),
    ]
