# Generated by Django 5.2.8 on 2026-02-10 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staffgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpayroll",
            name="basic_pension_number",
            field=models.CharField(
                blank=True,
                help_text="10桁の数字で入力してください（ハイフンも含められます）",
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="基礎年金番号は10桁の数字（ハイフン可）で入力してください",
                        regex="^[\\d-]{10,12}$",
                    )
                ],
                verbose_name="基礎年金番号",
            ),
        ),
    ]
