# Generated by Django 5.2.1 on 2025-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffcontacted_detail_alter_staffcontacted_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcontacted',
            name='contact_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='連絡種別'),
        ),
    ]
