# Generated by Django 5.2.8 on 2026-02-14 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_staffpayroll_basic_pension_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpayroll",
            name="employment_insurance_number",
            field=models.CharField(
                blank=True,
                help_text="11桁の数字で入力してください（ハイフンも含められます）",
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="雇用保険被保険者番号は11桁の数字（ハイフン可）で入力してください",
                        regex="^[\\d-]{11,13}$",
                    )
                ],
                verbose_name="雇用保険被保険者番号",
            ),
        ),
        migrations.AddField(
            model_name="staffpayroll",
            name="previous_job_company_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="前職会社名"
            ),
        ),
        migrations.AddField(
            model_name="staffpayroll",
            name="previous_job_retirement_date",
            field=models.DateField(blank=True, null=True, verbose_name="前職退職日"),
        ),
    ]
