# Generated by Django 5.2.6 on 2026-01-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staffinquirymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinquirymessage',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='チェックを入れるとスタッフに表示されません（社内メモ用）', verbose_name='非表示'),
        ),
    ]
