# Generated by Django 5.2.6 on 2026-01-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staffinquiry_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinquiry',
            name='is_hidden',
        ),
    ]
