# Generated by Django 5.2.8 on 2026-01-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_remove_staffinquiry_is_hidden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffinquiry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "スタッフ問い合わせ・ご連絡",
                "verbose_name_plural": "スタッフ問い合わせ・ご連絡",
            },
        ),
        migrations.AddField(
            model_name="staffinquiry",
            name="inquiry_from",
            field=models.CharField(
                choices=[("staff", "スタッフ"), ("company", "会社")],
                default="staff",
                max_length=10,
                verbose_name="問い合わせ元",
            ),
        ),
    ]
