# Generated by Django 5.2.8 on 2026-01-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0010_alter_staffinquiry_options_staffinquiry_inquiry_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffinquirymessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="既読日時"),
        ),
    ]
