# Generated by Django 5.2.6 on 2026-01-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_staffinquirymessage_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinquiry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_attachments/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
        migrations.AddField(
            model_name='staffinquirymessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_attachments/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
