# Generated by Django 5.2.1 on 2025-07-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffcontacted_contact_type'),
        ('staff', '0011_staff_employee_no'),
    ]

    operations = [
    ]
