# Generated by Django 5.2.1 on 2025-07-23
from django.db import migrations
import concurrency.fields

class Migration(migrations.Migration):
    dependencies = [
        ('staff', '0011_staff_employee_no'),
    ]
    operations = [
        migrations.AddField(
            model_name='staff',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0),
        ),
    ]
