# Generated by Django 5.2.1 on 2025-07-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_merge_20250723_0158'),
        ('staff', '0012_staff_version'),
    ]

    operations = [
    ]
