# Generated by Django 5.2.8 on 2026-01-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0013_staffcontactschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffinquiry",
            name="status",
            field=models.CharField(
                choices=[("open", "受付中"), ("completed", "完了")],
                default="open",
                max_length=10,
                verbose_name="ステータス",
            ),
        ),
    ]
