# Generated by Django 5.2.1 on 2025-07-23 15:10

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_merge_0012_merge_20250723_0158_0012_staff_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontacted',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
