# Generated by Django 5.2.4 on 2025-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_staffcontacted_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department_code',
            field=models.CharField(blank=True, help_text='会社部署の部署コードを参照', max_length=20, null=True, verbose_name='所属部署コード'),
        ),
        migrations.AddField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='入社日'),
        ),
        migrations.AddField(
            model_name='staff',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='退職日'),
        ),
    ]
