# Generated by Django 5.2.6 on 2026-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_staffinquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinquiry',
            name='last_message_by',
            field=models.CharField(choices=[('staff', 'スタッフ'), ('company', '会社')], default='staff', max_length=10, verbose_name='最終投稿者'),
        ),
        migrations.AddField(
            model_name='staffinquirymessage',
            name='sender_type',
            field=models.CharField(choices=[('staff', 'スタッフ'), ('company', '会社')], default='staff', max_length=10, verbose_name='投稿者タイプ'),
        ),
    ]
