# Generated by Django 5.2.6 on 2026-01-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_staffinquiry_last_message_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinquirymessage',
            name='sender_type',
        ),
    ]
