# Generated by Django 5.2.4 on 2025-08-06 11:59

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('staff', '0015_staff_department_code_staff_hire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='取得日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='証明書番号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.qualification', verbose_name='資格')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ資格',
                'verbose_name_plural': 'スタッフ資格',
                'db_table': 'apps_staff_qualification',
                'ordering': ['-acquired_date'],
                'indexes': [models.Index(fields=['staff'], name='apps_staff__staff_i_cfa200_idx'), models.Index(fields=['qualification'], name='apps_staff__qualifi_cfa892_idx'), models.Index(fields=['acquired_date'], name='apps_staff__acquire_a827de_idx'), models.Index(fields=['expiry_date'], name='apps_staff__expiry__480291_idx')],
                'unique_together': {('staff', 'qualification')},
            },
        ),
        migrations.CreateModel(
            name='StaffSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('level', models.CharField(choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '上級'), ('expert', 'エキスパート')], default='beginner', max_length=20, verbose_name='レベル')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='習得日')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='経験年数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.skill', verbose_name='技能')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ技能',
                'verbose_name_plural': 'スタッフ技能',
                'db_table': 'apps_staff_skill',
                'ordering': ['-acquired_date'],
                'indexes': [models.Index(fields=['staff'], name='apps_staff__staff_i_e07a67_idx'), models.Index(fields=['skill'], name='apps_staff__skill_i_1e0d1f_idx'), models.Index(fields=['level'], name='apps_staff__level_b10a5c_idx'), models.Index(fields=['acquired_date'], name='apps_staff__acquire_bc2d06_idx')],
                'unique_together': {('staff', 'skill')},
            },
        ),
    ]
