# Generated by Django 5.2.4 on 2025-08-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_staffqualification_staffskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffqualification',
            name='score',
            field=models.IntegerField(blank=True, help_text='TOEICの点数など', null=True, verbose_name='点数'),
        ),
    ]
