# Generated by Django 5.2.8 on 2026-01-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_remove_staffinquirymessage_sender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinquiry',
            name='content',
        ),
    ]
