# Generated by Django 5.2.8 on 2026-01-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0017_remove_staffinquiry_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffbank",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontact",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontacted",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontactschedule",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffdisability",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffevaluation",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="stafffile",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffinquiry",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffinquirymessage",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffinternational",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffmynumber",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffpayroll",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffqualification",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffskill",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
    ]
