# Generated by Django 5.2.4 on 2025-08-08 10:27

import apps.staff.models
import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_staffqualification_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('file', models.FileField(help_text='添付ファイル（最大10MB）', upload_to=apps.staff.models.staff_file_upload_path, verbose_name='ファイル')),
                ('original_filename', models.CharField(help_text='アップロード時の元のファイル名', max_length=255, verbose_name='元ファイル名')),
                ('file_size', models.PositiveIntegerField(help_text='バイト単位', verbose_name='ファイルサイズ')),
                ('description', models.CharField(blank=True, help_text='ファイルの説明（任意）', max_length=255, null=True, verbose_name='説明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフファイル',
                'verbose_name_plural': 'スタッフファイル',
                'db_table': 'apps_staff_file',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['staff'], name='apps_staff__staff_i_a20af1_idx'), models.Index(fields=['uploaded_at'], name='apps_staff__uploade_31db21_idx')],
            },
        ),
    ]
