# Generated by Django 5.2.8 on 2026-01-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0046_clientcontacttype_staffcontacttype"),
        ("staff", "0018_staff_tenant_id_staffbank_tenant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcontacted",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.staffcontacttype",
                verbose_name="連絡種別",
            ),
        ),
        migrations.AlterField(
            model_name="staffcontactschedule",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.staffcontacttype",
                verbose_name="連絡種別",
            ),
        ),
    ]
