# Generated by Django 5.2.4 on 2025-08-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_stafffile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staffskill',
            name='apps_staff__level_b10a5c_idx',
        ),
        migrations.RemoveField(
            model_name='staffskill',
            name='level',
        ),
    ]
