# Generated by Django 5.2.8 on 2026-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0047_clienttag_stafftag'),
        ('staff', '0018_staff_tenant_id_staffbank_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='master.stafftag', verbose_name='タグ'),
        ),
    ]
