# Generated by Django 5.2.4 on 2025-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_remove_staffskill_apps_staff__level_b10a5c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcontacted',
            name='contacted_at',
            field=models.DateTimeField(verbose_name='連絡日時'),
        ),
    ]
