# Generated by Django 5.2.8 on 2026-01-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0047_clienttag_stafftag"),
        ("staff", "0019_staff_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcontacted",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.staffcontacttype",
                verbose_name="連絡種別",
            ),
        ),
        migrations.AlterField(
            model_name="staffcontactschedule",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.staffcontacttype",
                verbose_name="連絡種別",
            ),
        ),
    ]
