# Generated by Django 5.2.4 on 2025-08-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_staffcontacted_contacted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
