# Generated by Django 5.2.5 on 2025-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_staffmynumberrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(blank=True, help_text='dropdowns employment_type', max_length=10, null=True, verbose_name='雇用形態'),
        ),
    ]
