# Generated by Django 5.2.5 on 2025-08-25 17:00

import concurrency.fields
import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_staffinternational'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('bank_code', models.CharField(blank=True, help_text='4桁の数字で入力（任意）', max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='銀行コードは4桁の数字で入力してください', regex='^\\d{4}$')], verbose_name='銀行コード')),
                ('branch_code', models.CharField(blank=True, help_text='3桁の数字で入力（任意）', max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='支店コードは3桁の数字で入力してください', regex='^\\d{3}$')], verbose_name='支店コード')),
                ('account_type', models.CharField(help_text='普通、当座など', max_length=10, verbose_name='口座種別')),
                ('account_number', models.CharField(help_text='1-8桁の数字で入力', max_length=8, validators=[django.core.validators.RegexValidator(message='口座番号は1-8桁の数字で入力してください', regex='^\\d{1,8}$')], verbose_name='口座番号')),
                ('account_holder', models.CharField(help_text='口座名義人の名前', max_length=100, verbose_name='口座名義')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ銀行情報',
                'verbose_name_plural': 'スタッフ銀行情報',
                'db_table': 'apps_staff_bank',
            },
        ),
    ]
