# Generated by Django 5.2.5 on 2025-08-26 14:04

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0026_staffdisability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="緊急連絡先"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="続柄"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="郵便番号（住民票）",
                    ),
                ),
                (
                    "address1",
                    models.TextField(
                        blank=True, null=True, verbose_name="住所１（住民票）"
                    ),
                ),
                (
                    "address2",
                    models.TextField(
                        blank=True, null=True, verbose_name="住所２（住民票）"
                    ),
                ),
                (
                    "address3",
                    models.TextField(
                        blank=True, null=True, verbose_name="住所３（住民票）"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ連絡先情報",
                "verbose_name_plural": "スタッフ連絡先情報",
                "db_table": "apps_staff_contacts",
            },
        ),
    ]
