# Generated by Django 5.2.5 on 2025-08-26 15:05

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0027_staffcontact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcontact",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_staff_contact_set_staff_app",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作成者",
            ),
        ),
        migrations.AlterField(
            model_name="staffcontact",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_staff_contact_set_staff_app",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新者",
            ),
        ),
    ]
