# Generated by Django 5.2.5 on 2025-08-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0028_staff_contact_related_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffdisability",
            name="severity",
        ),
        migrations.AddField(
            model_name="staffdisability",
            name="disability_grade",
            field=models.CharField(
                blank=True,
                help_text="障害の等級を入力してください",
                max_length=100,
                null=True,
                verbose_name="等級",
            ),
        ),
    ]
