# Generated by Django 5.2.5 on 2025-08-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0029_remove_staffdisability_severity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="employee_no",
            field=models.CharField(
                blank=True,
                help_text="半角英数字10文字まで",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="社員番号",
            ),
        ),
    ]
