# Generated by Django 5.2.5 on 2025-08-28 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0030_alter_staff_employee_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffbank",
            name="bank_code",
            field=models.CharField(
                help_text="4桁の数字で入力",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="銀行コードは4桁の数字で入力してください",
                        regex="^\\d{4}$",
                    )
                ],
                verbose_name="銀行コード",
            ),
        ),
        migrations.AlterField(
            model_name="staffbank",
            name="branch_code",
            field=models.CharField(
                help_text="3桁の数字で入力",
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        message="支店コードは3桁の数字で入力してください",
                        regex="^\\d{3}$",
                    )
                ],
                verbose_name="支店コード",
            ),
        ),
    ]
