# Generated by Django 5.2.6 on 2025-10-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_alter_staffbank_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdisability',
            name='disability_severity',
            field=models.CharField(blank=True, help_text='障害の重度を入力してください', max_length=100, null=True, verbose_name='重度'),
        ),
    ]
