# Generated by Django 5.2.7 on 2025-10-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0035_alter_contractpattern_employment_type_to_fk'),
        ('staff', '0032_staffdisability_disability_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employmenttype', verbose_name='雇用形態'),
        ),
    ]
