# Generated by Django 5.2.7 on 2025-10-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0036_clientregiststatus_staffregiststatus'),
        ('staff', '0033_alter_staff_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_regist_status_code',
        ),
        migrations.AddField(
            model_name='staff',
            name='regist_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.staffregiststatus', verbose_name='登録区分'),
        ),
    ]
