# Generated by Django 5.2.8 on 2026-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="APIリクエストを一意に識別するキー",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("response", models.JSONField(help_text="APIからのレスポンスボディ")),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="キャッシュの有効期限"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="レコード作成日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "APIキャッシュ",
                "verbose_name_plural": "APIキャッシュ",
                "db_table": "apps_system_api_cache",
                "ordering": ["-created_at"],
            },
        ),
    ]
