# Generated by Django 5.2.8 on 2026-01-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicache', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apicache',
            table='apps_system_apicache',
        ),
    ]
