# Generated by Django 5.2.8 on 2026-01-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicache', '0002_alter_apicache_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apicache',
            table='apps_system_api_cache',
        ),
    ]
