# Generated by Django 5.2.8 on 2025-11-15 10:21

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0020_clientcontract_overtime_pattern'),
        ('staff', '0003_staffpayroll_employment_insurance_non_enrollment_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('year', models.PositiveIntegerField(help_text='対象年（例：2025）', verbose_name='年')),
                ('month', models.PositiveIntegerField(help_text='対象月（1-12）', verbose_name='月')),
                ('total_work_days', models.PositiveIntegerField(default=0, verbose_name='出勤日数')),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='総労働時間')),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='残業時間')),
                ('total_holiday_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='休日労働時間')),
                ('total_late_minutes', models.PositiveIntegerField(default=0, verbose_name='遅刻時間（分）')),
                ('total_early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='早退時間（分）')),
                ('total_absence_days', models.PositiveIntegerField(default=0, verbose_name='欠勤日数')),
                ('total_paid_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='有給休暇日数')),
                ('status', models.CharField(choices=[('10', '作成中'), ('20', '提出済み'), ('30', '承認済み'), ('40', '差戻し')], default='10', max_length=2, verbose_name='ステータス')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提出日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='差戻し日時')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='差戻し理由')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='差戻し者')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='staff.staff', verbose_name='スタッフ')),
                ('staff_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='contract.staffcontract', verbose_name='スタッフ契約')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='提出者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '月次勤怠',
                'verbose_name_plural': '月次勤怠',
                'db_table': 'apps_kintai_staff_timesheet',
                'ordering': ['-year', '-month', 'staff__name_last', 'staff__name_first'],
            },
        ),
        migrations.CreateModel(
            name='StaffTimecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('work_type', models.CharField(choices=[('10', '出勤'), ('20', '休日'), ('30', '欠勤'), ('40', '有給休暇'), ('50', '特別休暇'), ('60', '代休')], default='10', max_length=2, verbose_name='勤務区分')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='休憩時間（分）')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, help_text='実労働時間（時間）', max_digits=5, verbose_name='労働時間')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='残業時間（時間）', max_digits=5, verbose_name='残業時間')),
                ('holiday_work_hours', models.DecimalField(decimal_places=2, default=0, help_text='休日労働時間（時間）', max_digits=5, verbose_name='休日労働時間')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='遅刻時間（分）')),
                ('early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='早退時間（分）')),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=0, help_text='0.5（半休）または1.0（全休）', max_digits=3, verbose_name='有給休暇日数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecards', to='kintai.stafftimesheet', verbose_name='月次勤怠')),
            ],
            options={
                'verbose_name': '日次勤怠',
                'verbose_name_plural': '日次勤怠',
                'db_table': 'apps_kintai_staff_timecard',
                'ordering': ['work_date'],
            },
        ),
        migrations.AddIndex(
            model_name='stafftimesheet',
            index=models.Index(fields=['staff_contract'], name='apps_kintai_staff_c_0f16fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimesheet',
            index=models.Index(fields=['staff'], name='apps_kintai_staff_i_4d2b31_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimesheet',
            index=models.Index(fields=['year', 'month'], name='apps_kintai_year_f50a43_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimesheet',
            index=models.Index(fields=['status'], name='apps_kintai_status_0b517d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stafftimesheet',
            unique_together={('staff_contract', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='stafftimecard',
            index=models.Index(fields=['timesheet'], name='apps_kintai_timeshe_d513f3_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimecard',
            index=models.Index(fields=['work_date'], name='apps_kintai_work_da_93fb82_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimecard',
            index=models.Index(fields=['work_type'], name='apps_kintai_work_ty_014ab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stafftimecard',
            unique_together={('timesheet', 'work_date')},
        ),
    ]
