# Generated by Django 5.2.8 on 2026-02-01 21:55

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract", "0001_initial"),
        ("master", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffTimerecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("work_date", models.DateField(verbose_name="勤務日")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時刻"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了時刻"
                    ),
                ),
                (
                    "rounded_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="丸め開始時刻"
                    ),
                ),
                (
                    "rounded_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="丸め終了時刻"
                    ),
                ),
                (
                    "start_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="開始位置（緯度）",
                    ),
                ),
                (
                    "start_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="開始位置（経度）",
                    ),
                ),
                (
                    "end_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="終了位置（緯度）",
                    ),
                ),
                (
                    "end_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="終了位置（経度）",
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timerecords",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "staff_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timerecords",
                        to="contract.staffcontract",
                        verbose_name="スタッフ契約",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "勤怠打刻",
                "verbose_name_plural": "勤怠打刻",
                "db_table": "apps_kintai_staff_timerecord",
                "ordering": ["-work_date", "staff__name_last", "staff__name_first"],
            },
        ),
        migrations.CreateModel(
            name="StaffTimerecordBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("break_start", models.DateTimeField(verbose_name="休憩開始時刻")),
                (
                    "break_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="休憩終了時刻"
                    ),
                ),
                (
                    "rounded_break_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="丸め休憩開始時刻"
                    ),
                ),
                (
                    "rounded_break_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="丸め休憩終了時刻"
                    ),
                ),
                (
                    "start_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="開始位置（緯度）",
                    ),
                ),
                (
                    "start_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="開始位置（経度）",
                    ),
                ),
                (
                    "end_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="終了位置（緯度）",
                    ),
                ),
                (
                    "end_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=20,
                        null=True,
                        verbose_name="終了位置（経度）",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "timerecord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="kintai.stafftimerecord",
                        verbose_name="勤怠打刻",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "休憩時間",
                "verbose_name_plural": "休憩時間",
                "db_table": "apps_kintai_staff_timerecord_break",
                "ordering": ["break_start"],
            },
        ),
        migrations.CreateModel(
            name="StaffTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "target_month",
                    models.DateField(
                        help_text="対象年月の1日を設定してください。",
                        verbose_name="対象年月",
                    ),
                ),
                (
                    "total_work_days",
                    models.PositiveIntegerField(default=0, verbose_name="出勤日数"),
                ),
                (
                    "total_work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="総労働時間（分）"
                    ),
                ),
                (
                    "total_overtime_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="残業時間（分）"
                    ),
                ),
                (
                    "total_late_night_overtime_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="深夜時間（分）"
                    ),
                ),
                (
                    "total_holiday_work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="休日労働時間（分）"
                    ),
                ),
                (
                    "total_premium_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="月単位時間範囲での割増時間",
                        verbose_name="割増時間（分）",
                    ),
                ),
                (
                    "total_deduction_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="月単位時間範囲での控除時間",
                        verbose_name="控除時間（分）",
                    ),
                ),
                (
                    "total_variable_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="1ヶ月単位変形労働での月次法定超過時間",
                        verbose_name="変形時間（分）",
                    ),
                ),
                (
                    "total_absence_days",
                    models.PositiveIntegerField(default=0, verbose_name="欠勤日数"),
                ),
                (
                    "total_paid_leave_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="有給休暇日数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("10", "作成中"),
                            ("20", "提出済み"),
                            ("30", "承認済み"),
                            ("40", "差戻し"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提出日時"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="差戻し日時"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True, verbose_name="差戻し理由"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timesheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_timesheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="差戻し者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "staff_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="contract.staffcontract",
                        verbose_name="スタッフ契約",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_timesheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提出者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "月次勤怠",
                "verbose_name_plural": "月次勤怠",
                "db_table": "apps_kintai_staff_timesheet",
                "ordering": ["-target_month", "staff__name_last", "staff__name_first"],
            },
        ),
        migrations.CreateModel(
            name="StaffTimecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("work_date", models.DateField(verbose_name="勤務日")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("10", "出勤"),
                            ("20", "休日"),
                            ("30", "欠勤"),
                            ("40", "有給休暇"),
                            ("50", "特別休暇"),
                            ("60", "代休"),
                            ("70", "稼働無し"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="勤務区分",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="出勤時刻"),
                ),
                (
                    "start_time_next_day",
                    models.BooleanField(default=False, verbose_name="出勤時刻翌日"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="退勤時刻"),
                ),
                (
                    "end_time_next_day",
                    models.BooleanField(default=False, verbose_name="退勤時刻翌日"),
                ),
                (
                    "break_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="休憩時間（分）"
                    ),
                ),
                (
                    "late_night_break_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="深夜休憩（分）"
                    ),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="実労働時間（分）",
                        verbose_name="労働時間（分）",
                    ),
                ),
                (
                    "overtime_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="残業時間（分）",
                        verbose_name="残業時間（分）",
                    ),
                ),
                (
                    "late_night_overtime_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="深夜残業時間（分）",
                        verbose_name="深夜時間（分）",
                    ),
                ),
                (
                    "holiday_work_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="休日労働時間（分）",
                        verbose_name="休日労働時間（分）",
                    ),
                ),
                (
                    "paid_leave_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="0.5（半休）または1.0（全休）",
                        max_digits=3,
                        verbose_name="有給休暇日数",
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timecards_direct",
                        to="contract.staffcontract",
                        verbose_name="スタッフ契約",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "work_time_pattern_work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timecards",
                        to="master.worktimepatternwork",
                        verbose_name="就業時間パターン",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timecards",
                        to="kintai.stafftimesheet",
                        verbose_name="月次勤怠",
                    ),
                ),
            ],
            options={
                "verbose_name": "日次勤怠",
                "verbose_name_plural": "日次勤怠",
                "db_table": "apps_kintai_staff_timecard",
                "ordering": ["work_date"],
            },
        ),
        migrations.AddIndex(
            model_name="stafftimerecord",
            index=models.Index(
                fields=["staff_contract"], name="apps_kintai_staff_c_624c9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimerecord",
            index=models.Index(fields=["staff"], name="apps_kintai_staff_i_94493a_idx"),
        ),
        migrations.AddIndex(
            model_name="stafftimerecord",
            index=models.Index(
                fields=["work_date"], name="apps_kintai_work_da_a2a6e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimerecord",
            index=models.Index(
                fields=["start_time"], name="apps_kintai_start_t_1207de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimerecord",
            index=models.Index(
                fields=["end_time"], name="apps_kintai_end_tim_dbc73f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stafftimerecord",
            unique_together={("staff_contract", "work_date")},
        ),
        migrations.AddIndex(
            model_name="stafftimerecordbreak",
            index=models.Index(
                fields=["timerecord"], name="apps_kintai_timerec_9149da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimerecordbreak",
            index=models.Index(
                fields=["break_start"], name="apps_kintai_break_s_f72bf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimerecordbreak",
            index=models.Index(
                fields=["break_end"], name="apps_kintai_break_e_5464ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimesheet",
            index=models.Index(
                fields=["staff_contract"], name="apps_kintai_staff_c_0f16fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimesheet",
            index=models.Index(fields=["staff"], name="apps_kintai_staff_i_4d2b31_idx"),
        ),
        migrations.AddIndex(
            model_name="stafftimesheet",
            index=models.Index(
                fields=["target_month"], name="apps_kintai_target__97a128_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimesheet",
            index=models.Index(fields=["status"], name="apps_kintai_status_0b517d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="stafftimesheet",
            unique_together={("staff_contract", "target_month")},
        ),
        migrations.AddIndex(
            model_name="stafftimecard",
            index=models.Index(
                fields=["timesheet"], name="apps_kintai_timeshe_d513f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimecard",
            index=models.Index(
                fields=["staff_contract"], name="apps_kintai_staff_c_8e304a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimecard",
            index=models.Index(
                fields=["work_date"], name="apps_kintai_work_da_93fb82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stafftimecard",
            index=models.Index(
                fields=["work_type"], name="apps_kintai_work_ty_014ab0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stafftimecard",
            unique_together={("staff_contract", "work_date")},
        ),
    ]
