# Generated by Django 5.2.8 on 2025-11-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftimesheet',
            name='memo',
        ),
    ]
