# Generated by Django 5.2.8 on 2026-02-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kintai", "0002_stafftimerecord_end_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stafftimerecord",
            name="end_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="終了位置（緯度）",
            ),
        ),
        migrations.AlterField(
            model_name="stafftimerecord",
            name="end_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="終了位置（経度）",
            ),
        ),
        migrations.AlterField(
            model_name="stafftimerecord",
            name="start_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="開始位置（緯度）",
            ),
        ),
        migrations.AlterField(
            model_name="stafftimerecord",
            name="start_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="開始位置（経度）",
            ),
        ),
        migrations.AlterField(
            model_name="stafftimerecordbreak",
            name="end_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="終了位置（緯度）",
            ),
        ),
        migrations.AlterField(
            model_name="stafftimerecordbreak",
            name="end_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="終了位置（経度）",
            ),
        ),
        migrations.AlterField(
            model_name="stafftimerecordbreak",
            name="start_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="開始位置（緯度）",
            ),
        ),
        migrations.AlterField(
            model_name="stafftimerecordbreak",
            name="start_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                verbose_name="開始位置（経度）",
            ),
        ),
    ]
