# Generated by Django 5.2.8 on 2025-11-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0002_add_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftimecard',
            name='work_type',
            field=models.CharField(choices=[('10', '出勤'), ('20', '休日'), ('30', '欠勤'), ('40', '有給休暇'), ('50', '特別休暇'), ('60', '代休'), ('70', '稼働無し')], default='10', max_length=2, verbose_name='勤務区分'),
        ),
    ]
