# Generated by Django 5.2.8 on 2025-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kintai", "0002_remove_stafftimesheet_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftimecard",
            name="late_night_overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="深夜残業時間（時間）",
                max_digits=5,
                verbose_name="深夜時間",
            ),
        ),
        migrations.AddField(
            model_name="stafftimesheet",
            name="total_late_night_overtime_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="深夜時間"
            ),
        ),
    ]
