# Generated by Django 5.2.8 on 2025-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0003_alter_stafftimecard_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimecard',
            name='end_time_next_day',
            field=models.BooleanField(default=False, verbose_name='退勤時刻翌日'),
        ),
        migrations.AddField(
            model_name='stafftimecard',
            name='start_time_next_day',
            field=models.BooleanField(default=False, verbose_name='出勤時刻翌日'),
        ),
    ]
