# Generated by Django 5.2.8 on 2025-11-20 15:08

from django.db import migrations, models
from django.db.models import F

def convert_hours_to_minutes(apps, schema_editor):
    """
    Populate the new '_minutes' fields by converting the values from
    the old '_hours' fields (multiplied by 60).
    """
    StaffTimecard = apps.get_model("kintai", "StaffTimecard")
    StaffTimesheet = apps.get_model("kintai", "StaffTimesheet")
    db_alias = schema_editor.connection.alias

    StaffTimecard.objects.using(db_alias).all().update(
        work_minutes=F('work_hours') * 60,
        overtime_minutes=F('overtime_hours') * 60,
        late_night_overtime_minutes=F('late_night_overtime_hours') * 60,
        holiday_work_minutes=F('holiday_work_hours') * 60,
    )

    StaffTimesheet.objects.using(db_alias).all().update(
        total_work_minutes=F('total_work_hours') * 60,
        total_overtime_minutes=F('total_overtime_hours') * 60,
        total_late_night_overtime_minutes=F('total_late_night_overtime_hours') * 60,
        total_holiday_work_minutes=F('total_holiday_work_hours') * 60,
    )

def convert_minutes_to_hours(apps, schema_editor):
    """
    Reverse operation: Populate the old '_hours' fields from the '_minutes' fields.
    This function is used for rollbacks.
    """
    StaffTimecard = apps.get_model("kintai", "StaffTimecard")
    StaffTimesheet = apps.get_model("kintai", "StaffTimesheet")
    db_alias = schema_editor.connection.alias

    StaffTimecard.objects.using(db_alias).all().update(
        work_hours=F('work_minutes') / 60.0,
        overtime_hours=F('overtime_minutes') / 60.0,
        late_night_overtime_hours=F('late_night_overtime_minutes') / 60.0,
        holiday_work_hours=F('holiday_work_minutes') / 60.0,
    )

    StaffTimesheet.objects.using(db_alias).all().update(
        total_work_hours=F('total_work_minutes') / 60.0,
        total_overtime_hours=F('total_overtime_minutes') / 60.0,
        total_late_night_overtime_hours=F('total_late_night_overtime_minutes') / 60.0,
        total_holiday_work_hours=F('total_holiday_work_minutes') / 60.0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("kintai", "0003_stafftimecard_late_night_overtime_hours_and_more"),
    ]

    operations = [
        # Step 1: Add the new '_minutes' fields
        migrations.AddField(
            model_name="stafftimecard",
            name="holiday_work_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="休日労働時間（分）", verbose_name="休日労働時間（分）"
            ),
        ),
        migrations.AddField(
            model_name="stafftimecard",
            name="late_night_overtime_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="深夜残業時間（分）", verbose_name="深夜時間（分）"
            ),
        ),
        migrations.AddField(
            model_name="stafftimecard",
            name="overtime_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="残業時間（分）", verbose_name="残業時間（分）"
            ),
        ),
        migrations.AddField(
            model_name="stafftimecard",
            name="work_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="実労働時間（分）", verbose_name="労働時間（分）"
            ),
        ),
        migrations.AddField(
            model_name="stafftimesheet",
            name="total_holiday_work_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="休日労働時間（分）"),
        ),
        migrations.AddField(
            model_name="stafftimesheet",
            name="total_late_night_overtime_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="深夜時間（分）"),
        ),
        migrations.AddField(
            model_name="stafftimesheet",
            name="total_overtime_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="残業時間（分）"),
        ),
        migrations.AddField(
            model_name="stafftimesheet",
            name="total_work_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="総労働時間（分）"),
        ),

        # Step 2: Run the data migration
        migrations.RunPython(convert_hours_to_minutes, convert_minutes_to_hours),

        # Step 3: Remove the old '_hours' fields
        migrations.RemoveField(
            model_name="stafftimecard",
            name="holiday_work_hours",
        ),
        migrations.RemoveField(
            model_name="stafftimecard",
            name="late_night_overtime_hours",
        ),
        migrations.RemoveField(
            model_name="stafftimecard",
            name="overtime_hours",
        ),
        migrations.RemoveField(
            model_name="stafftimecard",
            name="work_hours",
        ),
        migrations.RemoveField(
            model_name="stafftimesheet",
            name="total_holiday_work_hours",
        ),
        migrations.RemoveField(
            model_name="stafftimesheet",
            name="total_late_night_overtime_hours",
        ),
        migrations.RemoveField(
            model_name="stafftimesheet",
            name="total_overtime_hours",
        ),
        migrations.RemoveField(
            model_name="stafftimesheet",
            name="total_work_hours",
        ),
    ]
