# Generated by Django 5.2.8 on 2026-02-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kintai", "0003_alter_stafftimerecord_end_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stafftimerecordbreak",
            name="break_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="休憩開始時刻"
            ),
        ),
    ]
