# Generated by Django 5.2.8 on 2026-02-11 08:00

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
        ("kintai", "0004_alter_stafftimerecordbreak_break_start"),
        ("staff", "0004_staffpayroll_basic_pension_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffTimerecordApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("closing_date", models.DateField(verbose_name="締め日")),
                ("period_start", models.DateField(verbose_name="締期間開始")),
                ("period_end", models.DateField(verbose_name="締期間終了")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("10", "作成中"),
                            ("20", "提出済み"),
                            ("30", "承認済み"),
                            ("40", "差戻し"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="承認ステータス",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timerecord_approvals",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "staff_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timerecord_approvals",
                        to="contract.staffcontract",
                        verbose_name="スタッフ契約",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "勤怠申請承認",
                "verbose_name_plural": "勤怠申請承認",
                "db_table": "apps_kintai_staff_timerecord_approval",
                "ordering": ["-closing_date", "staff"],
                "indexes": [
                    models.Index(
                        fields=["staff"], name="apps_kintai_staff_i_d2845e_idx"
                    ),
                    models.Index(
                        fields=["staff_contract"], name="apps_kintai_staff_c_626893_idx"
                    ),
                    models.Index(
                        fields=["closing_date"], name="apps_kintai_closing_56aa16_idx"
                    ),
                    models.Index(
                        fields=["status"], name="apps_kintai_status_5ca52c_idx"
                    ),
                ],
            },
        ),
    ]
