# Generated by Django 5.2.8 on 2025-11-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kintai", "0004_remove_stafftimecard_holiday_work_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftimecard",
            name="late_night_break_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="深夜休憩（分）"),
        ),
    ]
