# Generated by Django 5.2.8 on 2025-11-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0004_stafftimecard_end_time_next_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftimecard',
            name='early_leave_minutes',
        ),
        migrations.RemoveField(
            model_name='stafftimecard',
            name='late_minutes',
        ),
        migrations.RemoveField(
            model_name='stafftimesheet',
            name='total_early_leave_minutes',
        ),
        migrations.RemoveField(
            model_name='stafftimesheet',
            name='total_late_minutes',
        ),
    ]
