# Generated by Django 5.2.8 on 2026-02-14 16:59

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_clientfavorite"),
        ("contract", "0001_initial"),
        ("kintai", "0005_stafftimerecordapproval"),
        (
            "master",
            "0003_rename_apps_master_is_acti_98aa7a_idx_apps_master_is_acti_be8d5c_idx_and_more",
        ),
        ("staff", "0004_staffpayroll_basic_pension_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "target_month",
                    models.DateField(
                        help_text="対象年月の1日を設定してください。",
                        verbose_name="対象年月",
                    ),
                ),
                (
                    "total_work_days",
                    models.PositiveIntegerField(default=0, verbose_name="出勤日数"),
                ),
                (
                    "total_work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="総労働時間（分）"
                    ),
                ),
                (
                    "total_overtime_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="残業時間（分）"
                    ),
                ),
                (
                    "total_late_night_overtime_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="深夜時間（分）"
                    ),
                ),
                (
                    "total_holiday_work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="休日労働時間（分）"
                    ),
                ),
                (
                    "total_premium_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="月単位時間範囲での割増時間",
                        verbose_name="割増時間（分）",
                    ),
                ),
                (
                    "total_deduction_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="月単位時間範囲での控除時間",
                        verbose_name="控除時間（分）",
                    ),
                ),
                (
                    "total_variable_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="1ヶ月単位変形労働での月次法定超過時間",
                        verbose_name="変形時間（分）",
                    ),
                ),
                (
                    "total_absence_days",
                    models.PositiveIntegerField(default=0, verbose_name="欠勤日数"),
                ),
                (
                    "total_paid_leave_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="有給休暇日数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("10", "作成中"),
                            ("20", "提出済み"),
                            ("30", "承認済み"),
                            ("40", "差戻し"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提出日時"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="差戻し日時"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True, verbose_name="差戻し理由"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_client_timesheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_timesheets",
                        to="client.client",
                        verbose_name="クライアント",
                    ),
                ),
                (
                    "client_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_timesheets",
                        to="contract.clientcontract",
                        verbose_name="クライアント契約",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_client_timesheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="差戻し者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_timesheets",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_client_timesheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提出者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント月次勤怠",
                "verbose_name_plural": "クライアント月次勤怠",
                "db_table": "apps_kintai_client_timesheet",
                "ordering": [
                    "-target_month",
                    "client__name",
                    "staff__name_last",
                    "staff__name_first",
                ],
            },
        ),
        migrations.CreateModel(
            name="ClientTimecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("work_date", models.DateField(verbose_name="勤務日")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("10", "出勤"),
                            ("20", "休日"),
                            ("30", "欠勤"),
                            ("40", "有給休暇"),
                            ("50", "特別休暇"),
                            ("60", "代休"),
                            ("70", "稼働無し"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="勤務区分",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="出勤時刻"),
                ),
                (
                    "start_time_next_day",
                    models.BooleanField(default=False, verbose_name="出勤時刻翌日"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="退勤時刻"),
                ),
                (
                    "end_time_next_day",
                    models.BooleanField(default=False, verbose_name="退勤時刻翌日"),
                ),
                (
                    "break_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="休憩時間（分）"
                    ),
                ),
                (
                    "late_night_break_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="深夜休憩（分）"
                    ),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="実労働時間（分）",
                        verbose_name="労働時間（分）",
                    ),
                ),
                (
                    "overtime_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="残業時間（分）",
                        verbose_name="残業時間（分）",
                    ),
                ),
                (
                    "late_night_overtime_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="深夜残業時間（分）",
                        verbose_name="深夜時間（分）",
                    ),
                ),
                (
                    "holiday_work_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="休日労働時間（分）",
                        verbose_name="休日労働時間（分）",
                    ),
                ),
                (
                    "paid_leave_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="0.5（半休）または1.0（全休）",
                        max_digits=3,
                        verbose_name="有給休暇日数",
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "client_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_timecards_direct",
                        to="contract.clientcontract",
                        verbose_name="クライアント契約",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_timecards",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "work_time_pattern_work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_timecards",
                        to="master.worktimepatternwork",
                        verbose_name="就業時間パターン",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timecards",
                        to="kintai.clienttimesheet",
                        verbose_name="クライアント月次勤怠",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント日次勤怠",
                "verbose_name_plural": "クライアント日次勤怠",
                "db_table": "apps_kintai_client_timecard",
                "ordering": ["work_date"],
            },
        ),
        migrations.AddIndex(
            model_name="clienttimesheet",
            index=models.Index(
                fields=["client_contract"], name="apps_kintai_client__5f33ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttimesheet",
            index=models.Index(
                fields=["client"], name="apps_kintai_client__7c5489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttimesheet",
            index=models.Index(fields=["staff"], name="apps_kintai_staff_i_74c866_idx"),
        ),
        migrations.AddIndex(
            model_name="clienttimesheet",
            index=models.Index(
                fields=["target_month"], name="apps_kintai_target__f42e61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttimesheet",
            index=models.Index(fields=["status"], name="apps_kintai_status_e9226f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clienttimesheet",
            unique_together={("client_contract", "staff", "target_month")},
        ),
        migrations.AddIndex(
            model_name="clienttimecard",
            index=models.Index(
                fields=["timesheet"], name="apps_kintai_timeshe_2d6798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttimecard",
            index=models.Index(
                fields=["client_contract"], name="apps_kintai_client__a4b40f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttimecard",
            index=models.Index(fields=["staff"], name="apps_kintai_staff_i_e471d6_idx"),
        ),
        migrations.AddIndex(
            model_name="clienttimecard",
            index=models.Index(
                fields=["work_date"], name="apps_kintai_work_da_7e0f32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttimecard",
            index=models.Index(
                fields=["work_type"], name="apps_kintai_work_ty_2be986_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clienttimecard",
            unique_together={("client_contract", "staff", "work_date")},
        ),
    ]
