# Generated by Django 5.2.6 on 2025-11-24 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_clientcontract_overtime_pattern'),
        ('kintai', '0005_stafftimecard_late_night_break_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stafftimecard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stafftimecard',
            name='staff_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timecards_direct', to='contract.staffcontract', verbose_name='スタッフ契約'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stafftimecard',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecards', to='kintai.stafftimesheet', verbose_name='月次勤怠'),
        ),
        migrations.AlterUniqueTogether(
            name='stafftimecard',
            unique_together={('staff_contract', 'work_date')},
        ),
        migrations.AddIndex(
            model_name='stafftimecard',
            index=models.Index(fields=['staff_contract'], name='apps_kintai_staff_c_8e304a_idx'),
        ),
    ]
