# Generated by Django 5.2.6 on 2026-02-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0006_clienttimesheet_clienttimecard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttimecard',
            name='paid_leave_days',
        ),
        migrations.AlterField(
            model_name='clienttimecard',
            name='work_type',
            field=models.CharField(choices=[('10', '出勤'), ('20', '休日'), ('30', '欠勤'), ('70', '稼働無し')], default='10', max_length=2, verbose_name='勤務区分'),
        ),
    ]
