# Generated by Django 5.2.6 on 2025-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0006_alter_stafftimecard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimesheet',
            name='total_deduction_minutes',
            field=models.PositiveIntegerField(default=0, help_text='月単位時間範囲での控除時間', verbose_name='控除時間（分）'),
        ),
        migrations.AddField(
            model_name='stafftimesheet',
            name='total_premium_minutes',
            field=models.PositiveIntegerField(default=0, help_text='月単位時間範囲での割増時間', verbose_name='割増時間（分）'),
        ),
    ]
