# Generated by Django 5.2.8 on 2025-11-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0007_stafftimesheet_total_deduction_minutes_and_more'),
        ('master', '0031_add_flexible_overtime_minutes_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimecard',
            name='work_time_pattern_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timecards', to='master.worktimepatternwork', verbose_name='就業時間パターン'),
        ),
    ]
