# Generated by Django 5.2.6 on 2026-02-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0007_remove_clienttimecard_paid_leave_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttimesheet',
            name='total_paid_leave_days',
        ),
    ]
