# Generated by Django 5.2.6 on 2025-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0008_stafftimecard_work_time_pattern_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimesheet',
            name='total_variable_minutes',
            field=models.PositiveIntegerField(default=0, help_text='1ヶ月単位変形労働での月次法定超過時間', verbose_name='変形時間（分）'),
        ),
    ]
