# Generated by Django 5.2.8 on 2025-12-30 17:00

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0009_stafftimesheet_total_variable_minutes'),
        ('staff', '0004_staffevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTimerecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='開始位置（緯度）')),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='開始位置（経度）')),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='終了位置（緯度）')),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='終了位置（経度）')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timerecords', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '勤怠打刻',
                'verbose_name_plural': '勤怠打刻',
                'db_table': 'apps_kintai_staff_timerecord',
                'ordering': ['-work_date', 'staff__name_last', 'staff__name_first'],
            },
        ),
        migrations.CreateModel(
            name='StaffTimerecordBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('break_start', models.DateTimeField(verbose_name='休憩開始時刻')),
                ('break_end', models.DateTimeField(verbose_name='休憩終了時刻')),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='開始位置（緯度）')),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='開始位置（経度）')),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='終了位置（緯度）')),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='終了位置（経度）')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('timerecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='kintai.stafftimerecord', verbose_name='勤怠打刻')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '休憩時間',
                'verbose_name_plural': '休憩時間',
                'db_table': 'apps_kintai_staff_timerecord_break',
                'ordering': ['break_start'],
            },
        ),
        migrations.AddIndex(
            model_name='stafftimerecord',
            index=models.Index(fields=['staff'], name='apps_kintai_staff_i_94493a_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimerecord',
            index=models.Index(fields=['work_date'], name='apps_kintai_work_da_a2a6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimerecord',
            index=models.Index(fields=['start_time'], name='apps_kintai_start_t_1207de_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimerecord',
            index=models.Index(fields=['end_time'], name='apps_kintai_end_tim_dbc73f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stafftimerecord',
            unique_together={('staff', 'work_date')},
        ),
        migrations.AddIndex(
            model_name='stafftimerecordbreak',
            index=models.Index(fields=['timerecord'], name='apps_kintai_timerec_9149da_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimerecordbreak',
            index=models.Index(fields=['break_start'], name='apps_kintai_break_s_f72bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimerecordbreak',
            index=models.Index(fields=['break_end'], name='apps_kintai_break_e_5464ba_idx'),
        ),
    ]
