# Generated by Django 5.2.8 on 2025-12-30 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_clientcontract_overtime_pattern'),
        ('kintai', '0010_stafftimerecord_stafftimerecordbreak_and_more'),
        ('staff', '0004_staffevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stafftimerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stafftimerecord',
            name='staff_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timerecords', to='contract.staffcontract', verbose_name='スタッフ契約'),
        ),
        migrations.AlterUniqueTogether(
            name='stafftimerecord',
            unique_together={('staff_contract', 'work_date')},
        ),
        migrations.AddIndex(
            model_name='stafftimerecord',
            index=models.Index(fields=['staff_contract'], name='apps_kintai_staff_c_624c9f_idx'),
        ),
    ]
