# Generated by Django 5.2.8 on 2025-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0011_alter_stafftimerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftimerecord',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='終了位置（緯度）'),
        ),
        migrations.AlterField(
            model_name='stafftimerecord',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='終了位置（経度）'),
        ),
        migrations.AlterField(
            model_name='stafftimerecord',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='開始位置（緯度）'),
        ),
        migrations.AlterField(
            model_name='stafftimerecord',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='開始位置（経度）'),
        ),
        migrations.AlterField(
            model_name='stafftimerecordbreak',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='終了位置（緯度）'),
        ),
        migrations.AlterField(
            model_name='stafftimerecordbreak',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='終了位置（経度）'),
        ),
        migrations.AlterField(
            model_name='stafftimerecordbreak',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='開始位置（緯度）'),
        ),
        migrations.AlterField(
            model_name='stafftimerecordbreak',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='開始位置（経度）'),
        ),
    ]
