# Generated by Django 5.2.6 on 2025-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0012_alter_stafftimerecord_end_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftimerecordbreak',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='休憩終了時刻'),
        ),
    ]
