# Generated by Django 5.2.8 on 2026-01-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0013_alter_stafftimerecordbreak_break_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimerecord',
            name='rounded_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='丸め終了時刻'),
        ),
        migrations.AddField(
            model_name='stafftimerecord',
            name='rounded_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='丸め開始時刻'),
        ),
        migrations.AddField(
            model_name='stafftimerecordbreak',
            name='rounded_break_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='丸め休憩終了時刻'),
        ),
        migrations.AddField(
            model_name='stafftimerecordbreak',
            name='rounded_break_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='丸め休憩開始時刻'),
        ),
    ]
