# Generated by Django 5.2.8 on 2026-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kintai", "0014_stafftimerecord_rounded_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftimecard",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="stafftimesheet",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
    ]
