# Generated by Django 5.2.8 on 2026-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='テナントID'),
        ),
    ]
