# Generated by Copilot: Remove phone_number from MyUser
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="phone_number",
        ),
    ]
