# Generated by Django 5.2.7 on 2025-10-18 15:21

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.CharField(default='', max_length=50, verbose_name='カテゴリ')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('value', models.CharField(max_length=100, verbose_name='設定値')),
                ('disp_seq', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プルダウン',
                'verbose_name_plural': 'プルダウン',
                'db_table': 'apps_system_dropdowns',
                'ordering': ['category', 'disp_seq'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('icon', models.CharField(max_length=100, verbose_name='アイコン')),
                ('icon_style', models.CharField(max_length=100, verbose_name='アイコンスタイル')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='階層レベル')),
                ('exact_match', models.BooleanField(default=False, help_text='URLの完全一致判定を行う', verbose_name='完全一致')),
                ('required_permission', models.CharField(blank=True, help_text='例: staff.view_staff (空欄の場合は全員アクセス可能)', max_length=100, null=True, verbose_name='必要な権限')),
                ('disp_seq', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.menu', verbose_name='親メニュー')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'メニュー',
                'verbose_name_plural': 'メニュー',
                'db_table': 'apps_system_menu',
                'ordering': ['level', 'disp_seq'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.CharField(default='', max_length=50, verbose_name='分類')),
                ('key', models.CharField(max_length=100, verbose_name='キー')),
                ('value', models.CharField(max_length=100, verbose_name='設定値')),
                ('default_value', models.CharField(max_length=100, verbose_name='初期値')),
                ('note', models.CharField(max_length=100, verbose_name='備考')),
                ('disp_seq', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'パラメータ',
                'verbose_name_plural': 'パラメータ',
                'db_table': 'apps_system_parameter',
                'ordering': ['category', 'disp_seq'],
            },
        ),
    ]
