# Generated by Django 5.2.5 on 2025-08-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['level', 'disp_seq'], 'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー'},
        ),
        migrations.AddField(
            model_name='menu',
            name='exact_match',
            field=models.BooleanField(default=False, help_text='URLの完全一致判定を行う', verbose_name='完全一致'),
        ),
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='階層レベル'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.menu', verbose_name='親メニュー'),
        ),
    ]
