# Generated by Django 5.2.5 on 2025-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_menu_options_menu_exact_match_menu_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='required_permission',
            field=models.CharField(blank=True, help_text='例: staff.view_staff (空欄の場合は全員アクセス可能)', max_length=100, null=True, verbose_name='必要な権限'),
        ),
    ]
