# Generated by Django 5.1.2 on 2024-11-11 13:42

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('corporate_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='法人番号')),
                ('name', models.TextField(db_comment='会社名（正式名称）')),
                ('name_furigana', models.TextField(db_comment='会社名カナ')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号')),
                ('address_kana', models.TextField(blank=True, null=True, verbose_name='住所カナ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='電話番号')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-MAIL')),
                ('url', models.TextField(blank=True, db_comment='URL', null=True)),
                ('memo', models.TextField(blank=True, db_comment='メモ', null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント',
                'db_table': 'apps_client',
            },
        ),
    ]
