# Generated by Django 5.2.7 on 2025-10-18 15:21

import apps.client.models
import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('corporate_number', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='法人番号')),
                ('name', models.TextField(verbose_name='会社名')),
                ('name_furigana', models.TextField(verbose_name='会社名カナ')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号')),
                ('address_kana', models.TextField(blank=True, null=True, verbose_name='住所カナ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('basic_contract_date', models.DateField(blank=True, null=True, verbose_name='基本契約締結日(業務委託)')),
                ('basic_contract_date_haken', models.DateField(blank=True, null=True, verbose_name='基本契約締結日(人材派遣)')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('payment_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.billpayment', verbose_name='支払いサイト')),
                ('regist_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.clientregiststatus', verbose_name='登録区分')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント',
                'db_table': 'apps_client',
            },
        ),
        migrations.CreateModel(
            name='ClientDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='組織名')),
                ('department_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='組織コード')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='住所')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('is_haken_office', models.BooleanField(default=False, verbose_name='派遣事業所該当')),
                ('is_haken_unit', models.BooleanField(default=False, verbose_name='派遣組織単位該当')),
                ('haken_unit_manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='派遣組織単位長役職')),
                ('haken_jigyosho_teishokubi', models.DateField(blank=True, null=True, verbose_name='派遣事業所抵触日')),
                ('haken_jigyosho_teishokubi_notice_date', models.DateField(blank=True, null=True, verbose_name='事業所抵触日通知日')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('valid_from', models.DateField(blank=True, help_text='未入力の場合は無期限', null=True, verbose_name='有効期限開始日')),
                ('valid_to', models.DateField(blank=True, help_text='未入力の場合は無期限', null=True, verbose_name='有効期限終了日')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント組織',
                'verbose_name_plural': 'クライアント組織',
                'db_table': 'apps_client_department',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name_last', models.CharField(max_length=50, verbose_name='姓')),
                ('name_first', models.CharField(max_length=50, verbose_name='名')),
                ('name_kana_last', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓カナ')),
                ('name_kana_first', models.CharField(blank=True, max_length=50, null=True, verbose_name='名カナ')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='役職')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='client.clientdepartment', verbose_name='所属組織')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント担当者',
                'verbose_name_plural': 'クライアント担当者',
                'db_table': 'apps_client_user',
                'ordering': ['display_order', 'name_last', 'name_first'],
            },
        ),
        migrations.CreateModel(
            name='ClientContacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contacted_at', models.DateTimeField(verbose_name='連絡日時')),
                ('content', models.CharField(max_length=255, verbose_name='対応内容')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='対応詳細')),
                ('contact_type', models.IntegerField(blank=True, null=True, verbose_name='連絡種別')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_histories', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_histories', to='client.clientdepartment', verbose_name='組織')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_histories', to='client.clientuser', verbose_name='担当者')),
            ],
            options={
                'verbose_name': 'クライアント連絡履歴',
                'verbose_name_plural': 'クライアント連絡履歴',
                'db_table': 'apps_client_contacted',
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('file', models.FileField(help_text='添付ファイル（最大10MB）', upload_to=apps.client.models.client_file_upload_path, verbose_name='ファイル')),
                ('original_filename', models.CharField(help_text='アップロード時の元のファイル名', max_length=255, verbose_name='元ファイル名')),
                ('file_size', models.PositiveIntegerField(help_text='バイト単位', verbose_name='ファイルサイズ')),
                ('description', models.CharField(blank=True, help_text='ファイルの説明（任意）', max_length=255, null=True, verbose_name='説明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアントファイル',
                'verbose_name_plural': 'クライアントファイル',
                'db_table': 'apps_client_file',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['client'], name='apps_client_client__b4d28e_idx'), models.Index(fields=['uploaded_at'], name='apps_client_uploade_82d93b_idx')],
            },
        ),
    ]
