# Generated by Django 5.2.8 on 2025-11-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdepartment",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commander_departments",
                to="client.clientuser",
                verbose_name="派遣先指揮命令者",
            ),
        ),
        migrations.AddField(
            model_name="clientdepartment",
            name="complaint_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaint_officer_departments",
                to="client.clientuser",
                verbose_name="派遣先苦情申出先",
            ),
        ),
        migrations.AddField(
            model_name="clientdepartment",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_person_departments",
                to="client.clientuser",
                verbose_name="派遣先責任者",
            ),
        ),
    ]
