# Generated by Django 5.2.1 on 2025-07-23
from django.db import migrations
import concurrency.fields

class Migration(migrations.Migration):
    dependencies = [
        ('client', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='client',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0),
        ),
    ]
