# Generated by Django 5.2.6 on 2026-01-23 16:40

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientdepartment_commander_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContactSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contact_date', models.DateField(verbose_name='連絡日')),
                ('content', models.CharField(max_length=255, verbose_name='対応内容')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='対応詳細')),
                ('contact_type', models.IntegerField(blank=True, null=True, verbose_name='連絡種別')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_schedules', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_schedules', to='client.clientdepartment', verbose_name='組織')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_schedules', to='client.clientuser', verbose_name='担当者')),
            ],
            options={
                'verbose_name': 'クライアント連絡予定',
                'verbose_name_plural': 'クライアント連絡予定',
                'db_table': 'apps_client_contact_schedule',
                'ordering': ['-contact_date'],
            },
        ),
    ]
