# Generated by Django 5.1.2 on 2024-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_email_remove_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='regist_form_client',
            field=models.IntegerField(blank=True, null=True, verbose_name='登録区分'),
        ),
    ]
