# Generated by Django 5.2.8 on 2026-01-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_tenant_id_clientcontacted_tenant_id_and_more'),
        ('master', '0047_clienttag_stafftag'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='master.clienttag', verbose_name='タグ'),
        ),
    ]
