# Generated by Django 5.2.8 on 2026-01-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_client_tenant_id_clientcontacted_tenant_id_and_more"),
        ("master", "0046_clientcontacttype_staffcontacttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontacted",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.clientcontacttype",
                verbose_name="連絡種別",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontactschedule",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.clientcontacttype",
                verbose_name="連絡種別",
            ),
        ),
    ]
