# Generated by Django 5.2.8 on 2026-01-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_client_tags"),
        ("master", "0047_clienttag_stafftag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontacted",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.clientcontacttype",
                verbose_name="連絡種別",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontactschedule",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.clientcontacttype",
                verbose_name="連絡種別",
            ),
        ),
    ]
