# Generated by Django 5.1.2 on 2024-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_corporate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='法人番号'),
        ),
    ]
