# Generated by Django 5.2.1 on 2025-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_corporate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='法人番号'),
        ),
    ]
