# Generated by Django 5.2.1 on 2025-07-12 17:35

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_corporate_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contacted_at', models.DateTimeField(auto_now_add=True, verbose_name='連絡日時')),
                ('content', models.CharField(max_length=255, verbose_name='対応内容')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='対応詳細')),
                ('contact_type', models.IntegerField(blank=True, null=True, verbose_name='連絡種別')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_histories', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント連絡履歴',
                'verbose_name_plural': 'クライアント連絡履歴',
                'db_table': 'apps_client_contacted',
                'ordering': ['-contacted_at'],
            },
        ),
    ]
