# Generated by Django 5.2.1 on 2025-07-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_version'),
        ('client', '0008_clientcontacted'),
    ]

    operations = [
    ]
