# Generated by Django 5.2.1 on 2025-07-23 15:10

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_merge_0002_client_version_0008_clientcontacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontacted',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
