# Generated by Django 5.2.4 on 2025-08-05 21:19

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_clientcontacted_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='組織名')),
                ('department_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='組織コード')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='住所')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント組織',
                'verbose_name_plural': 'クライアント組織',
                'db_table': 'apps_client_department',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name_last', models.CharField(max_length=50, verbose_name='姓')),
                ('name_first', models.CharField(max_length=50, verbose_name='名')),
                ('name_kana_last', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓カナ')),
                ('name_kana_first', models.CharField(blank=True, max_length=50, null=True, verbose_name='名カナ')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='役職')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='client.clientdepartment', verbose_name='所属組織')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント担当者',
                'verbose_name_plural': 'クライアント担当者',
                'db_table': 'apps_client_user',
                'ordering': ['display_order', 'name_last', 'name_first'],
            },
        ),
    ]
