# Generated by Django 5.2.4 on 2025-08-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_clientdepartment_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdepartment',
            name='valid_from',
            field=models.DateField(blank=True, help_text='未入力の場合は無期限', null=True, verbose_name='有効期限開始日'),
        ),
        migrations.AddField(
            model_name='clientdepartment',
            name='valid_to',
            field=models.DateField(blank=True, help_text='未入力の場合は無期限', null=True, verbose_name='有効期限終了日'),
        ),
    ]
