# Generated by Django 5.2.4 on 2025-08-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_clientdepartment_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdepartment',
            name='email',
        ),
        migrations.AddField(
            model_name='clientcontacted',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_histories', to='client.clientdepartment', verbose_name='組織'),
        ),
        migrations.AddField(
            model_name='clientcontacted',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_histories', to='client.clientuser', verbose_name='担当者'),
        ),
    ]
