# Generated by Django 5.2.4 on 2025-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='basic_contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='基本契約締結日'),
        ),
    ]
