# Generated by Django 5.2.4 on 2025-08-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_clientcontacted_contacted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='url',
        ),
    ]
