# Generated by Django 5.2.5 on 2025-08-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_client_payment_site'),
        ('master', '0006_remove_billbank_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.billpayment', verbose_name='支払いサイト'),
        ),
    ]
