# Generated by Django 5.2.6 on 2025-09-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0019_alter_client_payment_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="basic_contract_date_haken",
            field=models.DateField(
                blank=True, null=True, verbose_name="基本契約締結日(派遣)"
            ),
        ),
    ]
