# Generated by Django 5.2.6 on 2025-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_client_basic_contract_date_haken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='basic_contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='基本契約締結日(業務委託)'),
        ),
    ]
