# Generated by Django 5.2.6 on 2025-09-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0021_alter_client_basic_contract_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdepartment",
            name="haken_unit_manager_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="派遣組織単位長役職"
            ),
        ),
        migrations.AddField(
            model_name="clientdepartment",
            name="is_haken_office",
            field=models.BooleanField(default=False, verbose_name="派遣事業所該当"),
        ),
        migrations.AddField(
            model_name="clientdepartment",
            name="is_haken_unit",
            field=models.BooleanField(default=False, verbose_name="派遣組織単位該当"),
        ),
    ]
