# Generated by Django 5.2.6 on 2025-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0022_clientdepartment_haken_unit_manager_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdepartment",
            name="haken_jigyosho_teishokubi",
            field=models.DateField(
                blank=True, null=True, verbose_name="派遣事業所抵触日"
            ),
        ),
    ]
