# Generated by Django 5.2.7 on 2025-10-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_clientdepartment_haken_jigyosho_teishokubi'),
        ('master', '0036_clientregiststatus_staffregiststatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_regist_status',
        ),
        migrations.AddField(
            model_name='client',
            name='regist_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.clientregiststatus', verbose_name='登録区分'),
        ),
    ]
