# Generated by Django 5.2.7 on 2025-10-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_remove_client_client_regist_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdepartment',
            name='haken_jigyosho_teishokubi_notice_date',
            field=models.DateField(blank=True, null=True, verbose_name='事業所抵触日通知日'),
        ),
    ]
