# Generated by Django 5.2.7 on 2025-10-18 15:21

import apps.profile.models
import concurrency.fields
import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name_last', models.CharField(help_text='姓を入力してください', max_length=50, verbose_name='姓')),
                ('name_first', models.CharField(help_text='名を入力してください', max_length=50, verbose_name='名')),
                ('name_kana_last', models.CharField(help_text='姓をカタカナで入力してください', max_length=50, verbose_name='姓（カナ）')),
                ('name_kana_first', models.CharField(help_text='名をカタカナで入力してください', max_length=50, verbose_name='名（カナ）')),
                ('birth_date', models.DateField(blank=True, help_text='生年月日を入力してください', null=True, verbose_name='生年月日')),
                ('sex', models.IntegerField(blank=True, help_text='性別を選択してください', null=True, verbose_name='性別')),
                ('postal_code', models.CharField(blank=True, help_text='郵便番号を7桁の数字で入力してください（ハイフンなし）', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='郵便番号は7桁の数字で入力してください（ハイフンなし）', regex='^\\d{7}$')], verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, help_text='都道府県を入力してください', max_length=100, null=True, verbose_name='都道府県')),
                ('address2', models.CharField(blank=True, help_text='市区町村を入力してください', max_length=100, null=True, verbose_name='市区町村')),
                ('address3', models.CharField(blank=True, help_text='番地・建物名を入力してください', max_length=200, null=True, verbose_name='番地・建物名')),
                ('phone', models.CharField(blank=True, help_text='電話番号を入力してください', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='電話番号は数字とハイフンのみ入力可能です', regex='^[\\d\\-]+$')], verbose_name='電話番号')),
                ('email', models.EmailField(help_text='メールアドレス（ログインユーザーと同じ）', max_length=254, verbose_name='メールアドレス')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフプロフィール',
                'verbose_name_plural': 'スタッフプロフィール',
                'db_table': 'apps_profile_staff',
            },
        ),
        migrations.CreateModel(
            name='StaffProfileBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('bank_code', models.CharField(help_text='4桁の数字で入力', max_length=4, validators=[django.core.validators.RegexValidator(message='銀行コードは4桁の数字で入力してください', regex='^\\d{4}$')], verbose_name='銀行コード')),
                ('branch_code', models.CharField(help_text='3桁の数字で入力', max_length=3, validators=[django.core.validators.RegexValidator(message='支店コードは3桁の数字で入力してください', regex='^\\d{3}$')], verbose_name='支店コード')),
                ('account_type', models.CharField(help_text='普通、当座など', max_length=10, verbose_name='口座種別')),
                ('account_number', models.CharField(help_text='1-8桁の数字で入力', max_length=8, validators=[django.core.validators.RegexValidator(message='口座番号は1-8桁の数字で入力してください', regex='^\\d{1,8}$')], verbose_name='口座番号')),
                ('account_holder', models.CharField(help_text='口座名義人の名前', max_length=100, verbose_name='口座名義')),
                ('document_file', models.FileField(blank=True, help_text='通帳の表紙など、銀行情報が確認できる書類をアップロードしてください。', null=True, upload_to=apps.profile.models.profile_bank_file_path, verbose_name='確認書類')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_bank', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフ銀行プロフィール',
                'verbose_name_plural': 'スタッフ銀行プロフィール',
                'db_table': 'apps_profile_staff_bank',
            },
        ),
        migrations.CreateModel(
            name='StaffProfileContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='緊急連絡先')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='続柄')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号（住民票）')),
                ('address1', models.TextField(blank=True, null=True, verbose_name='住所１（住民票）')),
                ('address2', models.TextField(blank=True, null=True, verbose_name='住所２（住民票）')),
                ('address3', models.TextField(blank=True, null=True, verbose_name='住所３（住民票）')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_contact_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_staff_contact_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contact', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフ連絡先情報プロフィール',
                'verbose_name_plural': 'スタッフ連絡先情報プロフィール',
                'db_table': 'apps_profile_staff_contacts',
            },
        ),
        migrations.CreateModel(
            name='StaffProfileDisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('email', models.EmailField(default='', help_text='メールアドレス（ログインユーザーと同じ）', max_length=254, verbose_name='メールアドレス')),
                ('disability_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='障害の種類')),
                ('disability_grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='等級')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_disability', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフ障害者情報',
                'verbose_name_plural': 'スタッフ障害者情報',
                'db_table': 'apps_profile_staff_disability',
            },
        ),
        migrations.CreateModel(
            name='StaffProfileInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('email', models.EmailField(default='', help_text='メールアドレス（ログインユーザーと同じ）', max_length=254, verbose_name='メールアドレス')),
                ('residence_card_number', models.CharField(help_text='在留カード番号を入力してください', max_length=20, verbose_name='在留カード番号')),
                ('residence_status', models.CharField(help_text='在留資格を入力してください', max_length=100, verbose_name='在留資格')),
                ('residence_period_from', models.DateField(help_text='在留許可の開始日を入力してください', verbose_name='在留許可開始日')),
                ('residence_period_to', models.DateField(help_text='在留期間の終了日（在留期限）を入力してください', verbose_name='在留期限')),
                ('residence_card_front', models.FileField(blank=True, null=True, upload_to=apps.profile.models.profile_international_file_path, verbose_name='在留カード（表面）')),
                ('residence_card_back', models.FileField(blank=True, null=True, upload_to=apps.profile.models.profile_international_file_path, verbose_name='在留カード（裏面）')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_international', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフ外国籍情報',
                'verbose_name_plural': 'スタッフ外国籍情報',
                'db_table': 'apps_profile_staff_international',
            },
        ),
        migrations.CreateModel(
            name='StaffProfileMynumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('email', models.EmailField(help_text='メールアドレス（ログインユーザーと同じ）', max_length=254, verbose_name='メールアドレス')),
                ('mynumber', models.CharField(help_text='マイナンバーを12桁の数字で入力してください', max_length=12, validators=[apps.profile.models.validate_mynumber, django.core.validators.RegexValidator(message='マイナンバーは12桁の数字で入力してください', regex='^\\d{12}$')], verbose_name='マイナンバー')),
                ('mynumber_card_front', models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_mynumber_file_path, verbose_name='マイナンバーカード表面')),
                ('mynumber_card_back', models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_mynumber_file_path, verbose_name='マイナンバーカード裏面')),
                ('identity_document_1', models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_mynumber_file_path, verbose_name='本人確認書類１')),
                ('identity_document_2', models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_mynumber_file_path, verbose_name='本人確認書類２')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_mynumber', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフマイナンバー',
                'verbose_name_plural': 'スタッフマイナンバー',
                'db_table': 'apps_profile_staff_mynumber',
            },
        ),
        migrations.CreateModel(
            name='StaffProfileQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='取得日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='証明書番号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('score', models.IntegerField(blank=True, help_text='TOEICの点数など', null=True, verbose_name='点数')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.qualification', verbose_name='資格')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='profile.staffprofile', verbose_name='スタッフプロフィール')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プロフィールスタッフ資格',
                'verbose_name_plural': 'プロフィールスタッフ資格',
                'db_table': 'apps_profile_staff_qualification',
                'ordering': ['-acquired_date'],
                'unique_together': {('staff_profile', 'qualification')},
            },
        ),
        migrations.CreateModel(
            name='StaffProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='習得日')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='経験年数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.skill', verbose_name='技能')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profile.staffprofile', verbose_name='スタッフプロフィール')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プロフィールスタッフ技能',
                'verbose_name_plural': 'プロフィールスタッフ技能',
                'db_table': 'apps_profile_staff_skill',
                'ordering': ['-acquired_date'],
                'unique_together': {('staff_profile', 'skill')},
            },
        ),
    ]
