# Generated by Django 5.2.5 on 2025-08-16 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_last', models.CharField(help_text='姓を入力してください', max_length=50, verbose_name='姓')),
                ('name_first', models.CharField(help_text='名を入力してください', max_length=50, verbose_name='名')),
                ('name_kana_last', models.CharField(help_text='姓をカタカナで入力してください', max_length=50, verbose_name='姓（カナ）')),
                ('name_kana_first', models.CharField(help_text='名をカタカナで入力してください', max_length=50, verbose_name='名（カナ）')),
                ('birth_date', models.DateField(blank=True, help_text='生年月日を入力してください', null=True, verbose_name='生年月日')),
                ('sex', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], help_text='性別を選択してください', max_length=1, null=True, verbose_name='性別')),
                ('postal_code', models.CharField(blank=True, help_text='郵便番号を7桁の数字で入力してください（ハイフンなし）', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='郵便番号は7桁の数字で入力してください（ハイフンなし）', regex='^\\d{7}$')], verbose_name='郵便番号')),
                ('address_kana', models.CharField(blank=True, help_text='住所をカタカナで入力してください', max_length=200, null=True, verbose_name='住所（カナ）')),
                ('address1', models.CharField(blank=True, help_text='都道府県を入力してください', max_length=100, null=True, verbose_name='都道府県')),
                ('address2', models.CharField(blank=True, help_text='市区町村を入力してください', max_length=100, null=True, verbose_name='市区町村')),
                ('address3', models.CharField(blank=True, help_text='番地・建物名を入力してください', max_length=200, null=True, verbose_name='番地・建物名')),
                ('phone', models.CharField(blank=True, help_text='電話番号を入力してください', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='電話番号は数字とハイフンのみ入力可能です', regex='^[\\d\\-]+$')], verbose_name='電話番号')),
                ('email', models.EmailField(help_text='メールアドレス（ログインユーザーと同じ）', max_length=254, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフプロフィール',
                'verbose_name_plural': 'スタッフプロフィール',
                'db_table': 'apps_profile_staff',
            },
        ),
    ]
