# Generated by Django 5.2.5 on 2025-08-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_staffprofile_created_by_staffprofile_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='sex',
            field=models.CharField(blank=True, help_text='性別を選択してください', max_length=1, null=True, verbose_name='性別'),
        ),
    ]
