# Generated by Django 5.2.5 on 2025-08-18 21:28

import apps.profile.models
import concurrency.fields
import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_make_bill_bank_codes_required'),
        ('profile', '0004_staffmynumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmynumber',
            name='mynumber',
            field=models.CharField(help_text='マイナンバーを12桁の数字で入力してください', max_length=12, validators=[apps.profile.models.validate_mynumber, django.core.validators.RegexValidator(message='マイナンバーは12桁の数字で入力してください', regex='^\\d{12}$')], verbose_name='マイナンバー'),
        ),
        migrations.CreateModel(
            name='StaffProfileQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='取得日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='証明書番号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('score', models.IntegerField(blank=True, help_text='TOEICの点数など', null=True, verbose_name='点数')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.qualification', verbose_name='資格')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='profile.staffprofile', verbose_name='スタッフプロフィール')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プロフィールスタッフ資格',
                'verbose_name_plural': 'プロフィールスタッフ資格',
                'db_table': 'apps_profile_staff_qualification',
                'ordering': ['-acquired_date'],
                'unique_together': {('staff_profile', 'qualification')},
            },
        ),
        migrations.CreateModel(
            name='StaffProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='習得日')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='経験年数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.skill', verbose_name='技能')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profile.staffprofile', verbose_name='スタッフプロフィール')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プロフィールスタッフ技能',
                'verbose_name_plural': 'プロフィールスタッフ技能',
                'db_table': 'apps_profile_staff_skill',
                'ordering': ['-acquired_date'],
                'unique_together': {('staff_profile', 'skill')},
            },
        ),
    ]
