# Generated by Django 5.2.5 on 2025-08-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_alter_staffmynumber_mynumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofile",
            name="address_kana",
        ),
    ]
