# Generated by Django Copilot on 2025-08-21
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_remove_staffprofile_address_kana"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StaffMynumber",
            new_name="StaffProfileMynumber",
        ),
    ]
