# Generated by Django 5.2.5 on 2025-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_rename_staffmynumber_staffprofilemynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='sex',
            field=models.IntegerField(blank=True, help_text='性別を選択してください', null=True, verbose_name='性別'),
        ),
    ]
