# Generated by Django 5.2.5 on 2025-08-25 15:21

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_alter_staffprofile_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfileInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('residence_card_number', models.CharField(help_text='在留カード番号を入力してください', max_length=20, verbose_name='在留カード番号')),
                ('residence_status', models.CharField(help_text='在留資格を入力してください', max_length=100, verbose_name='在留資格')),
                ('residence_period_from', models.DateField(help_text='在留許可の開始日を入力してください', verbose_name='在留許可開始日')),
                ('residence_period_to', models.DateField(help_text='在留期間の終了日（在留期限）を入力してください', verbose_name='在留期限')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international', to='profile.staffprofile', verbose_name='スタッフプロフィール')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ外国籍情報',
                'verbose_name_plural': 'スタッフ外国籍情報',
                'db_table': 'apps_profile_staff_international',
            },
        ),
    ]
