# Generated by Django 5.2.5 on 2025-08-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_staffprofileinternational'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofileinternational',
            name='staff_profile',
        ),
        migrations.AddField(
            model_name='staffprofileinternational',
            name='email',
            field=models.EmailField(default='', help_text='メールアドレス（ログインユーザーと同じ）', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='staffprofileinternational',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_international', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
            preserve_default=False,
        ),
    ]
