# Generated by Django 5.2.5 on 2025-08-26 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0014_staffprofilecontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofilecontact",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="連絡先メールアドレスを入力してください",
                max_length=254,
                null=True,
                verbose_name="メールアドレス",
            ),
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="備考"),
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="電話番号を入力してください",
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="電話番号は数字とハイフンのみ入力可能です",
                        regex="^[\\d\\-]+$",
                    )
                ],
                verbose_name="電話番号",
            ),
        ),
    ]
