# Generated by Django 5.2.5 on 2025-08-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0015_staffprofilecontact_email_staffcontact_notes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffprofilecontact",
            options={
                "verbose_name": "スタッフ連絡先情報プロフィール",
                "verbose_name_plural": "スタッフ連絡先情報プロフィール",
            },
        ),
        migrations.RemoveField(
            model_name="staffprofilecontact",
            name="email",
        ),
        migrations.RemoveField(
            model_name="staffprofilecontact",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="staffprofilecontact",
            name="phone",
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="address1",
            field=models.TextField(
                blank=True, null=True, verbose_name="住所１（住民票）"
            ),
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="address2",
            field=models.TextField(
                blank=True, null=True, verbose_name="住所２（住民票）"
            ),
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="address3",
            field=models.TextField(
                blank=True, null=True, verbose_name="住所３（住民票）"
            ),
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="緊急連絡先"
            ),
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="郵便番号（住民票）"
            ),
        ),
        migrations.AddField(
            model_name="staffprofilecontact",
            name="relationship",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="続柄"
            ),
        ),
    ]
