# Generated by Django 5.2.5 on 2025-08-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0016_alter_staffprofilecontact_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofiledisability",
            name="notes",
        ),
    ]
