# Generated by Django 5.2.5 on 2025-08-30 15:19

import apps.profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_alter_staffprofilebank_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofilemynumber',
            name='identity_document_1',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_files_path, verbose_name='本人確認書類１'),
        ),
        migrations.AddField(
            model_name='staffprofilemynumber',
            name='identity_document_2',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_files_path, verbose_name='本人確認書類２'),
        ),
        migrations.AddField(
            model_name='staffprofilemynumber',
            name='mynumber_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_files_path, verbose_name='マイナンバーカード裏面'),
        ),
        migrations.AddField(
            model_name='staffprofilemynumber',
            name='mynumber_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile.models.profile_files_path, verbose_name='マイナンバーカード表面'),
        ),
    ]
