# Generated by Django 5.2.5 on 2025-08-30 15:51

import apps.profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0020_staffprofilemynumber_identity_document_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofileinternational',
            name='residence_card_back',
            field=models.FileField(blank=True, null=True, upload_to=apps.profile.models.residence_card_path, verbose_name='在留カード（裏面）'),
        ),
        migrations.AddField(
            model_name='staffprofileinternational',
            name='residence_card_front',
            field=models.FileField(blank=True, null=True, upload_to=apps.profile.models.residence_card_path, verbose_name='在留カード（表面）'),
        ),
    ]
