# Generated by Django 5.2.5 on 2025-09-05 14:22

import apps.profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0021_staffprofileinternational_residence_card_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofilebank",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="通帳の表紙など、銀行情報が確認できる書類をアップロードしてください。",
                null=True,
                upload_to=apps.profile.models.profile_bank_file_path,
                verbose_name="確認書類",
            ),
        ),
    ]
