# Generated by Django 5.2.8 on 2026-02-01 21:55

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0001_initial"),
        ("profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        help_text="会社の法人番号",
                        max_length=13,
                        verbose_name="法人番号",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="スタッフのメールアドレス",
                        max_length=254,
                        verbose_name="メールアドレス",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "未承認"), ("approved", "承認済み")],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_staff_connections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ接続",
                "verbose_name_plural": "スタッフ接続",
                "db_table": "apps_connect_staff",
                "ordering": ["-created_at"],
                "unique_together": {("corporate_number", "email")},
            },
        ),
        migrations.CreateModel(
            name="ConnectClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        help_text="会社の法人番号",
                        max_length=13,
                        verbose_name="法人番号",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="クライアントのメールアドレス",
                        max_length=254,
                        verbose_name="メールアドレス",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "未承認"), ("approved", "承認済み")],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_client_connections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント接続",
                "verbose_name_plural": "クライアント接続",
                "db_table": "apps_connect_client",
                "ordering": ["-created_at"],
                "unique_together": {("corporate_number", "email")},
            },
        ),
        migrations.CreateModel(
            name="ConnectInternationalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未承認"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        help_text="申請の現在のステータス",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "profile_international",
                    models.ForeignKey(
                        help_text="関連するプロフィール外国籍情報",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.staffprofileinternational",
                        verbose_name="プロフィール外国籍情報",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "connect_staff",
                    models.ForeignKey(
                        help_text="関連するスタッフ接続",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect.connectstaff",
                        verbose_name="スタッフ接続",
                    ),
                ),
            ],
            options={
                "verbose_name": "外国籍情報申請",
                "verbose_name_plural": "外国籍情報申請",
                "db_table": "apps_connect_international_request",
                "ordering": ["-created_at"],
                "unique_together": {("connect_staff", "profile_international")},
            },
        ),
        migrations.CreateModel(
            name="BankRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未承認"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        help_text="申請の現在のステータス",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff_bank_profile",
                    models.ForeignKey(
                        help_text="関連するスタッフ銀行プロフィール",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.staffprofilebank",
                        verbose_name="スタッフ銀行プロフィール",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "connect_staff",
                    models.ForeignKey(
                        help_text="関連するスタッフ接続",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect.connectstaff",
                        verbose_name="スタッフ接続",
                    ),
                ),
            ],
            options={
                "verbose_name": "銀行情報申請",
                "verbose_name_plural": "銀行情報申請",
                "db_table": "apps_connect_bank_request",
                "ordering": ["-created_at"],
                "unique_together": {("connect_staff", "staff_bank_profile")},
            },
        ),
        migrations.CreateModel(
            name="ConnectStaffAgree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="メールアドレス"),
                ),
                (
                    "corporate_number",
                    models.CharField(max_length=13, verbose_name="法人番号"),
                ),
                (
                    "is_agreed",
                    models.BooleanField(default=False, verbose_name="同意有無"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.staffagreement",
                        verbose_name="スタッフ同意文言",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ同意",
                "verbose_name_plural": "スタッフ同意",
                "db_table": "apps_connect_staff_agree",
                "ordering": ["-created_at"],
                "unique_together": {("email", "corporate_number", "staff_agreement")},
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未承認"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        help_text="申請の現在のステータス",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "connect_staff",
                    models.ForeignKey(
                        help_text="関連するスタッフ接続",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect.connectstaff",
                        verbose_name="スタッフ接続",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff_profile_contact",
                    models.ForeignKey(
                        help_text="関連するスタッフ連絡先情報プロフィール",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.staffprofilecontact",
                        verbose_name="スタッフ連絡先情報プロフィール",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "連絡先情報接続申請",
                "verbose_name_plural": "連絡先情報接続申請",
                "db_table": "apps_connect_contact_request",
                "ordering": ["-created_at"],
                "unique_together": {("connect_staff", "staff_profile_contact")},
            },
        ),
        migrations.CreateModel(
            name="DisabilityRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未承認"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        help_text="申請の現在のステータス",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "connect_staff",
                    models.ForeignKey(
                        help_text="関連するスタッフ接続",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect.connectstaff",
                        verbose_name="スタッフ接続",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "profile_disability",
                    models.ForeignKey(
                        help_text="関連するプロフィール障害者情報",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.staffprofiledisability",
                        verbose_name="プロフィール障害者情報",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "障害者情報申請",
                "verbose_name_plural": "障害者情報申請",
                "db_table": "apps_connect_disability_request",
                "ordering": ["-created_at"],
                "unique_together": {("connect_staff", "profile_disability")},
            },
        ),
        migrations.CreateModel(
            name="MynumberRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未承認"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        help_text="申請の現在のステータス",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "connect_staff",
                    models.ForeignKey(
                        help_text="関連するスタッフ接続",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect.connectstaff",
                        verbose_name="スタッフ接続",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "profile_mynumber",
                    models.ForeignKey(
                        help_text="関連するプロフィールマイナンバー",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.staffprofilemynumber",
                        verbose_name="プロフィールマイナンバー",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "マイナンバー申請",
                "verbose_name_plural": "マイナンバー申請",
                "db_table": "apps_connect_mynumber_request",
                "ordering": ["-created_at"],
                "unique_together": {("connect_staff", "profile_mynumber")},
            },
        ),
        migrations.CreateModel(
            name="ProfileRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未承認"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        help_text="申請の現在のステータス",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "connect_staff",
                    models.ForeignKey(
                        help_text="関連するスタッフ接続",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect.connectstaff",
                        verbose_name="スタッフ接続",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "staff_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="関連するスタッフプロフィール",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.staffprofile",
                        verbose_name="スタッフプロフィール",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロフィール申請",
                "verbose_name_plural": "プロフィール申請",
                "db_table": "apps_connect_profile_request",
                "ordering": ["-created_at"],
                "unique_together": {("connect_staff", "staff_profile")},
            },
        ),
    ]
