# Generated by Django 5.2.5 on 2025-08-14 11:35

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('corporate_number', models.CharField(help_text='会社の法人番号', max_length=13, verbose_name='法人番号')),
                ('email', models.EmailField(help_text='クライアントのメールアドレス', max_length=254, verbose_name='メールアドレス')),
                ('status', models.CharField(choices=[('pending', '未承認'), ('approved', '承認済み')], default='pending', max_length=20, verbose_name='ステータス')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_client_connections', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント接続',
                'verbose_name_plural': 'クライアント接続',
                'db_table': 'apps_connect_client',
                'ordering': ['-created_at'],
                'unique_together': {('corporate_number', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ConnectStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('corporate_number', models.CharField(help_text='会社の法人番号', max_length=13, verbose_name='法人番号')),
                ('email', models.EmailField(help_text='スタッフのメールアドレス', max_length=254, verbose_name='メールアドレス')),
                ('status', models.CharField(choices=[('pending', '未承認'), ('approved', '承認済み')], default='pending', max_length=20, verbose_name='ステータス')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_connections', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ接続',
                'verbose_name_plural': 'スタッフ接続',
                'db_table': 'apps_connect_staff',
                'ordering': ['-created_at'],
                'unique_together': {('corporate_number', 'email')},
            },
        ),
    ]
