# Generated by Django 5.2.7 on 2025-11-05 18:24

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
        ('contract', '0013_clientcontractprint_file_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffContractConfirmRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('document_type', models.CharField(choices=[('staff_contract', 'スタッフ契約書'), ('employment_conditions', '就業条件明示書')], help_text='確認対象の書類種別', max_length=25, verbose_name='書類種別')),
                ('status', models.CharField(choices=[('pending', '未確認'), ('confirmed', '確認済み')], default='pending', help_text='確認状況', max_length=20, verbose_name='ステータス')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('assignment_haken_print', models.ForeignKey(blank=True, help_text='就業条件明示書の場合の印刷履歴', null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractassignmenthakenprint', verbose_name='就業条件明示書印刷履歴')),
                ('connect_staff', models.ForeignKey(help_text='関連するスタッフ接続', on_delete=django.db.models.deletion.CASCADE, to='connect.connectstaff', verbose_name='スタッフ接続')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff_contract_print', models.ForeignKey(blank=True, help_text='スタッフ契約書の場合の印刷履歴', null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.staffcontractprint', verbose_name='スタッフ契約書印刷履歴')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ契約確認要求',
                'verbose_name_plural': 'スタッフ契約確認要求',
                'db_table': 'apps_connect_staff_contract_confirm_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['connect_staff', 'status'], name='apps_connec_connect_a75146_idx'), models.Index(fields=['document_type', 'status'], name='apps_connec_documen_60943e_idx')],
            },
        ),
    ]
