# Generated by Django 5.2.7 on 2025-11-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_staffcontractconfirmrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffContractConfirmRequest',
        ),
    ]
