# Generated by Django 5.2.5 on 2025-08-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0003_profilerequest"),
        ("profile", "0007_rename_staffmynumber_staffprofilemynumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilerequest",
            name="staff_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="関連するスタッフプロフィール",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profile.staffprofile",
                verbose_name="スタッフプロフィール",
            ),
        ),
    ]
