# Generated by Django 5.2.5 on 2025-08-26 16:42

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0006_bankrequest"),
        ("profile", "0015_staffprofilecontact_email_staffcontact_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisabilityRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未承認"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        help_text="申請の現在のステータス",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "connect_staff",
                    models.ForeignKey(
                        help_text="関連するスタッフ接続",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect.connectstaff",
                        verbose_name="スタッフ接続",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "profile_disability",
                    models.ForeignKey(
                        help_text="関連するプロフィール障害者情報",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.staffdisabilityprofile",
                        verbose_name="プロフィール障害者情報",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "障害者情報申請",
                "verbose_name_plural": "障害者情報申請",
                "db_table": "apps_connect_disability_request",
                "ordering": ["-created_at"],
                "unique_together": {("connect_staff", "profile_disability")},
            },
        ),
    ]
