# Generated by Django 5.2.5 on 2025-09-03 12:36

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_contactrequest'),
        ('master', '0016_staffagreement_corporation_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectStaffAgree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('corporate_number', models.CharField(max_length=13, verbose_name='法人番号')),
                ('is_agreed', models.BooleanField(default=False, verbose_name='同意有無')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.staffagreement', verbose_name='スタッフ同意文言')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ同意',
                'verbose_name_plural': 'スタッフ同意',
                'db_table': 'apps_connect_staff_agree',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'corporate_number', 'staff_agreement')},
            },
        ),
    ]
