# Generated by Django 5.2.5 on 2025-09-03 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0009_appsconnectstaffagree"),
        ("master", "0016_staffagreement_corporation_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AppsConnectStaffAgree",
            new_name="ConnectStaffAgree",
        ),
    ]
