# Generated by Django 5.2.1 on 2025-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applog',
            name='action',
            field=models.CharField(choices=[('create', '作成'), ('update', '編集'), ('delete', '削除'), ('login', 'ログイン'), ('logout', 'ログアウト'), ('view', '閲覧')], max_length=10),
        ),
    ]
