# Generated by Django 5.2.1 on 2025-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_applog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
