# Generated by Django 5.2.1 on 2025-08-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_applog_version'),
    ]

    operations = [
        # 旧AppLogテーブルを削除
        migrations.RunSQL(
            "DROP TABLE IF EXISTS common_applog;",
            reverse_sql="-- 旧AppLogテーブルの復元は手動で行ってください"
        ),
    ]
