# Generated by Django 5.2.4 on 2025-08-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20250801_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppLog',
        ),
    ]
