#!/usr/bin/env python
"""
サンプルデータ設定
サンプルデータのファイルリストを一元管理します。
"""

# サンプルデータファイルのリスト（読み込み順序）
# タプル形式: (ファイルパス, 説明)
SAMPLE_DATA_FILES = [
    ("_sample_data/groups.json", "グループデータ"),
    ("_sample_data/group_permissions.json", "グループ権限データ"),
    ("_sample_data/dropdowns.json", "ドロップダウンデータ"),
    ("_sample_data/parameters.json", "パラメータデータ"),
    ("_sample_data/master_user_parameter.json", "ユーザーパラメータマスタデータ"),
    ("_sample_data/menus.json", "メニューデータ"),
    ("_sample_data/master_qualifications.json", "資格マスタデータ"),
    ("_sample_data/master_skills.json", "技能マスタデータ"),
    ("_sample_data/master_bill_payment.json", "支払いサイトマスタデータ"),
    ("_sample_data/master_bill_bank.json", "会社銀行マスタデータ"),
    ("_sample_data/master_bank.json", "銀行マスタデータ"),
    ("_sample_data/master_bank_branch.json", "銀行支店マスタデータ"),
    ("_sample_data/master_staff_agreement.json", "スタッフ同意文言マスタデータ"),
    ("_sample_data/master_information.json", "お知らせマスタデータ"),
    ("_sample_data/master_mail_template.json", "メールテンプレートマスタデータ"),
    ("_sample_data/master_job_category.json", "職種マスタデータ"),
    ("_sample_data/master_minimum_pay.json", "最低賃金マスタデータ"),
    ("_sample_data/master_phrase_template_title.json", "汎用文言タイトルマスタデータ"),
    ("_sample_data/master_phrase_template.json", "汎用文言テンプレートマスタデータ"),
    ("_sample_data/master_default_value.json", "初期値マスタデータ"),
    ("_sample_data/master_client_regist_status.json", "クライアント登録ステータスマスタデータ"),
    ("_sample_data/master_staff_regist_status.json", "スタッフ登録ステータスマスタデータ"),
    ("_sample_data/master_worktime_pattern.json", "就業時間パターンマスタデータ"),
    ("_sample_data/master_worktime_pattern_work.json", "就業時間パターン勤務時間マスタデータ"),
    ("_sample_data/master_worktime_pattern_break.json", "就業時間パターン休憩時間マスタデータ"),
    ("_sample_data/master_overtime_pattern.json", "時間外算出パターンマスタデータ"),
    ("_sample_data/master_time_punch.json", "勤怠打刻マスタデータ"),
    ("_sample_data/master_employment_type.json", "雇用形態マスタデータ"),
    ("_sample_data/master_contract_pattern.json", "契約書パターンマスタデータ"),
    ("_sample_data/master_contract_terms.json", "契約文言マスタデータ"),
    ("_sample_data/master_generative_ai_setting.json", "生成AI設定マスタデータ"),
    ("_sample_data/company.json", "会社データ"),
    ("_sample_data/company_department.json", "部署データ"),
    ("_sample_data/company_user.json", "自社担当者データ"),
    ("_sample_data/staff.json", "スタッフデータ"),
    ("_sample_data/staff_international.json", "スタッフ外国籍情報データ"),
    ("_sample_data/staff_disability.json", "スタッフ障害者情報データ"),
    ("_sample_data/staff_contacted.json", "スタッフ連絡履歴データ"),
    ("_sample_data/staff_payroll.json", "スタッフ給与データ"),
    ("_sample_data/staff_evaluation.json", "スタッフ評価データ"),
    ("_sample_data/client.json", "クライアントデータ"),
    ("_sample_data/client_department.json", "クライアント組織データ"),
    ("_sample_data/client_user.json", "クライアント担当者データ"),
    ("_sample_data/client_contacted.json", "クライアント連絡履歴データ"),
    ("_sample_data/connect_client.json", "クライアント接続データ"),
    ("_sample_data/connect_staff.json", "スタッフ接続データ"),
    ("_sample_data/contract_client.json", "クライアント契約データ"),
    ("_sample_data/contract_client_haken.json", "クライアント契約派遣データ"),
    ("_sample_data/contract_staff.json", "スタッフ契約データ"),
    ("_sample_data/contract_assignment.json", "契約アサインメントデータ"),
    ("_sample_data/staff_inquiry.json", "スタッフ問い合わせデータ"),
    ("_sample_data/staff_inquiry_message.json", "スタッフ問い合わせメッセージデータ"),
]
