# Generated by Django 5.2.8 on 2026-02-01 21:55

import apps.company.models
import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="会社名"
                    ),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="法人番号",
                    ),
                ),
                (
                    "representative",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="代表者"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "haken_permit_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="許可番号(人材派遣)",
                    ),
                ),
                (
                    "shokai_permit_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="許可番号(職業紹介)",
                    ),
                ),
                (
                    "foreign_regist_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="登録番号(特定技能)",
                    ),
                ),
                (
                    "dispatch_treatment_method",
                    models.CharField(
                        choices=[
                            ("agreement", "労使協定方式"),
                            ("equal_balance", "派遣先均等・均衡方式"),
                        ],
                        default="agreement",
                        help_text="派遣労働者の待遇決定方式を選択してください",
                        max_length=20,
                        verbose_name="派遣待遇決定方式",
                    ),
                ),
                (
                    "round_seal",
                    models.ImageField(
                        blank=True,
                        help_text="契約書等に使用する丸印の画像 (600x600推奨)",
                        null=True,
                        upload_to=apps.company.models.company_seal_upload_path,
                        verbose_name="丸印",
                    ),
                ),
                (
                    "square_seal",
                    models.ImageField(
                        blank=True,
                        help_text="請求書等に使用する角印の画像 (600x600推奨)",
                        null=True,
                        upload_to=apps.company.models.company_seal_upload_path,
                        verbose_name="角印",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "会社",
                "verbose_name_plural": "会社",
                "db_table": "apps_company",
            },
        ),
        migrations.CreateModel(
            name="CompanyDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="部署名")),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=13,
                        null=True,
                        verbose_name="法人番号",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(max_length=20, verbose_name="部署コード"),
                ),
                (
                    "accounting_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="会計コード"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="住所"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="未入力の場合は無期限",
                        null=True,
                        verbose_name="有効期限開始日",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="未入力の場合は無期限",
                        null=True,
                        verbose_name="有効期限終了日",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "部署",
                "verbose_name_plural": "部署",
                "db_table": "apps_company_department",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=13,
                        null=True,
                        verbose_name="法人番号",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="部署コード",
                    ),
                ),
                ("name_last", models.CharField(max_length=50, verbose_name="姓")),
                ("name_first", models.CharField(max_length=50, verbose_name="名")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="役職"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="メールアドレス",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "自社担当者",
                "verbose_name_plural": "自社担当者",
                "db_table": "apps_company_user",
                "ordering": ["display_order", "name_last", "name_first"],
            },
        ),
    ]
