# Generated by Django 5.2.7 on 2025-10-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dispatch_treatment_method',
            field=models.CharField(choices=[('agreement', '労使協定方式'), ('equal_balance', '派遣先均等・均衡方式')], default='agreement', help_text='派遣労働者の待遇決定方式を選択してください', max_length=20, verbose_name='派遣待遇決定方式'),
        ),
    ]
