# Generated by Django 5.2.8 on 2026-02-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "permissions": [
                    ("view_business_summary", "業務サマリを表示できる"),
                    ("view_registration_status", "登録状況を表示できる"),
                ],
                "verbose_name": "会社",
                "verbose_name_plural": "会社",
            },
        ),
    ]
