# Generated by Django 5.2.4 on 2025-08-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydepartment',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号'),
        ),
    ]
