# Generated by Django 5.2.6 on 2026-01-10 15:01

import apps.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_dispatch_treatment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='round_seal',
            field=models.ImageField(blank=True, help_text='契約書等に使用する丸印の画像 (600x600推奨)', null=True, upload_to=apps.company.models.company_seal_upload_path, verbose_name='丸印'),
        ),
        migrations.AddField(
            model_name='company',
            name='square_seal',
            field=models.ImageField(blank=True, help_text='請求書等に使用する角印の画像 (600x600推奨)', null=True, upload_to=apps.company.models.company_seal_upload_path, verbose_name='角印'),
        ),
    ]
