# Generated by Django 5.2.4 on 2025-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companydepartment_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydepartment',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '部署', 'verbose_name_plural': '部署'},
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='description',
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='accounting_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='会計コード'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='department_code',
            field=models.CharField(default='DEPT001', max_length=20, unique=True, verbose_name='部署コード'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
