# Generated by Django 5.2.8 on 2026-01-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_company_round_seal_company_square_seal"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="companydepartment",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
    ]
