# Generated by Django 5.2.4 on 2025-08-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companydepartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydepartment',
            name='department_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='部署コード'),
        ),
    ]
