# Generated by Django 5.2.4 on 2025-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companydepartment_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydepartment',
            name='valid_from',
            field=models.DateField(blank=True, help_text='未入力の場合は無期限', null=True, verbose_name='有効期限開始日'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='valid_to',
            field=models.DateField(blank=True, help_text='未入力の場合は無期限', null=True, verbose_name='有効期限終了日'),
        ),
        migrations.AlterField(
            model_name='companydepartment',
            name='department_code',
            field=models.CharField(max_length=20, verbose_name='部署コード'),
        ),
        migrations.AlterField(
            model_name='companydepartment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部署名'),
        ),
    ]
