# Generated by Django 5.2.4 on 2025-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companydepartment_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='代表者'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='住所'),
        ),
    ]
