# Generated by Django 5.2.4 on 2025-08-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_representative_alter_company_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='url',
        ),
    ]
