# Generated by Django 5.2.5 on 2025-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_companyuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="name_kana_first",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="名カナ"
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="name_kana_last",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="姓カナ"
            ),
        ),
    ]
