# Generated by Django 5.2.5 on 2025-08-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companyuser_name_kana_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='name_kana_first',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='name_kana_last',
        ),
    ]
