# Generated by Django 5.2.5 on 2025-09-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_remove_companyuser_name_kana_first_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyuser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="companyuser",
            name="department",
        ),
        migrations.AddField(
            model_name="companydepartment",
            name="corporate_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=13,
                null=True,
                verbose_name="法人番号",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="corporate_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=13,
                null=True,
                verbose_name="法人番号",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="department_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="部署コード",
            ),
        ),
    ]
