# Generated by Django 5.2.6 on 2025-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_remove_companyuser_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="haken_permit_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="許可番号(人材派遣)"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="shokai_permit_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="許可番号(職業紹介)"
            ),
        ),
    ]
