# Generated by Django 5.2.7 on 2025-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_haken_permit_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='foreign_regist_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='登録番号(特定技能)'),
        ),
    ]
