# Generated by Django 5.2.8 on 2026-02-01 21:55

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="通知の見出し",
                        max_length=255,
                        verbose_name="通知タイトル",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="通知の本文", verbose_name="通知メッセージ"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "一般"),
                            ("alert", "アラート"),
                            ("info", "情報"),
                            ("warning", "警告"),
                        ],
                        default="general",
                        help_text="通知の種類",
                        max_length=20,
                        verbose_name="通知種別",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="ユーザーが通知を読んだかどうか",
                        verbose_name="既読フラグ",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="通知に関連するページへのリンク（オプション）",
                        max_length=500,
                        null=True,
                        verbose_name="リンクURL",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="ユーザーが通知を読んだ日時",
                        null=True,
                        verbose_name="既読日時",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="通知を受け取るユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="対象ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "apps_system_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="apps_system_user_id_680d99_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="apps_system_user_id_71fdd8_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="apps_system_notific_889d8e_idx",
                    ),
                ],
            },
        ),
    ]
