# Generated by Django 5.2.8 on 2026-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tenant_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='テナントID'),
        ),
    ]
