# Generated by Django 5.2.5 on 2025-08-09 13:18

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0017_remove_client_url'),
        ('staff', '0021_staff_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contract_name', models.CharField(max_length=200, verbose_name='契約名')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='契約番号')),
                ('contract_type', models.CharField(choices=[('service', 'サービス契約'), ('maintenance', '保守契約'), ('development', '開発契約'), ('consulting', 'コンサルティング契約'), ('other', 'その他')], default='service', max_length=20, verbose_name='契約種別')),
                ('start_date', models.DateField(verbose_name='契約開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='契約金額')),
                ('payment_terms', models.CharField(blank=True, max_length=200, null=True, verbose_name='支払条件')),
                ('description', models.TextField(blank=True, null=True, verbose_name='契約内容')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='自動更新')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='client.client', verbose_name='クライアント')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'クライアント契約',
                'verbose_name_plural': 'クライアント契約',
                'db_table': 'apps_contract_client',
                'ordering': ['-start_date', 'client__name'],
                'indexes': [models.Index(fields=['client'], name='apps_contra_client__d9e26d_idx'), models.Index(fields=['start_date'], name='apps_contra_start_d_05b55f_idx'), models.Index(fields=['end_date'], name='apps_contra_end_dat_dbec5d_idx'), models.Index(fields=['is_active'], name='apps_contra_is_acti_5259ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contract_name', models.CharField(max_length=200, verbose_name='契約名')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='契約番号')),
                ('contract_type', models.CharField(choices=[('full_time', '正社員'), ('part_time', 'パートタイム'), ('contract', '契約社員'), ('freelance', 'フリーランス'), ('intern', 'インターン'), ('other', 'その他')], default='full_time', max_length=20, verbose_name='契約種別')),
                ('start_date', models.DateField(verbose_name='契約開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='契約金額')),
                ('payment_terms', models.CharField(blank=True, max_length=200, null=True, verbose_name='支払条件')),
                ('description', models.TextField(blank=True, null=True, verbose_name='契約内容')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='自動更新')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='staff.staff', verbose_name='スタッフ')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'スタッフ契約',
                'verbose_name_plural': 'スタッフ契約',
                'db_table': 'apps_contract_staff',
                'ordering': ['-start_date', 'staff__name_last', 'staff__name_first'],
                'indexes': [models.Index(fields=['staff'], name='apps_contra_staff_i_5f88df_idx'), models.Index(fields=['start_date'], name='apps_contra_start_d_96d49b_idx'), models.Index(fields=['end_date'], name='apps_contra_end_dat_cdd4e5_idx'), models.Index(fields=['is_active'], name='apps_contra_is_acti_b37ee6_idx')],
            },
        ),
    ]
