# Generated by Django 5.2.8 on 2026-02-01 21:55

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("company", "0001_initial"),
        ("master", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "client_contract_type_code",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="契約種別"
                    ),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="法人番号"
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(max_length=200, verbose_name="契約名"),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="契約番号"
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        blank=True,
                        default="1",
                        max_length=2,
                        null=True,
                        verbose_name="契約状況",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="契約開始日")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="契約終了日"),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="契約金額",
                    ),
                ),
                (
                    "bill_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="請求単位"
                    ),
                ),
                (
                    "business_content",
                    models.TextField(blank=True, null=True, verbose_name="業務内容"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="発行日時"
                    ),
                ),
                (
                    "quotation_issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="見積発行日時"
                    ),
                ),
                (
                    "teishokubi_notification_issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="抵触日通知書共有日時"
                    ),
                ),
                (
                    "dispatch_ledger_issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="派遣先管理台帳発行日時"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_client_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="client.client",
                        verbose_name="クライアント",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_client_contracts",
                        to="client.clientuser",
                        verbose_name="確認者",
                    ),
                ),
                (
                    "contract_pattern",
                    models.ForeignKey(
                        limit_choices_to={"domain": "10"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.contractpattern",
                        verbose_name="契約書パターン",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "dispatch_ledger_issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_dispatch_ledgers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="派遣先管理台帳発行者",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_client_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発行者",
                    ),
                ),
                (
                    "job_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.jobcategory",
                        verbose_name="職種",
                    ),
                ),
                (
                    "overtime_pattern",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.overtimepattern",
                        verbose_name="時間外算出",
                    ),
                ),
                (
                    "payment_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.billpayment",
                        verbose_name="支払いサイト",
                    ),
                ),
                (
                    "quotation_issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_client_quotations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="見積発行者",
                    ),
                ),
                (
                    "teishokubi_notification_issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_teishokubi_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="抵触日通知書共有者",
                    ),
                ),
                (
                    "time_punch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.timepunch",
                        verbose_name="勤怠打刻",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "worktime_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.worktimepattern",
                        verbose_name="就業時間",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約",
                "verbose_name_plural": "クライアント契約",
                "db_table": "apps_contract_client",
                "ordering": ["-start_date", "client__name"],
                "permissions": [
                    ("confirm_clientcontract", "クライアント契約を確認できる")
                ],
            },
        ),
        migrations.CreateModel(
            name="ClientContractHaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "limit_by_agreement",
                    models.CharField(
                        blank=True,
                        choices=[("0", "限定しない"), ("1", "限定する")],
                        max_length=1,
                        null=True,
                        verbose_name="協定対象派遣労働者に限定するか否かの別",
                    ),
                ),
                (
                    "limit_indefinite_or_senior",
                    models.CharField(
                        blank=True,
                        choices=[("0", "限定しない"), ("1", "限定する")],
                        max_length=1,
                        null=True,
                        verbose_name="無期雇用派遣労働者又は60歳以上の者に限定するか否かの別",
                    ),
                ),
                (
                    "work_location",
                    models.TextField(blank=True, null=True, verbose_name="就業場所"),
                ),
                (
                    "responsibility_degree",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="責任の程度"
                    ),
                ),
                (
                    "client_contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haken_info",
                        to="contract.clientcontract",
                        verbose_name="クライアント契約",
                    ),
                ),
                (
                    "commander",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_commanders",
                        to="client.clientuser",
                        verbose_name="派遣先指揮命令者",
                    ),
                ),
                (
                    "complaint_officer_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_complaint_officers_client",
                        to="client.clientuser",
                        verbose_name="派遣先苦情申出先",
                    ),
                ),
                (
                    "complaint_officer_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_complaint_officers_company",
                        to="company.companyuser",
                        verbose_name="派遣元苦情申出先",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "haken_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_offices",
                        to="client.clientdepartment",
                        verbose_name="派遣先事業所",
                    ),
                ),
                (
                    "haken_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_units",
                        to="client.clientdepartment",
                        verbose_name="組織単位",
                    ),
                ),
                (
                    "responsible_person_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_responsible_persons_client",
                        to="client.clientuser",
                        verbose_name="派遣先責任者",
                    ),
                ),
                (
                    "responsible_person_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_responsible_persons_company",
                        to="company.companyuser",
                        verbose_name="派遣元責任者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約派遣情報",
                "verbose_name_plural": "クライアント契約派遣情報",
                "db_table": "apps_contract_client_haken",
            },
        ),
        migrations.CreateModel(
            name="ClientContractHakenExempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "period_exempt_detail",
                    models.TextField(verbose_name="抵触日制限外詳細"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "haken",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haken_exempt_info",
                        to="contract.clientcontracthaken",
                        verbose_name="クライアント契約派遣情報",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約派遣抵触日制限外情報",
                "verbose_name_plural": "クライアント契約派遣抵触日制限外情報",
                "db_table": "apps_contract_client_haken_exempt",
            },
        ),
        migrations.CreateModel(
            name="ClientContractPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "print_type",
                    models.CharField(
                        choices=[
                            ("10", "契約書"),
                            ("20", "見積書"),
                            ("30", "抵触日通知書"),
                            ("40", "派遣先通知書"),
                            ("50", "派遣先管理台帳"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="種別",
                    ),
                ),
                (
                    "printed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発行日時"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="client_prints/",
                        verbose_name="PDFファイル",
                    ),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="タイトル"
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="契約番号"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="PDFファイルのSHA256ハッシュ値",
                        max_length=64,
                        null=True,
                        verbose_name="ファイルハッシュ",
                    ),
                ),
                (
                    "client_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_history",
                        to="contract.clientcontract",
                        verbose_name="クライアント契約",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発行者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約書発行履歴",
                "verbose_name_plural": "クライアント契約書発行履歴",
                "db_table": "apps_contract_client_print",
                "ordering": ["-printed_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientContractTtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "contract_period",
                    models.TextField(blank=True, null=True, verbose_name="契約期間"),
                ),
                (
                    "probation_period",
                    models.TextField(
                        blank=True, null=True, verbose_name="試用期間に関する事項"
                    ),
                ),
                (
                    "business_content",
                    models.TextField(blank=True, null=True, verbose_name="業務内容"),
                ),
                (
                    "work_location",
                    models.TextField(blank=True, null=True, verbose_name="就業場所"),
                ),
                (
                    "working_hours",
                    models.TextField(blank=True, null=True, verbose_name="始業・終業"),
                ),
                (
                    "break_time",
                    models.TextField(blank=True, null=True, verbose_name="休憩時間"),
                ),
                (
                    "overtime",
                    models.TextField(
                        blank=True, null=True, verbose_name="所定時間外労働"
                    ),
                ),
                (
                    "holidays",
                    models.TextField(blank=True, null=True, verbose_name="休日"),
                ),
                (
                    "vacations",
                    models.TextField(blank=True, null=True, verbose_name="休暇"),
                ),
                ("wages", models.TextField(blank=True, null=True, verbose_name="賃金")),
                (
                    "insurances",
                    models.TextField(
                        blank=True, null=True, verbose_name="各種保険の加入"
                    ),
                ),
                (
                    "employer_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="雇用しようとする者の名称"
                    ),
                ),
                (
                    "other",
                    models.TextField(blank=True, null=True, verbose_name="その他"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "haken",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ttp_info",
                        to="contract.clientcontracthaken",
                        verbose_name="クライアント契約派遣情報",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約紹介予定派遣情報",
                "verbose_name_plural": "クライアント契約紹介予定派遣情報",
                "db_table": "apps_contract_client_ttp",
            },
        ),
        migrations.CreateModel(
            name="ContractAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="アサイン日時"
                    ),
                ),
                (
                    "staff_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="スタッフメールアドレス",
                    ),
                ),
                (
                    "client_corporate_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        verbose_name="クライアント法人番号",
                    ),
                ),
                (
                    "assignment_start_date",
                    models.DateField(blank=True, null=True, verbose_name="割当開始日"),
                ),
                (
                    "assignment_end_date",
                    models.DateField(blank=True, null=True, verbose_name="割当終了日"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="発行日時"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
                (
                    "client_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contract.clientcontract",
                        verbose_name="クライアント契約",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "契約アサイン",
                "verbose_name_plural": "契約アサイン",
                "db_table": "apps_contract_assignment",
            },
        ),
        migrations.CreateModel(
            name="ContractAssignmentConfirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "confirm_type",
                    models.CharField(
                        choices=[("10", "延長予定"), ("90", "終了予定")],
                        help_text="延長予定か終了予定かを選択してください",
                        max_length=2,
                        verbose_name="確認種別",
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(
                        blank=True,
                        help_text="終了予定の場合は理由を入力してください",
                        null=True,
                        verbose_name="終了理由",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="確認日時"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備考")),
                (
                    "contract_assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_confirm",
                        to="contract.contractassignment",
                        verbose_name="契約アサイン",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "契約割り当て確認",
                "verbose_name_plural": "契約割り当て確認",
                "db_table": "apps_contract_assignment_confirm",
                "ordering": ["-confirmed_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractAssignmentFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="フラッグに関する詳細情報",
                        null=True,
                        verbose_name="詳細",
                    ),
                ),
                (
                    "company_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社組織",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companydepartment",
                        verbose_name="会社組織",
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社担当者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companyuser",
                        verbose_name="会社担当者",
                    ),
                ),
                (
                    "contract_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="contract.contractassignment",
                        verbose_name="契約アサイン",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "flag_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグのステータス",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.flagstatus",
                        verbose_name="フラッグステータス",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "契約アサインフラッグ",
                "verbose_name_plural": "契約アサインフラッグ",
                "db_table": "apps_contract_assignment_flag",
            },
        ),
        migrations.CreateModel(
            name="ContractAssignmentHaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "direct_employment_request",
                    models.BooleanField(
                        default=False,
                        help_text="派遣先への直接雇用の依頼を行うかどうか",
                        verbose_name="派遣先への直接雇用の依頼",
                    ),
                ),
                (
                    "direct_employment_detail",
                    models.TextField(
                        blank=True,
                        help_text="直接雇用の依頼に関する詳細情報",
                        null=True,
                        verbose_name="直接雇用依頼詳細",
                    ),
                ),
                (
                    "new_dispatch_offer",
                    models.BooleanField(
                        default=False,
                        help_text="新たな派遣先の提供を行うかどうか",
                        verbose_name="新たな派遣先の提供",
                    ),
                ),
                (
                    "new_dispatch_detail",
                    models.TextField(
                        blank=True,
                        help_text="新たな派遣先の提供に関する詳細情報",
                        null=True,
                        verbose_name="新派遣先提供詳細",
                    ),
                ),
                (
                    "indefinite_employment",
                    models.BooleanField(
                        default=False,
                        help_text="派遣元での無期雇用化を行うかどうか",
                        verbose_name="派遣元での無期雇用化",
                    ),
                ),
                (
                    "indefinite_employment_detail",
                    models.TextField(
                        blank=True,
                        help_text="派遣元での無期雇用化に関する詳細情報",
                        null=True,
                        verbose_name="無期雇用化詳細",
                    ),
                ),
                (
                    "other_measures",
                    models.BooleanField(
                        default=False,
                        help_text="その他の雇用安定措置を行うかどうか",
                        verbose_name="その他の雇用安定措置",
                    ),
                ),
                (
                    "other_measures_detail",
                    models.TextField(
                        blank=True,
                        help_text="その他の雇用安定措置に関する詳細情報",
                        null=True,
                        verbose_name="その他措置詳細",
                    ),
                ),
                (
                    "contract_assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haken_info",
                        to="contract.contractassignment",
                        verbose_name="契約アサイン",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "契約割り当て派遣雇用安定措置",
                "verbose_name_plural": "契約割り当て派遣雇用安定措置",
                "db_table": "apps_contract_assignment_haken",
            },
        ),
        migrations.CreateModel(
            name="ContractAssignmentHakenPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "print_type",
                    models.CharField(
                        choices=[("10", "就業条件明示書")],
                        default="10",
                        max_length=2,
                        verbose_name="種別",
                    ),
                ),
                (
                    "printed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発行日時"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignment_haken_prints/",
                        verbose_name="PDFファイル",
                    ),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="タイトル"
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="契約番号"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="PDFファイルのSHA256ハッシュ値",
                        max_length=64,
                        null=True,
                        verbose_name="ファイルハッシュ",
                    ),
                ),
                (
                    "contract_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haken_print_history",
                        to="contract.contractassignment",
                        verbose_name="契約アサイン",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発行者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "契約アサイン派遣印刷履歴",
                "verbose_name_plural": "契約アサイン派遣印刷履歴",
                "db_table": "apps_contract_assignment_haken_print",
                "ordering": ["-printed_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractClientFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="フラッグに関する詳細情報",
                        null=True,
                        verbose_name="詳細",
                    ),
                ),
                (
                    "client_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="contract.clientcontract",
                        verbose_name="クライアント契約",
                    ),
                ),
                (
                    "company_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社組織",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companydepartment",
                        verbose_name="会社組織",
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社担当者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companyuser",
                        verbose_name="会社担当者",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "flag_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグのステータス",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.flagstatus",
                        verbose_name="フラッグステータス",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約フラッグ",
                "verbose_name_plural": "クライアント契約フラッグ",
                "db_table": "apps_contract_client_flag",
            },
        ),
        migrations.CreateModel(
            name="StaffContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="法人番号"
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(max_length=200, verbose_name="契約名"),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="契約番号"
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        blank=True,
                        default="1",
                        max_length=2,
                        null=True,
                        verbose_name="契約状況",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="契約開始日")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="契約終了日"),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="契約金額",
                    ),
                ),
                (
                    "pay_unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="支払単位"
                    ),
                ),
                (
                    "work_location",
                    models.TextField(blank=True, null=True, verbose_name="就業場所"),
                ),
                (
                    "business_content",
                    models.TextField(blank=True, null=True, verbose_name="業務内容"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("memo", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="発行日時"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_staff_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "contract_pattern",
                    models.ForeignKey(
                        limit_choices_to={"domain": "1"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.contractpattern",
                        verbose_name="契約書パターン",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="契約作成時点のスタッフの雇用形態を保存",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.employmenttype",
                        verbose_name="雇用形態",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_staff_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発行者",
                    ),
                ),
                (
                    "job_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.jobcategory",
                        verbose_name="職種",
                    ),
                ),
                (
                    "overtime_pattern",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.overtimepattern",
                        verbose_name="時間外算出",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "time_punch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.timepunch",
                        verbose_name="勤怠打刻",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "worktime_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.worktimepattern",
                        verbose_name="就業時間",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ契約",
                "verbose_name_plural": "スタッフ契約",
                "db_table": "apps_contract_staff",
                "ordering": ["-start_date", "staff__name_last", "staff__name_first"],
                "permissions": [("confirm_staffcontract", "スタッフ契約を確認できる")],
            },
        ),
        migrations.CreateModel(
            name="ContractStaffFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="フラッグに関する詳細情報",
                        null=True,
                        verbose_name="詳細",
                    ),
                ),
                (
                    "company_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社組織",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companydepartment",
                        verbose_name="会社組織",
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグに関連する会社担当者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.companyuser",
                        verbose_name="会社担当者",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "flag_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="フラッグのステータス",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.flagstatus",
                        verbose_name="フラッグステータス",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "staff_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="contract.staffcontract",
                        verbose_name="スタッフ契約",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ契約フラッグ",
                "verbose_name_plural": "スタッフ契約フラッグ",
                "db_table": "apps_contract_staff_flag",
            },
        ),
        migrations.AddField(
            model_name="contractassignment",
            name="staff_contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contract.staffcontract",
                verbose_name="スタッフ契約",
            ),
        ),
        migrations.AddField(
            model_name="clientcontract",
            name="staff_contracts",
            field=models.ManyToManyField(
                related_name="client_contracts",
                through="contract.ContractAssignment",
                to="contract.staffcontract",
                verbose_name="関連スタッフ契約",
            ),
        ),
        migrations.CreateModel(
            name="StaffContractNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "employee_no",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="社員番号"
                    ),
                ),
                (
                    "year_month",
                    models.CharField(db_index=True, max_length=6, verbose_name="年月"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="最終番号"),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="法人番号"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ契約番号管理",
                "verbose_name_plural": "スタッフ契約番号管理",
                "db_table": "apps_contract_staff_number",
            },
        ),
        migrations.CreateModel(
            name="StaffContractPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "printed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発行日時"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="staff_prints/",
                        verbose_name="PDFファイル",
                    ),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="タイトル"
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="契約番号"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="PDFファイルのSHA256ハッシュ値",
                        max_length=64,
                        null=True,
                        verbose_name="ファイルハッシュ",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発行者",
                    ),
                ),
                (
                    "staff_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_history",
                        to="contract.staffcontract",
                        verbose_name="スタッフ契約",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ契約書発行履歴",
                "verbose_name_plural": "スタッフ契約書発行履歴",
                "db_table": "apps_contract_staff_print",
                "ordering": ["-printed_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffContractTeishokubi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "staff_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="スタッフメールアドレス",
                    ),
                ),
                (
                    "client_corporate_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        verbose_name="クライアント法人番号",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(max_length=255, verbose_name="組織名"),
                ),
                ("dispatch_start_date", models.DateField(verbose_name="派遣開始日")),
                ("conflict_date", models.DateField(verbose_name="抵触日")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "個人抵触日",
                "verbose_name_plural": "個人抵触日",
                "db_table": "apps_contract_staff_teishokubi",
                "ordering": ["-dispatch_start_date", "staff_email"],
            },
        ),
        migrations.CreateModel(
            name="StaffContractTeishokubiDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("assignment_start_date", models.DateField(verbose_name="割当開始日")),
                ("assignment_end_date", models.DateField(verbose_name="割当終了日")),
                (
                    "is_calculated",
                    models.BooleanField(default=True, verbose_name="算出対象"),
                ),
                (
                    "is_manual",
                    models.BooleanField(default=False, verbose_name="手動作成"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "teishokubi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="contract.staffcontractteishokubi",
                        verbose_name="個人抵触日",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "個人抵触日算出詳細",
                "verbose_name_plural": "個人抵触日算出詳細",
                "db_table": "apps_contract_staff_teishokubi_detail",
                "ordering": ["assignment_start_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientContractNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "client_code",
                    models.CharField(
                        db_index=True, max_length=8, verbose_name="クライアントコード"
                    ),
                ),
                (
                    "year_month",
                    models.CharField(db_index=True, max_length=6, verbose_name="年月"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="最終番号"),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="法人番号"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約番号管理",
                "verbose_name_plural": "クライアント契約番号管理",
                "db_table": "apps_contract_client_number",
                "unique_together": {("client_code", "year_month")},
            },
        ),
        migrations.AddIndex(
            model_name="staffcontract",
            index=models.Index(fields=["staff"], name="apps_contra_staff_i_5f88df_idx"),
        ),
        migrations.AddIndex(
            model_name="staffcontract",
            index=models.Index(
                fields=["start_date"], name="apps_contra_start_d_96d49b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcontract",
            index=models.Index(
                fields=["end_date"], name="apps_contra_end_dat_cdd4e5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractassignment",
            unique_together={("client_contract", "staff_contract")},
        ),
        migrations.AddIndex(
            model_name="clientcontract",
            index=models.Index(
                fields=["client"], name="apps_contra_client__d9e26d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontract",
            index=models.Index(
                fields=["start_date"], name="apps_contra_start_d_05b55f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontract",
            index=models.Index(
                fields=["end_date"], name="apps_contra_end_dat_dbec5d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffcontractnumber",
            unique_together={("employee_no", "year_month")},
        ),
    ]
