# Generated by Django 5.2.5 on 2025-08-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='payment_site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支払いサイト'),
        ),
    ]
