# Generated by Django 5.2.7 on 2025-10-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_clientcontracthakenexempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracthakenexempt',
            name='period_exempt_detail',
            field=models.TextField(verbose_name='抵触日制限外詳細'),
        ),
    ]
