# Generated by Django 5.2.5 on 2025-08-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_clientcontract_payment_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontract',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='staffcontract',
            name='payment_terms',
        ),
    ]
