# Generated by Django 5.2.7 on 2025-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_clientcontracthakenexempt_period_exempt_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractassignment',
            name='assignment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='割当終了日'),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='assignment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='割当開始日'),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='client_corporate_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='クライアント法人番号'),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='staff_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='スタッフメールアドレス'),
        ),
        migrations.AlterField(
            model_name='clientcontractprint',
            name='print_type',
            field=models.CharField(choices=[('10', '契約書'), ('20', '見積書'), ('30', '抵触日通知書'), ('40', '派遣先通知書')], default='10', max_length=2, verbose_name='種別'),
        ),
    ]
