# Generated by Django 5.2.7 on 2025-10-29 17:55

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contractassignment_assignment_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAssignmentConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('confirm_type', models.CharField(choices=[('1', '延長予定'), ('2', '終了予定')], help_text='延長予定か終了予定かを選択してください', max_length=2, verbose_name='確認種別')),
                ('termination_reason', models.TextField(blank=True, help_text='終了予定の場合は理由を入力してください', null=True, verbose_name='終了理由')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='確認日時')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('contract_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_confirm', to='contract.contractassignment', verbose_name='契約アサイン')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '契約割り当て確認',
                'verbose_name_plural': '契約割り当て確認',
                'db_table': 'apps_contract_assignment_confirm',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
