# Generated by Django 5.2.5 on 2025-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0004_remove_clientcontract_payment_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="contract_status",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="契約状況"
            ),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="contract_status",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="契約状況"
            ),
        ),
    ]
