# Generated by Django 5.2.5 on 2025-09-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0005_clientcontract_contract_status_and_more"),
        ("master", "0020_contractpattern_contractterms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="contract_pattern",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"contract_type": "client"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.contractpattern",
                verbose_name="契約パターン",
            ),
        ),
        migrations.AddField(
            model_name="clientcontract",
            name="job_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.jobcategory",
                verbose_name="職種",
            ),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="contract_pattern",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"contract_type": "staff"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.contractpattern",
                verbose_name="契約パターン",
            ),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="job_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master.jobcategory",
                verbose_name="職種",
            ),
        ),
    ]
