# Generated by Django 5.2.7 on 2025-10-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contractassignmentconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractassignmentconfirm',
            name='confirm_type',
            field=models.CharField(choices=[('10', '延長予定'), ('90', '終了予定')], help_text='延長予定か終了予定かを選択してください', max_length=2, verbose_name='確認種別'),
        ),
    ]
