# Generated by Django 5.2.5 on 2025-09-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0006_clientcontract_contract_pattern_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientcontract",
            name="contract_type",
        ),
        migrations.RemoveField(
            model_name="staffcontract",
            name="contract_type",
        ),
    ]
