# Generated by Django 5.2.7 on 2025-10-30 13:10

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_update_assignment_confirm_type_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAssignmentHaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('direct_employment_request', models.BooleanField(default=False, help_text='派遣先への直接雇用の依頼を行うかどうか', verbose_name='派遣先への直接雇用の依頼')),
                ('direct_employment_detail', models.TextField(blank=True, help_text='直接雇用の依頼に関する詳細情報', null=True, verbose_name='直接雇用依頼詳細')),
                ('new_dispatch_offer', models.BooleanField(default=False, help_text='新たな派遣先の提供を行うかどうか', verbose_name='新たな派遣先の提供')),
                ('new_dispatch_detail', models.TextField(blank=True, help_text='新たな派遣先の提供に関する詳細情報', null=True, verbose_name='新派遣先提供詳細')),
                ('indefinite_employment', models.BooleanField(default=False, help_text='派遣元での無期雇用化を行うかどうか', verbose_name='派遣元での無期雇用化')),
                ('indefinite_employment_detail', models.TextField(blank=True, help_text='派遣元での無期雇用化に関する詳細情報', null=True, verbose_name='無期雇用化詳細')),
                ('other_measures', models.BooleanField(default=False, help_text='その他の雇用安定措置を行うかどうか', verbose_name='その他の雇用安定措置')),
                ('other_measures_detail', models.TextField(blank=True, help_text='その他の雇用安定措置に関する詳細情報', null=True, verbose_name='その他措置詳細')),
                ('contract_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haken_info', to='contract.contractassignment', verbose_name='契約アサイン')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '契約割り当て派遣雇用安定措置',
                'verbose_name_plural': '契約割り当て派遣雇用安定措置',
                'db_table': 'apps_contract_assignment_haken',
            },
        ),
    ]
