# Generated by Django 5.2.7 on 2025-11-01 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_contractassignmenthaken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='dispatch_ledger_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='派遣先管理台帳発行日時'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='dispatch_ledger_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_dispatch_ledgers', to=settings.AUTH_USER_MODEL, verbose_name='派遣先管理台帳発行者'),
        ),
        migrations.AlterField(
            model_name='clientcontractprint',
            name='print_type',
            field=models.CharField(choices=[('10', '契約書'), ('20', '見積書'), ('30', '抵触日通知書'), ('40', '派遣先通知書'), ('50', '派遣先管理台帳')], default='10', max_length=2, verbose_name='種別'),
        ),
    ]
