# Generated by Django 5.2.5 on 2025-09-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_clientcontract_contract_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientcontract',
            name='apps_contra_is_acti_5259ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffcontract',
            name='apps_contra_is_acti_b37ee6_idx',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='auto_renewal',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffcontract',
            name='auto_renewal',
        ),
        migrations.RemoveField(
            model_name='staffcontract',
            name='is_active',
        ),
    ]
