# Generated by Django 5.2.7 on 2025-11-03 14:23

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_clientcontract_dispatch_ledger_issued_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAssignmentPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('print_type', models.CharField(choices=[('10', '就業条件明示書')], default='10', max_length=2, verbose_name='種別')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='assignment_prints/', verbose_name='PDFファイル')),
                ('document_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='タイトル')),
                ('is_draft', models.BooleanField(default=True, verbose_name='ドラフト版')),
                ('contract_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_history', to='contract.contractassignment', verbose_name='契約アサイン')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='発行者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '契約アサイン印刷履歴',
                'verbose_name_plural': '契約アサイン印刷履歴',
                'db_table': 'apps_contract_assignment_print',
                'ordering': ['-printed_at'],
            },
        ),
    ]
