# Generated by Django 5.2.5 on 2025-09-08 18:57

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0009_alter_clientcontract_contract_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcontract",
            name="contract_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "作成中"),
                    ("20", "申請中"),
                    ("30", "承認済"),
                    ("40", "発行済"),
                ],
                default="1",
                max_length=2,
                null=True,
                verbose_name="契約状況",
            ),
        ),
        migrations.CreateModel(
            name="StaffContractPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "printed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発行日時"),
                ),
                (
                    "pdf_file_path",
                    models.CharField(max_length=255, verbose_name="PDFファイル参照"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発行者",
                    ),
                ),
                (
                    "staff_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_history",
                        to="contract.staffcontract",
                        verbose_name="スタッフ契約",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ契約書発行履歴",
                "verbose_name_plural": "スタッフ契約書発行履歴",
                "db_table": "apps_contract_staff_print",
                "ordering": ["-printed_at"],
            },
        ),
    ]
