# Generated by Django 5.2.5 on 2025-09-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0010_alter_staffcontract_contract_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="corporate_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="法人番号"
            ),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="corporate_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="法人番号"
            ),
        ),
    ]
