# Generated by Django 5.2.7 on 2025-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_contractassignmenthakenprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractassignmenthakenprint',
            name='is_draft',
        ),
    ]
