# Generated by Django 5.2.7 on 2025-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_remove_contractassignmenthakenprint_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractassignmenthakenprint',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='契約番号'),
        ),
    ]
