# Generated by Django 5.2.5 on 2025-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0011_add_corporate_number_to_contracts"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcontract",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="承認日時"),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="確認日時"),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="発行日時"),
        ),
        migrations.AlterField(
            model_name="staffcontract",
            name="contract_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "作成中"),
                    ("20", "申請中"),
                    ("30", "承認済"),
                    ("40", "発行済"),
                    ("50", "確認済"),
                ],
                default="1",
                max_length=2,
                null=True,
                verbose_name="契約状況",
            ),
        ),
    ]
