# Generated by Django 5.2.7 on 2025-11-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_contractassignmenthakenprint_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontractprint',
            name='file_hash',
            field=models.CharField(blank=True, help_text='PDFファイルのSHA256ハッシュ値', max_length=64, null=True, verbose_name='ファイルハッシュ'),
        ),
        migrations.AddField(
            model_name='contractassignmenthakenprint',
            name='file_hash',
            field=models.CharField(blank=True, help_text='PDFファイルのSHA256ハッシュ値', max_length=64, null=True, verbose_name='ファイルハッシュ'),
        ),
        migrations.AddField(
            model_name='staffcontractprint',
            name='file_hash',
            field=models.CharField(blank=True, help_text='PDFファイルのSHA256ハッシュ値', max_length=64, null=True, verbose_name='ファイルハッシュ'),
        ),
    ]
