# Generated by Django 5.2.5 on 2025-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract",
            "0012_staffcontract_approved_at_staffcontract_confirmed_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="承認日時"),
        ),
        migrations.AddField(
            model_name="clientcontract",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="確認日時"),
        ),
        migrations.AddField(
            model_name="clientcontract",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="発行日時"),
        ),
    ]
