# Generated by Django 5.2.5 on 2025-09-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0013_clientcontract_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientcontract",
            options={
                "ordering": ["-start_date", "client__name"],
                "permissions": [
                    ("confirm_clientcontract", "クライアント契約を確認できる")
                ],
                "verbose_name": "クライアント契約",
                "verbose_name_plural": "クライアント契約",
            },
        ),
        migrations.AlterModelOptions(
            name="staffcontract",
            options={
                "ordering": ["-start_date", "staff__name_last", "staff__name_first"],
                "permissions": [("confirm_staffcontract", "スタッフ契約を確認できる")],
                "verbose_name": "スタッフ契約",
                "verbose_name_plural": "スタッフ契約",
            },
        ),
    ]
