# Generated by Django 5.2.7 on 2025-11-05 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_clientcontractprint_file_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractassignment',
            name='employment_conditions_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='就業条件明示書確認日時'),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='employment_conditions_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_employment_conditions', to=settings.AUTH_USER_MODEL, verbose_name='就業条件明示書確認者'),
        ),
    ]
