# Generated by Django 5.2.7 on 2025-11-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_contractassignment_employment_conditions_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractassignment',
            name='employment_conditions_confirmed_by',
        ),
    ]
