# Generated by Django 5.2.6 on 2025-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_clientcontract_approved_by_clientcontract_issued_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('1', '作成中'), ('5', '申請中'), ('10', '承認済'), ('20', '発行済'), ('30', '確認済')], default='1', max_length=2, null=True, verbose_name='契約状況'),
        ),
        migrations.AlterField(
            model_name='staffcontract',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('1', '作成中'), ('5', '申請中'), ('10', '承認済'), ('20', '発行済'), ('30', '確認済')], default='1', max_length=2, null=True, verbose_name='契約状況'),
        ),
    ]
