# Generated by Django 5.2.7 on 2025-11-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_remove_contractassignment_employment_conditions_confirmed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractassignment',
            name='employment_conditions_confirmed_at',
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認日時'),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='発行日時'),
        ),
    ]
