# Generated by Django 5.2.6 on 2025-09-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_clientcontract_contract_status_and_more'),
        ('master', '0025_alter_contractpattern_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='contract_pattern',
            field=models.ForeignKey(blank=True, limit_choices_to={'domain': '10'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.contractpattern', verbose_name='契約パターン'),
        ),
        migrations.AlterField(
            model_name='staffcontract',
            name='contract_pattern',
            field=models.ForeignKey(blank=True, limit_choices_to={'domain': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.contractpattern', verbose_name='契約パターン'),
        ),
    ]
