# Generated by Django 5.2.8 on 2025-11-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_add_issued_at_and_rename_confirmed_at'),
        ('master', '0022_employmenttype_worktime_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='worktime_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.worktimepattern', verbose_name='就業時間'),
        ),
    ]
