# Generated by Django 5.2.6 on 2025-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0017_alter_clientcontract_contract_pattern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="client_contract_type_code",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="契約種別"
            ),
        ),
    ]
