# Generated by Django 5.2.8 on 2025-11-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_staffcontract_worktime_pattern'),
        ('master', '0027_employmenttype_overtime_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontract',
            name='overtime_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.overtimepattern', verbose_name='時間外算出'),
        ),
    ]
