# Generated by Django 5.2.6 on 2025-09-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0018_clientcontract_client_contract_type_code"),
        ("master", "0026_contractpattern_contract_type_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontract",
            name="contract_pattern",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"domain": "10"},
                on_delete=django.db.models.deletion.PROTECT,
                to="master.contractpattern",
                verbose_name="契約パターン",
            ),
            preserve_default=False,
        ),
    ]
