# Generated by Django 5.2.6 on 2025-09-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0019_alter_clientcontract_contract_pattern"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientcontractprint",
            name="pdf_file_path",
        ),
        migrations.AddField(
            model_name="clientcontractprint",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="client_prints/",
                verbose_name="PDFファイル",
            ),
        ),
        migrations.AddField(
            model_name="clientcontractprint",
            name="print_type",
            field=models.CharField(
                choices=[("10", "契約書"), ("20", "見積書")],
                default="10",
                max_length=2,
                verbose_name="種別",
            ),
        ),
    ]
