# Generated by Django 5.2.6 on 2025-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0019_alter_clientcontract_contract_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontractprint",
            name="document_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="契約書タイトル"
            ),
        ),
        migrations.AddField(
            model_name="staffcontractprint",
            name="document_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="契約書タイトル"
            ),
        ),
    ]
