# Generated by Django 5.2.6 on 2025-09-16 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0019_alter_clientcontract_contract_pattern"),
        ("master", "0026_contractpattern_contract_type_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontract",
            name="contract_pattern",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"domain": "10"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="master.contractpattern",
                verbose_name="契約パターン",
            ),
        ),
    ]
