# Generated by Django 5.2.8 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_clientcontract_overtime_pattern'),
        ('master', '0034_timerounding'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='time_rounding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.timerounding', verbose_name='時間丸め'),
        ),
        migrations.AddField(
            model_name='staffcontract',
            name='time_rounding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.timerounding', verbose_name='時間丸め'),
        ),
    ]
