# Generated by Django 5.2.6 on 2025-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0020_remove_clientcontractprint_pdf_file_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffcontractprint",
            name="pdf_file_path",
        ),
        migrations.AddField(
            model_name="staffcontractprint",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="staff_prints/",
                verbose_name="PDFファイル",
            ),
        ),
    ]
