# Generated by Django 5.2.6 on 2025-09-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_clientcontractprint_document_title_and_more'),
        ('contract', '0021_remove_staffcontractprint_pdf_file_path_and_more'),
    ]

    operations = [
    ]
