# Generated by Django 5.2.6 on 2026-01-05 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_clientcontract_time_rounding_and_more'),
        ('master', '0037_alter_timepunch_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontract',
            name='time_rounding',
        ),
        migrations.RemoveField(
            model_name='staffcontract',
            name='time_rounding',
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='time_punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.timepunch', verbose_name='勤怠打刻'),
        ),
        migrations.AddField(
            model_name='staffcontract',
            name='time_punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.timepunch', verbose_name='勤怠打刻'),
        ),
    ]
