# Generated by Django 5.2.8 on 2026-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0022_remove_clientcontract_time_rounding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="clientcontracthaken",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="clientcontracthakenexempt",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="clientcontractnumber",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="clientcontractprint",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="clientcontractttp",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="contractassignment",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="contractassignmentconfirm",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="contractassignmenthaken",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="contractassignmenthakenprint",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontractnumber",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontractprint",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontractteishokubi",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffcontractteishokubidetail",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
    ]
