# Generated by Django 5.2.6 on 2025-09-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_merge_20250920_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontractprint',
            name='document_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='staffcontractprint',
            name='document_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='タイトル'),
        ),
    ]
