# Generated by Django 5.2.6 on 2025-09-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0023_alter_clientcontractprint_document_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContractNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(
                        db_index=True, max_length=8, verbose_name="クライアントコード"
                    ),
                ),
                (
                    "year_month",
                    models.CharField(db_index=True, max_length=6, verbose_name="年月"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="最終番号"),
                ),
            ],
            options={
                "verbose_name": "クライアント契約番号管理",
                "verbose_name_plural": "クライアント契約番号管理",
                "db_table": "apps_contract_client_number",
                "unique_together": {("client_code", "year_month")},
            },
        ),
    ]
