# Generated by Django 5.2.8 on 2026-01-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0025_contractstaffflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractclientflag",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="詳細"),
        ),
        migrations.AddField(
            model_name="contractstaffflag",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="詳細"),
        ),
    ]
