# Generated by Django 5.2.6 on 2025-09-22 16:50

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0021_alter_client_basic_contract_date"),
        ("company", "0012_company_haken_permit_number_and_more"),
        ("contract", "0025_clientcontractnumber_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContractHaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "limit_by_agreement",
                    models.CharField(
                        blank=True,
                        choices=[("0", "限定しない"), ("1", "限定する")],
                        max_length=1,
                        null=True,
                        verbose_name="協定対象派遣労働者に限定するか否かの別",
                    ),
                ),
                (
                    "limit_indefinite_or_senior",
                    models.CharField(
                        blank=True,
                        choices=[("0", "限定しない"), ("1", "限定する")],
                        max_length=1,
                        null=True,
                        verbose_name="無期雇用派遣労働者又は60歳以上の者に限定するか否かの別",
                    ),
                ),
                (
                    "client_contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haken_info",
                        to="contract.clientcontract",
                        verbose_name="クライアント契約",
                    ),
                ),
                (
                    "commander",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_commanders",
                        to="client.clientuser",
                        verbose_name="派遣先指揮命令者",
                    ),
                ),
                (
                    "complaint_officer_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_complaint_officers_client",
                        to="client.clientuser",
                        verbose_name="派遣先苦情申出先",
                    ),
                ),
                (
                    "complaint_officer_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_complaint_officers_company",
                        to="company.companyuser",
                        verbose_name="派遣元苦情申出先",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "responsible_person_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_responsible_persons_client",
                        to="client.clientuser",
                        verbose_name="派遣先責任者",
                    ),
                ),
                (
                    "responsible_person_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haken_responsible_persons_company",
                        to="company.companyuser",
                        verbose_name="派遣元責任者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約派遣情報",
                "verbose_name_plural": "クライアント契約派遣情報",
                "db_table": "apps_contract_client_haken",
            },
        ),
    ]
