# Generated by Django 5.2.6 on 2025-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0025_clientcontractnumber_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontractnumber",
            name="corporate_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="法人番号"
            ),
        ),
    ]
