# Generated by Django 5.2.6 on 2025-09-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_clientcontracthaken'),
        ('contract', '0026_clientcontractnumber_corporate_number'),
    ]

    operations = [
    ]
