# Generated by Django 5.2.6 on 2025-09-23 16:23

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0027_merge_20250923_0201"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffContractNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "employee_no",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="社員番号"
                    ),
                ),
                (
                    "year_month",
                    models.CharField(db_index=True, max_length=6, verbose_name="年月"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="最終番号"),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="法人番号"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ契約番号管理",
                "verbose_name_plural": "スタッフ契約番号管理",
                "db_table": "apps_contract_staff_number",
                "unique_together": {("employee_no", "year_month")},
            },
        ),
    ]
