# Generated by Django 5.2.6 on 2025-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0028_staffcontractnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontracthaken",
            name="business_content",
            field=models.TextField(blank=True, null=True, verbose_name="業務内容"),
        ),
        migrations.AddField(
            model_name="clientcontracthaken",
            name="responsibility_degree",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="責任の程度"
            ),
        ),
    ]
