# Generated by Django 5.2.6 on 2025-10-01 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0023_clientdepartment_haken_jigyosho_teishokubi"),
        ("contract", "0029_clientcontractbusiness_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontracthaken",
            name="haken_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="haken_offices",
                to="client.clientdepartment",
                verbose_name="派遣先事業所",
            ),
        ),
        migrations.AddField(
            model_name="clientcontracthaken",
            name="haken_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="haken_units",
                to="client.clientdepartment",
                verbose_name="組織単位",
            ),
        ),
    ]
