# Generated by Django 5.2.6 on 2025-10-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0030_clientcontracthaken_haken_office_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontracthaken",
            name="work_location",
            field=models.TextField(blank=True, null=True, verbose_name="就業場所"),
        ),
    ]
