# Generated by Django 5.2.6 on 2025-10-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0031_clientcontracthaken_work_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontractprint",
            name="print_type",
            field=models.CharField(
                choices=[("10", "契約書"), ("20", "見積書"), ("30", "抵触日通知書")],
                default="10",
                max_length=2,
                verbose_name="種別",
            ),
        ),
    ]
