# Generated by Django 5.2.6 on 2025-10-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0023_clientdepartment_haken_jigyosho_teishokubi"),
        ("contract", "0032_alter_clientcontractprint_print_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_client_contracts",
                to="client.clientuser",
                verbose_name="確認者",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontractprint",
            name="print_type",
            field=models.CharField(
                choices=[
                    ("10", "契約書"),
                    ("20", "見積書"),
                    ("30", "抵触日通知書"),
                    ("40", "派遣通知書"),
                ],
                default="10",
                max_length=2,
                verbose_name="種別",
            ),
        ),
    ]
