# Generated by Django 5.2.6 on 2025-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0033_clientcontract_confirmed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="bill_unit",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="請求単位"
            ),
        ),
    ]
