# Generated by Django 5.2.6 on 2025-10-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0034_clientcontract_bill_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcontract",
            name="pay_unit",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="支払単位"
            ),
        ),
    ]
