# Generated by Django 5.2.6 on 2025-10-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0035_staffcontract_pay_unit'),
        ('master', '0030_alter_contractpattern_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='contract_pattern',
            field=models.ForeignKey(limit_choices_to={'domain': '10'}, on_delete=django.db.models.deletion.PROTECT, to='master.contractpattern', verbose_name='契約書パターン'),
        ),
        migrations.AlterField(
            model_name='staffcontract',
            name='contract_pattern',
            field=models.ForeignKey(blank=True, limit_choices_to={'domain': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.contractpattern', verbose_name='契約書パターン'),
        ),
    ]
