# Generated by Django 5.2.6 on 2025-10-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0035_staffcontract_pay_unit"),
        ("master", "0029_jobcategory_is_manufacturing_dispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="memo",
            field=models.TextField(blank=True, null=True, verbose_name="メモ"),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="memo",
            field=models.TextField(blank=True, null=True, verbose_name="メモ"),
        ),
    ]