# Generated by Django 5.2.6 on 2025-10-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0036_alter_clientcontract_contract_pattern_and_more'),
        ('contract', '0037_clientcontract_memo_staffcontract_memo_and_more'),
    ]

    operations = [
    ]
