# Generated by Django 5.2.6 on 2025-10-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0038_merge_20251007_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontractprint',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='契約番号'),
        ),
        migrations.AddField(
            model_name='staffcontractprint',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='契約番号'),
        ),
    ]
