# Generated by Django 5.2.6 on 2025-10-06 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0039_clientcontractprint_contract_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='quotation_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='見積発行日時'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='quotation_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_client_quotations', to=settings.AUTH_USER_MODEL, verbose_name='見積発行者'),
        ),
    ]
