# Generated by Django 5.2.6 on 2025-10-07 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0040_clientcontract_quotation_issued_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="teishokubi_notification_issued_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="抵触日通知書共有日時"
            ),
        ),
        migrations.AddField(
            model_name="clientcontract",
            name="teishokubi_notification_issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_teishokubi_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="抵触日通知書共有者",
            ),
        ),
    ]
