# Generated by Django 5.2.6 on 2025-10-07 16:53

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0040_clientcontract_quotation_issued_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContractTtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "contract_period",
                    models.TextField(blank=True, null=True, verbose_name="契約期間"),
                ),
                (
                    "probation_period",
                    models.TextField(
                        blank=True, null=True, verbose_name="試用期間に関する事項"
                    ),
                ),
                (
                    "business_content",
                    models.TextField(blank=True, null=True, verbose_name="業務内容"),
                ),
                (
                    "work_location",
                    models.TextField(blank=True, null=True, verbose_name="就業場所"),
                ),
                (
                    "working_hours",
                    models.TextField(blank=True, null=True, verbose_name="始業・終業"),
                ),
                (
                    "break_time",
                    models.TextField(blank=True, null=True, verbose_name="休憩時間"),
                ),
                (
                    "overtime",
                    models.TextField(
                        blank=True, null=True, verbose_name="所定時間外労働"
                    ),
                ),
                (
                    "holidays",
                    models.TextField(blank=True, null=True, verbose_name="休日"),
                ),
                (
                    "vacations",
                    models.TextField(blank=True, null=True, verbose_name="休暇"),
                ),
                ("wages", models.TextField(blank=True, null=True, verbose_name="賃金")),
                (
                    "insurances",
                    models.TextField(
                        blank=True, null=True, verbose_name="各種保険の加入"
                    ),
                ),
                (
                    "employer_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="雇用しようとする者の名称"
                    ),
                ),
                (
                    "other",
                    models.TextField(blank=True, null=True, verbose_name="その他"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "haken",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ttp_info",
                        to="contract.clientcontracthaken",
                        verbose_name="クライアント契約派遣情報",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント契約紹介予定派遣情報",
                "verbose_name_plural": "クライアント契約紹介予定派遣情報",
                "db_table": "apps_contract_client_ttp",
            },
        ),
    ]
