# Generated by Django 5.2.6 on 2025-10-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0041_clientcontract_clash_day_notification_issued_at_and_more'),
        ('contract', '0041_clientcontractttp'),
    ]

    operations = [
    ]
