# Generated by Django 5.2.6 on 2025-10-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0042_merge_20251008_0227"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcontract",
            name="business_content",
            field=models.TextField(blank=True, null=True, verbose_name="業務内容"),
        ),
        migrations.AddField(
            model_name="staffcontract",
            name="work_location",
            field=models.TextField(blank=True, null=True, verbose_name="就業場所"),
        ),
    ]
