# Generated by Django 5.2.6 on 2025-10-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0043_staffcontract_business_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffcontract",
            name="description",
        ),
    ]
