# Generated by Django 5.2.6 on 2025-10-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0044_remove_clientcontract_description"),
        ("contract", "0044_remove_staffcontract_description"),
    ]

    operations = []
