# Generated by Django 5.2.6 on 2025-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0045_merge_20251011_0026"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientcontracthaken",
            name="business_content",
        ),
        migrations.AddField(
            model_name="clientcontract",
            name="business_content",
            field=models.TextField(blank=True, null=True, verbose_name="業務内容"),
        ),
    ]
