# Generated by Django 5.2.6 on 2025-10-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0046_contractassignment_clientcontract_staff_contracts'),
        ('contract', '0046_remove_clientcontracthaken_business_content_and_more'),
    ]

    operations = [
    ]
