# Generated by Django 5.2.6 on 2025-10-12 14:44

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0047_merge_20251011_0105"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffContractTeishokubi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "staff_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="スタッフメールアドレス",
                    ),
                ),
                (
                    "client_corporate_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        verbose_name="クライアント法人番号",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(max_length=255, verbose_name="組織名"),
                ),
                ("dispatch_start_date", models.DateField(verbose_name="派遣開始日")),
                ("conflict_date", models.DateField(verbose_name="抵触日")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "個人抵触日",
                "verbose_name_plural": "個人抵触日",
                "db_table": "apps_contract_staff_teishokubi",
                "ordering": ["-dispatch_start_date", "staff_email"],
            },
        ),
    ]
