# Generated by Django 5.2.7 on 2025-10-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0048_staffcontractteishokubi'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontract',
            name='employment_type',
            field=models.CharField(blank=True, help_text='契約作成時点のスタッフの雇用形態を保存', max_length=10, null=True, verbose_name='雇用形態'),
        ),
    ]
