# Generated by Django 5.2.7 on 2025-10-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0049_staffcontract_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='contract_status',
            field=models.CharField(blank=True, default='1', max_length=2, null=True, verbose_name='契約状況'),
        ),
        migrations.AlterField(
            model_name='staffcontract',
            name='contract_status',
            field=models.CharField(blank=True, default='1', max_length=2, null=True, verbose_name='契約状況'),
        ),
    ]
