# Generated by Django 5.2.7 on 2025-10-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0050_alter_clientcontract_contract_status_and_more'),
        ('contract', '0050_alter_staffcontract_employment_type'),
    ]

    operations = [
    ]
