# Generated by Django 5.2.7 on 2025-10-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0052_staffcontractteishokubidetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontractteishokubidetail',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='手動作成'),
        ),
    ]
