# Generated by Django 5.2.7 on 2025-10-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_staffcontractteishokubidetail_is_manual'),
        ('master', '0036_clientregiststatus_staffregiststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcontract',
            name='contract_pattern',
            field=models.ForeignKey(limit_choices_to={'domain': '1'}, on_delete=django.db.models.deletion.PROTECT, to='master.contractpattern', verbose_name='契約書パターン'),
        ),
    ]
