# Generated by Django 5.1.2 on 2024-11-07 04:59

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.CharField(default='', max_length=50, verbose_name='分類')),
                ('key', models.CharField(max_length=100, verbose_name='キー')),
                ('value', models.CharField(max_length=100, verbose_name='設定値')),
                ('default_value', models.CharField(max_length=100, verbose_name='初期値')),
                ('note', models.CharField(max_length=100, verbose_name='備考')),
                ('disp_seq', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'パラメータ',
                'verbose_name_plural': 'パラメータ',
                'db_table': 'apps_system_parameter',
                'ordering': ['category', 'disp_seq'],
            },
        ),
    ]
