# Generated by Django 5.2.8 on 2026-02-01 21:55

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048, verbose_name="URL")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="タイムスタンプ"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "アクセスログ",
                "verbose_name_plural": "アクセスログ",
                "db_table": "apps_system_access_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="apps_system_timesta_d51ab9_idx"
                    ),
                    models.Index(
                        fields=["user"], name="apps_system_user_id_9f8782_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "作成"),
                            ("update", "編集"),
                            ("delete", "削除"),
                            ("login", "ログイン"),
                            ("login_failed", "ログイン失敗"),
                            ("logout", "ログアウト"),
                            ("view", "閲覧"),
                            ("print", "印刷"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="モデル名"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="オブジェクトID"),
                ),
                ("object_repr", models.TextField(verbose_name="オブジェクト表現")),
                (
                    "version",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="バージョン"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="タイムスタンプ"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_app_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "アプリケーション操作ログ",
                "verbose_name_plural": "アプリケーション操作ログ",
                "db_table": "apps_system_app_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="apps_system_user_id_7766de_idx"
                    ),
                    models.Index(
                        fields=["action"], name="apps_system_action_a6aea6_idx"
                    ),
                    models.Index(
                        fields=["model_name"], name="apps_system_model_n_6247b1_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="apps_system_timesta_20787b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "from_email",
                    models.EmailField(
                        max_length=255, verbose_name="送信者メールアドレス"
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        max_length=255, verbose_name="受信者メールアドレス"
                    ),
                ),
                (
                    "mail_type",
                    models.CharField(
                        choices=[
                            ("signup", "サインアップ確認"),
                            ("password_reset", "パスワードリセット"),
                            ("password_change", "パスワード変更通知"),
                            ("general", "一般"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="メール種別",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="件名")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "送信成功"),
                            ("failed", "送信失敗"),
                            ("pending", "送信待ち"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="送信状況",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送信日時"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="エラーメッセージ"
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="メールバックエンド",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="メッセージID",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="ユーザーが特定できる場合のみ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受信者ユーザー",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "メール送信ログ",
                "verbose_name_plural": "メール送信ログ",
                "db_table": "apps_system_mail_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_email"], name="apps_system_to_emai_3dcb3e_idx"
                    ),
                    models.Index(
                        fields=["mail_type"], name="apps_system_mail_ty_12bfe4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="apps_system_status_f1514c_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="apps_system_sent_at_83f3cb_idx"
                    ),
                ],
            },
        ),
    ]
