# Generated by Django 5.2.1 on 2025-08-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '作成'), ('update', '編集'), ('delete', '削除'), ('login', 'ログイン'), ('logout', 'ログアウト'), ('view', '閲覧')], max_length=10, verbose_name='操作')),
                ('model_name', models.CharField(max_length=100, verbose_name='モデル名')),
                ('object_id', models.CharField(max_length=100, verbose_name='オブジェクトID')),
                ('object_repr', models.TextField(verbose_name='オブジェクト表現')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='バージョン')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='タイムスタンプ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_app_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アプリケーション操作ログ',
                'verbose_name_plural': 'アプリケーション操作ログ',
                'db_table': 'apps_system_app_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='apps_system_user_id_7766de_idx'), models.Index(fields=['action'], name='apps_system_action_a6aea6_idx'), models.Index(fields=['model_name'], name='apps_system_model_n_6247b1_idx'), models.Index(fields=['timestamp'], name='apps_system_timesta_20787b_idx')],
            },
        ),
    ]
