# Generated by Django 5.2.1 on 2025-08-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_applog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メッセージID'),
        ),
    ]
