# Generated by Django 5.2.4 on 2025-08-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_maillog_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='backend',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メールバックエンド'),
        ),
    ]
