# Generated by Django 5.2.5 on 2025-09-03 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_alter_applog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048, verbose_name="URL")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="タイムスタンプ"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "アクセスログ",
                "verbose_name_plural": "アクセスログ",
                "db_table": "apps_system_access_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="apps_system_timesta_d51ab9_idx"
                    ),
                    models.Index(
                        fields=["user"], name="apps_system_user_id_9f8782_idx"
                    ),
                ],
            },
        ),
    ]
