# Generated by Django 5.0.4 on 2025-09-03 14:12

from django.db import migrations

def add_view_accesslog_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Get the permission
    try:
        permission = Permission.objects.get(codename='view_accesslog')

        # Add permission to admin group
        admin_group, created = Group.objects.get_or_create(name='admin')
        admin_group.permissions.add(permission)
    except Permission.DoesNotExist:
        # Permission might not exist in some testing scenarios
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_accesslog'),
    ]

    operations = [
        migrations.RunPython(add_view_accesslog_permission),
    ]
