# Generated by Django 5.2.5 on 2025-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20250903_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applog',
            name='action',
            field=models.CharField(choices=[('create', '作成'), ('update', '編集'), ('delete', '削除'), ('login', 'ログイン'), ('login_failed', 'ログイン失敗'), ('logout', 'ログアウト'), ('view', '閲覧'), ('print', '印刷')], max_length=20, verbose_name='操作'),
        ),
    ]
