# Generated by Django 5.2.4 on 2025-08-06 11:59

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='資格名')),
                ('category', models.CharField(choices=[('national', '国家資格'), ('public', '公的資格'), ('private', '民間資格'), ('internal', '社内資格'), ('other', 'その他')], default='private', max_length=20, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('issuing_organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='発行機関')),
                ('validity_period', models.IntegerField(blank=True, help_text='無期限の場合は空欄', null=True, verbose_name='有効期間（年）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '資格',
                'verbose_name_plural': '資格',
                'db_table': 'apps_master_qualification',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['category'], name='apps_master_categor_550b56_idx'), models.Index(fields=['is_active'], name='apps_master_is_acti_fdbdb2_idx'), models.Index(fields=['display_order'], name='apps_master_display_e172db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='技能名')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('required_level', models.CharField(choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '上級'), ('expert', 'エキスパート')], default='beginner', help_text='この技能に求められる最低レベル', max_length=20, verbose_name='必要レベル')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'db_table': 'apps_master_skill',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['category'], name='apps_master_categor_33383a_idx'), models.Index(fields=['is_active'], name='apps_master_is_acti_dee479_idx'), models.Index(fields=['display_order'], name='apps_master_display_f7a2a4_idx')],
            },
        ),
    ]
