# Generated by Django 5.2.4 on 2025-08-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='issuing_organization',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='validity_period',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='required_level',
        ),
    ]
