# Generated by Django 5.2.7 on 2025-10-20 13:19

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HakenTeishokubiExempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('content', models.TextField(help_text='派遣抵触日制限外の詳細内容', verbose_name='内容')),
                ('display_order', models.IntegerField(default=0, help_text='表示順序（昇順）', verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, help_text='有効な場合はチェック', verbose_name='有効/無効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '派遣抵触日制限外',
                'verbose_name_plural': '派遣抵触日制限外',
                'db_table': 'apps_master_haken_teishokubi_exempt',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
