# Generated by Django 5.2.8 on 2026-02-06 08:05

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="コード")),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("10", "時給"), ("20", "日給"), ("30", "月給")],
                        max_length=10,
                        verbose_name="給与種別",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="金額")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="有効期間開始日"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="有効期間終了日"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ等級",
                "verbose_name_plural": "スタッフ等級",
                "db_table": "apps_master_grade",
                "ordering": ["display_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="apps_master_is_acti_98aa7a_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="apps_master_display_22c87e_idx"
                    ),
                ],
            },
        ),
    ]
