# Generated by Django 5.2.8 on 2026-02-04 06:32

from django.db import migrations

def add_header_text_color(apps, schema_editor):
    UserParameter = apps.get_model('master', 'UserParameter')

    UserParameter.objects.get_or_create(
        key='MAIN_HEADER_TEXT_COLOR',
        defaults={
            'target_item': 'メイン画面＞ヘッダー文字色',
            'format': 'color',
            'value': '#000000',
            'display_order': 22,
            'tenant_id': 1,
        }
    )

def remove_header_text_color(apps, schema_editor):
    UserParameter = apps.get_model('master', 'UserParameter')
    UserParameter.objects.filter(key='MAIN_HEADER_TEXT_COLOR').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_header_text_color, remove_header_text_color),
    ]
