# Generated by Django 5.2.7 on 2025-10-24 15:51

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_hakenteishokubiexempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.CharField(choices=[('health_insurance_non_enrollment', '健保非加入理由'), ('pension_insurance_non_enrollment', '厚年非加入理由'), ('employment_insurance_non_enrollment', '雇保非加入理由')], help_text='文言の分類を選択してください', max_length=50, verbose_name='分類')),
                ('content', models.TextField(help_text='文言の内容を入力してください', verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, help_text='有効な文言かどうかを設定してください', verbose_name='状態')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='表示順序を設定してください（小さい数字が先に表示されます）', verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '汎用文言テンプレート',
                'verbose_name_plural': '汎用文言テンプレート',
                'db_table': 'apps_master_phrase_template',
                'ordering': ['category', 'display_order', 'id'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='apps_master_categor_db29ab_idx'), models.Index(fields=['display_order'], name='apps_master_display_42f72b_idx')],
            },
        ),
    ]
