# Generated by Django 5.2.8 on 2026-02-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_grade"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="grade",
            new_name="apps_master_is_acti_be8d5c_idx",
            old_name="apps_master_is_acti_98aa7a_idx",
        ),
        migrations.RenameIndex(
            model_name="grade",
            new_name="apps_master_display_199f67_idx",
            old_name="apps_master_display_22c87e_idx",
        ),
    ]
