# Generated by Django 5.2.4 on 2025-08-07 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_qualification_issuing_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['level', 'display_order', 'name'], 'verbose_name': '技能', 'verbose_name_plural': '技能'},
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='apps_master_categor_33383a_idx',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(1, 'カテゴリ'), (2, '技能')], default=2, verbose_name='階層レベル'),
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.skill', verbose_name='親カテゴリ'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['level'], name='apps_master_level_66e2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['parent'], name='apps_master_parent__344918_idx'),
        ),
    ]
