# Generated by Django 5.2.7 on 2025-10-24 23:21

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_phrasetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseTemplateTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(help_text='文言タイトルの名称を入力してください', max_length=100, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, help_text='有効な文言タイトルかどうかを設定してください', verbose_name='状態')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='表示順序を設定してください（小さい数字が先に表示されます）', verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '汎用文言タイトル',
                'verbose_name_plural': '汎用文言タイトル',
                'db_table': 'apps_master_phrase_template_title',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='apps_master_is_acti_d60aeb_idx'), models.Index(fields=['display_order'], name='apps_master_display_a8ba3b_idx')],
            },
        ),
    ]
