# Generated by Django 5.2.4 on 2025-08-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_skill_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['level', 'display_order', 'name'], 'verbose_name': '資格', 'verbose_name_plural': '資格'},
        ),
        migrations.RemoveIndex(
            model_name='qualification',
            name='apps_master_categor_550b56_idx',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='category',
        ),
        migrations.AddField(
            model_name='qualification',
            name='level',
            field=models.IntegerField(choices=[(1, 'カテゴリ'), (2, '資格')], default=2, verbose_name='階層レベル'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.qualification', verbose_name='親カテゴリ'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['level'], name='apps_master_level_1b856e_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['parent'], name='apps_master_parent__35a637_idx'),
        ),
    ]
