# Generated by Django 5.2.7 on 2025-10-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_phrasetemplatetitle'),
    ]

    operations = [
    ]
