# Generated by Django 5.2.5 on 2025-08-11 07:14

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_qualification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='銀行名')),
                ('bank_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='銀行コード')),
                ('branch_name', models.CharField(max_length=100, verbose_name='支店名')),
                ('branch_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='支店コード')),
                ('account_type', models.CharField(choices=[('ordinary', '普通'), ('current', '当座'), ('savings', '貯蓄')], default='ordinary', max_length=10, verbose_name='口座種別')),
                ('account_number', models.CharField(max_length=8, verbose_name='口座番号')),
                ('account_holder', models.CharField(max_length=100, verbose_name='口座名義')),
                ('account_holder_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='口座名義（カナ）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '振込先銀行',
                'verbose_name_plural': '振込先銀行',
                'db_table': 'apps_master_bill_bank',
                'ordering': ['display_order', 'name', 'branch_name'],
                'indexes': [models.Index(fields=['is_active'], name='apps_master_is_acti_2bf485_idx'), models.Index(fields=['display_order'], name='apps_master_display_2990d3_idx'), models.Index(fields=['bank_code'], name='apps_master_bank_co_a28752_idx'), models.Index(fields=['branch_code'], name='apps_master_branch__01d505_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='支払いサイト名')),
                ('closing_day', models.IntegerField(help_text='月末締めの場合は31を入力', verbose_name='締め日')),
                ('invoice_months_after', models.IntegerField(default=0, help_text='締め日から何か月後', verbose_name='請求書提出月数')),
                ('invoice_day', models.IntegerField(help_text='請求書が必着する日', verbose_name='請求書必着日')),
                ('payment_months_after', models.IntegerField(default=1, help_text='締め日から何か月後', verbose_name='支払い月数')),
                ('payment_day', models.IntegerField(help_text='支払いが行われる日', verbose_name='支払い日')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '支払いサイト',
                'verbose_name_plural': '支払いサイト',
                'db_table': 'apps_master_bill_payment',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='apps_master_is_acti_d8286a_idx'), models.Index(fields=['display_order'], name='apps_master_display_79f66c_idx')],
            },
        ),
    ]
