# Generated by Django 5.2.7 on 2025-10-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20251025_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasetemplatetitle',
            name='format_type',
            field=models.CharField(choices=[('text', 'テキスト'), ('textarea', 'テキストエリア')], default='text', help_text='入力フィールドの書式を選択してください', max_length=10, verbose_name='書式'),
        ),
    ]
