# Generated by Django 5.2.5 on 2025-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_billbank_billpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billbank',
            name='description',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='description',
        ),
        migrations.AlterField(
            model_name='billbank',
            name='account_type',
            field=models.CharField(choices=[('ordinary', '普通'), ('current', '当座')], default='ordinary', max_length=10, verbose_name='口座種別'),
        ),
    ]
