# Generated by Django 5.2.5 on 2025-08-14 16:49

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_billbank_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billpayment',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '支払条件', 'verbose_name_plural': '支払条件'},
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='支払条件名'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='銀行名')),
                ('bank_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='銀行コード')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '銀行',
                'verbose_name_plural': '銀行',
                'db_table': 'apps_master_bank',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='apps_master_is_acti_bfb757_idx'), models.Index(fields=['display_order'], name='apps_master_display_26b320_idx'), models.Index(fields=['bank_code'], name='apps_master_bank_co_87c63f_idx')],
            },
        ),
    ]
