# Generated by Django 5.2.7 on 2025-10-25 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_phrasetemplatetitle_format_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrasetemplate',
            options={'ordering': ['title__display_order', 'display_order', 'id'], 'verbose_name': '汎用文言テンプレート', 'verbose_name_plural': '汎用文言テンプレート'},
        ),
        migrations.RemoveIndex(
            model_name='phrasetemplate',
            name='apps_master_categor_db29ab_idx',
        ),
        migrations.RemoveField(
            model_name='phrasetemplate',
            name='category',
        ),
        migrations.AddField(
            model_name='phrasetemplate',
            name='title',
            field=models.ForeignKey(default=1, help_text='文言のタイトルを選択してください', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='master.phrasetemplatetitle', verbose_name='文言タイトル'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='phrasetemplate',
            index=models.Index(fields=['title', 'is_active'], name='apps_master_title_i_ee8f11_idx'),
        ),
    ]
