# Generated by Django 5.2.5 on 2025-08-14 17:04

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_billpayment_options_alter_billpayment_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='支店名')),
                ('branch_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='支店コード')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='master.bank', verbose_name='銀行')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '銀行支店',
                'verbose_name_plural': '銀行支店',
                'db_table': 'apps_master_bank_branch',
                'ordering': ['bank__display_order', 'bank__name', 'display_order', 'name'],
                'indexes': [models.Index(fields=['bank'], name='apps_master_bank_id_378583_idx'), models.Index(fields=['is_active'], name='apps_master_is_acti_ce1d64_idx'), models.Index(fields=['display_order'], name='apps_master_display_955f67_idx'), models.Index(fields=['branch_code'], name='apps_master_branch__8672d6_idx')],
                'unique_together': {('bank', 'branch_code')},
            },
        ),
    ]
