# Generated by Django 5.2.7 on 2025-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_phrasetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasetemplatetitle',
            name='key',
            field=models.CharField(default=1, help_text='プログラムから参照するためのキーを入力してください（英数字とアンダースコアのみ）', max_length=50, unique=True, verbose_name='参照キー'),
            preserve_default=False,
        ),
    ]
