# Generated by Django 5.2.5 on 2025-08-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_bankbranch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': '銀行', 'verbose_name_plural': '銀行'},
        ),
        migrations.AlterModelOptions(
            name='bankbranch',
            options={'ordering': ['bank__name', 'name'], 'verbose_name': '銀行支店', 'verbose_name_plural': '銀行支店'},
        ),
        migrations.RemoveIndex(
            model_name='bank',
            name='apps_master_display_26b320_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankbranch',
            name='apps_master_display_955f67_idx',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='phone',
        ),
    ]
