# Generated by Django 5.2.7 on 2025-10-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_phrasetemplatetitle_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasetemplatetitle',
            name='description',
            field=models.TextField(blank=True, help_text='文言タイトルの補足説明を入力してください（任意）', null=True, verbose_name='補足'),
        ),
    ]
