# Generated by Django 5.2.7 on 2025-10-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_add_description_to_phrase_template_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HakenResponsibilityDegree',
        ),
    ]
