# Generated by Django 5.2.5 on 2025-08-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_bank_options_alter_bankbranch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(help_text='4桁の数字で入力', max_length=4, unique=True, verbose_name='銀行コード'),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='branch_code',
            field=models.CharField(help_text='3桁の数字で入力', max_length=3, verbose_name='支店コード'),
        ),
        migrations.AlterField(
            model_name='billbank',
            name='bank_code',
            field=models.CharField(help_text='4桁の数字で入力', max_length=4, verbose_name='銀行コード'),
        ),
        migrations.AlterField(
            model_name='billbank',
            name='branch_code',
            field=models.CharField(help_text='3桁の数字で入力', max_length=3, verbose_name='支店コード'),
        ),
    ]
