# Generated by Django 5.2.7 on 2025-10-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_delete_haken_responsibility_degree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HakenTeishokubiExempt',
        ),
    ]
