# Generated by Django 5.2.5 on 2025-08-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0010_make_bill_bank_codes_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billbank",
            options={
                "ordering": ["display_order", "name", "branch_name"],
                "verbose_name": "会社銀行",
                "verbose_name_plural": "会社銀行",
            },
        ),
    ]
