# Generated by Django 5.2.5 on 2025-08-25 15:04

from django.db import migrations

def add_international_profile_menu_item(apps, schema_editor):
    """
    「スタッフ外国籍プロフィール」をメニューに追加します。
    """
    SiteTree = apps.get_model('sitetree', 'Tree')
    SiteTreeItem = apps.get_model('sitetree', 'TreeItem')

    # 'main' というエイリアスのツリーが存在することを前提とします。
    # ツリーが存在しない、または複数存在する場合は、適宜修正が必要です。
    try:
        main_tree = SiteTree.objects.get(alias='main')
    except SiteTree.DoesNotExist:
        # mainツリーがない場合は何もしない
        return

    # 「プロフィール」メニュー項目を探します。
    # 見つからない場合は、トップレベルに追加します。
    try:
        profile_menu = SiteTreeItem.objects.get(tree=main_tree, title='プロフィール')
    except SiteTreeItem.DoesNotExist:
        profile_menu = None

    # 新しいメニュー項目を作成
    SiteTreeItem.objects.create(
        tree=main_tree,
        parent=profile_menu,
        title='スタッフ外国籍プロフィール',
        url='/admin/profile/staffprofileinternational/',
        hidden=False,
        sort_order=10 # 必要に応じて調整
    )

def remove_international_profile_menu_item(apps, schema_editor):
    """
    「スタッフ外国籍プロフィール」をメニューから削除します。
    """
    SiteTreeItem = apps.get_model('sitetree', 'TreeItem')
    SiteTreeItem.objects.filter(url='/admin/profile/staffprofileinternational/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0011_alter_billbank_options"),
        ('sitetree', '__first__'),
    ]

    operations = [
        migrations.RunPython(add_international_profile_menu_item, remove_international_profile_menu_item),
    ]
