# Generated by Django 5.2.5 on 2025-08-31 14:30

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0011_alter_billbank_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("company", "会社"),
                            ("staff", "スタッフ"),
                            ("client", "クライアント"),
                        ],
                        default="company",
                        max_length=10,
                        verbose_name="対象",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="件名")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "corporation_number",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="法人番号"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "お知らせ",
                "verbose_name_plural": "お知らせ",
                "db_table": "apps_master_information",
                "ordering": ["-start_date"],
            },
        ),
    ]
