# Generated by Django 5.2.5 on 2025-08-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0011_alter_billbank_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billbank",
            options={
                "ordering": ["display_order", "bank_code", "branch_code"],
                "verbose_name": "会社銀行",
                "verbose_name_plural": "会社銀行",
            },
        ),
        migrations.RemoveField(
            model_name="billbank",
            name="branch_name",
        ),
        migrations.RemoveField(
            model_name="billbank",
            name="name",
        ),
    ]
