# Generated by Django 5.2.7 on 2025-10-25 15:44

from django.db import migrations


def migrate_business_content_to_phrase_template(apps, schema_editor):
    """BusinessContentのデータを汎用文言マスタに移行"""
    BusinessContent = apps.get_model('master', 'BusinessContent')
    PhraseTemplate = apps.get_model('master', 'PhraseTemplate')
    PhraseTemplateTitle = apps.get_model('master', 'PhraseTemplateTitle')
    
    # 業務内容タイトルを取得
    try:
        title = PhraseTemplateTitle.objects.get(key='CONTRACT_BUSINESS_CONTENT')
    except PhraseTemplateTitle.DoesNotExist:
        # タイトルが存在しない場合は作成
        title = PhraseTemplateTitle.objects.create(
            key='CONTRACT_BUSINESS_CONTENT',
            name='業務内容',
            description='クライアント契約、スタッフ契約に利用',
            format_type='textarea',
            is_active=True,
            display_order=202
        )
    
    # BusinessContentのデータを汎用文言マスタに移行
    for business_content in BusinessContent.objects.all():
        PhraseTemplate.objects.create(
            title=title,
            content=business_content.content,
            is_active=business_content.is_active,
            display_order=business_content.display_order,
            created_at=business_content.created_at,
            created_by=business_content.created_by,
            updated_at=business_content.updated_at,
            updated_by=business_content.updated_by,
        )


def reverse_migrate_business_content(apps, schema_editor):
    """逆マイグレーション（汎用文言マスタから業務内容を削除）"""
    PhraseTemplate = apps.get_model('master', 'PhraseTemplate')
    PhraseTemplateTitle = apps.get_model('master', 'PhraseTemplateTitle')
    
    try:
        title = PhraseTemplateTitle.objects.get(key='CONTRACT_BUSINESS_CONTENT')
        PhraseTemplate.objects.filter(title=title).delete()
    except PhraseTemplateTitle.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_delete_hakenteishokubiexempt'),
    ]

    operations = [
        migrations.RunPython(
            migrate_business_content_to_phrase_template,
            reverse_migrate_business_content
        ),
        migrations.DeleteModel(
            name='BusinessContent',
        ),
    ]
