# Generated by Django 5.2.7 on 2025-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_remove_business_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultvalue',
            name='format',
            field=models.CharField(choices=[('text', 'テキスト'), ('textarea', 'テキストエリア'), ('boolean', '真偽値'), ('number', '数値')], default='text', max_length=10, verbose_name='形式'),
        ),
    ]
