# Generated by Django 5.2.8 on 2025-11-07 18:11

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_defaultvalue_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '就業時間パターン',
                'verbose_name_plural': '就業時間パターン',
                'db_table': 'apps_master_worktime_pattern',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimePatternWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('time_name', models.CharField(blank=True, help_text='例：日勤、準夜勤、夜勤', max_length=100, null=True, verbose_name='時間名称')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='メモ')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('worktime_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='master.worktimepattern', verbose_name='就業時間パターン')),
            ],
            options={
                'verbose_name': '就業時間パターン勤務時間',
                'verbose_name_plural': '就業時間パターン勤務時間',
                'db_table': 'apps_master_worktime_pattern_work',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimePatternBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('time_name', models.CharField(blank=True, help_text='例：休憩１、休憩２', max_length=100, null=True, verbose_name='時間名称')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='メモ')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('work_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to='master.worktimepatternwork', verbose_name='勤務時間')),
            ],
            options={
                'verbose_name': '就業時間パターン休憩時間',
                'verbose_name_plural': '就業時間パターン休憩時間',
                'db_table': 'apps_master_worktime_pattern_break',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='worktimepattern',
            index=models.Index(fields=['is_active'], name='apps_master_is_acti_5d687d_idx'),
        ),
        migrations.AddIndex(
            model_name='worktimepattern',
            index=models.Index(fields=['display_order'], name='apps_master_display_ac2c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='worktimepatternwork',
            index=models.Index(fields=['display_order'], name='apps_master_display_3a8291_idx'),
        ),
        migrations.AddIndex(
            model_name='worktimepatternbreak',
            index=models.Index(fields=['display_order'], name='apps_master_display_2de2f2_idx'),
        ),
    ]
