# Generated by Django 5.2.5 on 2025-09-02 13:44

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_informationfile'),
        ('settings', '0005_menu_required_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('jobs_kourou', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'category': 'jobs_kourou'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_category_kourou', to='settings.dropdowns', verbose_name='職業分類(厚労省)')),
                ('jobs_soumu', models.ForeignKey(blank=True, limit_choices_to={'active': True, 'category': 'jobs_soumu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_category_soumu', to='settings.dropdowns', verbose_name='職業分類(総務省)')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '職種マスタ',
                'verbose_name_plural': '職種マスタ',
                'db_table': 'apps_master_job_category',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='apps_master_is_acti_21241f_idx'), models.Index(fields=['display_order'], name='apps_master_display_68ec10_idx')],
            },
        ),
    ]
