# Generated by Django 5.2.8 on 2025-11-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_worktimepattern_worktimepatternwork_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktimepatternbreak',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='worktimepatternwork',
            name='memo',
        ),
    ]
