# Generated by Django 5.2.5 on 2025-09-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0015_staffagreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffagreement",
            name="corporation_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="法人番号"
            ),
        ),
    ]
