# Generated by Django 5.2.8 on 2025-11-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_remove_worktimepatternbreak_memo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktimepatternbreak',
            name='time_name',
        ),
    ]
