# Generated by Django 5.2.5 on 2025-09-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_staffagreement_corporation_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billbank',
            options={'ordering': ['display_order'], 'verbose_name': '会社銀行', 'verbose_name_plural': '会社銀行'},
        ),
        migrations.RemoveField(
            model_name='billbank',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='billbank',
            name='name',
        ),
    ]
