# Generated by Django 5.2.8 on 2025-11-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_remove_worktimepatternbreak_time_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktimepatternwork',
            name='time_name',
        ),
    ]
