# Generated by Django 5.2.8 on 2025-11-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_remove_worktimepatternwork_time_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimepatternwork',
            name='time_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'title__key': 'WORKTIME_NAME'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worktime_pattern_works', to='master.phrasetemplate', verbose_name='時間名称'),
        ),
    ]
