# Generated by Django 5.2.5 on 2025-09-04 16:33

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0017_alter_billbank_options_remove_billbank_branch_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "template_key",
                    models.CharField(
                        help_text='プログラム側で識別するためのキー（例: "connect_request_new_user"）',
                        max_length=255,
                        unique=True,
                        verbose_name="テンプレートキー",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="件名")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="このテンプレートの説明や変数のリストなど",
                        null=True,
                        verbose_name="備考",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "メールテンプレート",
                "verbose_name_plural": "メールテンプレート",
                "db_table": "apps_master_mail_template",
                "ordering": ["template_key"],
            },
        ),
    ]
