# Generated by Django 5.2.5 on 2025-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0018_mailtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="name",
            field=models.CharField(
                default="", editable=False, max_length=255, verbose_name="日本語名"
            ),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="template_key",
            field=models.CharField(
                editable=False,
                help_text='プログラム側で識別するためのキー（例: "connect_request_new_user"）',
                max_length=255,
                unique=True,
                verbose_name="テンプレートキー",
            ),
        ),
    ]
