# Generated by Django 5.2.5 on 2025-09-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_mailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billbank',
            name='account_type',
            field=models.CharField(help_text='普通、当座など', max_length=10, verbose_name='口座種別'),
        ),
    ]
