# Generated by Django 5.2.8 on 2025-11-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_alter_worktimepatternwork_time_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimepatternbreak',
            name='end_time_next_day',
            field=models.BooleanField(default=False, help_text='終了時刻が翌日の場合にチェック', verbose_name='終了時刻翌日'),
        ),
        migrations.AddField(
            model_name='worktimepatternbreak',
            name='start_time_next_day',
            field=models.BooleanField(default=False, help_text='開始時刻が翌日の場合にチェック', verbose_name='開始時刻翌日'),
        ),
        migrations.AddField(
            model_name='worktimepatternwork',
            name='end_time_next_day',
            field=models.BooleanField(default=False, help_text='終了時刻が翌日の場合にチェック', verbose_name='終了時刻翌日'),
        ),
    ]
