# Generated by Django 5.2.5 on 2025-09-07 11:33

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0019_alter_billbank_account_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("staff", "スタッフ契約"),
                            ("client", "クライアント契約"),
                        ],
                        default="staff",
                        max_length=10,
                        verbose_name="契約種別",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "契約パターン",
                "verbose_name_plural": "契約パターン",
                "db_table": "apps_master_contract_pattern",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContractTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("contract_clause", models.TextField(verbose_name="契約条項")),
                ("contract_terms", models.TextField(verbose_name="契約文言")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "contract_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="master.contractpattern",
                        verbose_name="契約パターン",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "契約文言",
                "verbose_name_plural": "契約文言",
                "db_table": "apps_master_contract_terms",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="contractpattern",
            index=models.Index(
                fields=["is_active"], name="apps_master_is_acti_a43933_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractpattern",
            index=models.Index(
                fields=["display_order"], name="apps_master_display_3d59ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractterms",
            index=models.Index(
                fields=["display_order"], name="apps_master_display_7b103d_idx"
            ),
        ),
    ]
