# Generated by Django 5.2.5 on 2025-09-09 15:28

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0020_contractpattern_contractterms_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MinimumPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("pref", models.CharField(max_length=10, verbose_name="都道府県")),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("hourly_wage", models.IntegerField(verbose_name="最低時給")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "最低賃金",
                "verbose_name_plural": "最低賃金",
                "db_table": "apps_master_minimum_pay",
                "ordering": ["display_order", "pref", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="apps_master_is_acti_413155_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="apps_master_display_dd23ae_idx"
                    ),
                    models.Index(fields=["pref"], name="apps_master_pref_985c4a_idx"),
                    models.Index(
                        fields=["start_date"], name="apps_master_start_d_0247b6_idx"
                    ),
                ],
            },
        ),
    ]
