# Generated by Django 5.2.8 on 2025-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_worktimepatternbreak_end_time_next_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimepatternwork',
            name='start_time_next_day',
            field=models.BooleanField(default=False, help_text='開始時刻が翌日の場合にチェック', verbose_name='開始時刻翌日'),
        ),
    ]
