# Generated by Django 5.2.8 on 2025-11-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_worktimepatternwork_start_time_next_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttype',
            name='worktime_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_types', to='master.worktimepattern', verbose_name='就業時間パターン'),
        ),
    ]
