# Generated by Django 5.2.6 on 2025-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0021_minimumpay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractpattern",
            options={
                "ordering": ["contract_type", "display_order"],
                "verbose_name": "契約パターン",
                "verbose_name_plural": "契約パターン",
            },
        ),
        migrations.AddField(
            model_name="contractterms",
            name="memo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="メモ"
            ),
        ),
        migrations.AlterField(
            model_name="contractpattern",
            name="contract_type",
            field=models.CharField(
                choices=[("staff", "スタッフ"), ("client", "クライアント")],
                default="staff",
                max_length=10,
                verbose_name="契約種別",
            ),
        ),
    ]
