# Generated by Django 5.2.6 on 2025-09-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0022_alter_contractpattern_options_contractterms_memo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpattern",
            name="memo",
            field=models.TextField(blank=True, null=True, verbose_name="メモ"),
        ),
    ]
