# Generated by Django 5.2.8 on 2025-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_overtimepattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimepattern',
            name='calculation_type',
            field=models.CharField(choices=[('premium', '割増'), ('variable', '1ヶ月単位変形労働')], default='premium', max_length=20, verbose_name='計算方式'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='daily_overtime_enabled',
            field=models.BooleanField(default=False, verbose_name='日単位時間外計算'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='daily_overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=8.0, max_digits=5, null=True, verbose_name='日単位時間外時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_28_hours',
            field=models.IntegerField(default=160, verbose_name='28日時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_28_minutes',
            field=models.IntegerField(default=0, verbose_name='28日分'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_29_hours',
            field=models.IntegerField(default=165, verbose_name='29日時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_29_minutes',
            field=models.IntegerField(default=42, verbose_name='29日分'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_30_hours',
            field=models.IntegerField(default=171, verbose_name='30日時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_30_minutes',
            field=models.IntegerField(default=25, verbose_name='30日分'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_31_hours',
            field=models.IntegerField(default=177, verbose_name='31日時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='days_31_minutes',
            field=models.IntegerField(default=8, verbose_name='31日分'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='variable_daily_overtime_enabled',
            field=models.BooleanField(default=False, verbose_name='変形労働日単位時間外計算'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='variable_daily_overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=8.0, max_digits=5, null=True, verbose_name='変形労働日単位時間外時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='variable_weekly_overtime_enabled',
            field=models.BooleanField(default=False, verbose_name='変形労働週単位時間外計算'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='variable_weekly_overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=40.0, max_digits=5, null=True, verbose_name='変形労働週単位時間外時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='monthly_estimated_enabled',
            field=models.BooleanField(default=False, verbose_name='月単位見込み残業'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='monthly_estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=5, null=True, verbose_name='月単位見込み残業時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='monthly_overtime_enabled',
            field=models.BooleanField(default=False, verbose_name='月単位時間外割増'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='monthly_overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=60.0, max_digits=5, null=True, verbose_name='月単位時間外割増時間'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='monthly_range_enabled',
            field=models.BooleanField(default=False, verbose_name='月単位時間範囲'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='monthly_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=160.0, max_digits=5, null=True, verbose_name='月単位時間範囲最大'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='monthly_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=140.0, max_digits=5, null=True, verbose_name='月単位時間範囲最小'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='weekly_overtime_enabled',
            field=models.BooleanField(default=False, verbose_name='週単位時間外計算'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='weekly_overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=40.0, max_digits=5, null=True, verbose_name='週単位時間外時間'),
        ),
    ]
