# Generated by Django 5.2.6 on 2025-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_contractpattern_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='target',
            field=models.CharField(default='1', max_length=10, verbose_name='対象'),
        ),
    ]
