# Generated by Django 5.2.6 on 2025-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0024_alter_information_target"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractpattern",
            options={
                "ordering": ["domain", "display_order"],
                "verbose_name": "契約パターン",
                "verbose_name_plural": "契約パターン",
            },
        ),
        migrations.RemoveField(
            model_name="contractpattern",
            name="contract_type",
        ),
        migrations.AddField(
            model_name="contractpattern",
            name="domain",
            field=models.CharField(default="1", max_length=10, verbose_name="対象"),
        ),
    ]
