# Generated by Django 5.2.8 on 2025-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_overtimepattern_calculation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimepattern',
            name='monthly_range_enabled',
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='calculation_type',
            field=models.CharField(choices=[('premium', '割増'), ('monthly_range', '月単位時間範囲'), ('flexible', '1ヶ月単位変形労働')], default='premium', max_length=20, verbose_name='計算方式'),
        ),
    ]
