# Generated by Django 5.2.8 on 2025-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_remove_overtimepattern_monthly_range_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimepattern',
            name='daily_overtime_hours',
            field=models.IntegerField(blank=True, default=8, null=True, verbose_name='日単位時間外時間'),
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='variable_daily_overtime_hours',
            field=models.IntegerField(blank=True, default=8, null=True, verbose_name='変形労働日単位時間外時間'),
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='variable_weekly_overtime_hours',
            field=models.IntegerField(blank=True, default=40, null=True, verbose_name='変形労働週単位時間外時間'),
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='monthly_estimated_hours',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='月単位見込み残業時間'),
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='monthly_overtime_hours',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='月単位時間外割増時間'),
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='monthly_range_max',
            field=models.IntegerField(blank=True, default=160, null=True, verbose_name='月単位時間範囲最大'),
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='monthly_range_min',
            field=models.IntegerField(blank=True, default=140, null=True, verbose_name='月単位時間範囲最小'),
        ),
        migrations.AlterField(
            model_name='overtimepattern',
            name='weekly_overtime_hours',
            field=models.IntegerField(blank=True, default=40, null=True, verbose_name='週単位時間外時間'),
        ),
    ]
