# Generated by Django 5.2.6 on 2025-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0025_alter_contractpattern_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpattern",
            name="contract_type_code",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="契約種別"
            ),
        ),
    ]
