# Generated by Django 5.2.6 on 2025-09-21 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0026_contractpattern_contract_type_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractterms",
            options={
                "ordering": ["display_position", "display_order"],
                "verbose_name": "契約文言",
                "verbose_name_plural": "契約文言",
            },
        ),
        migrations.AddField(
            model_name="contractterms",
            name="display_position",
            field=models.IntegerField(
                choices=[(1, "前文"), (2, "本文"), (3, "末文")],
                default=2,
                verbose_name="表示場所",
            ),
        ),
        migrations.AddIndex(
            model_name="contractterms",
            index=models.Index(
                fields=["display_position"], name="apps_master_display_b279e3_idx"
            ),
        ),
    ]
