# Generated by Django 5.2.8 on 2025-11-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_alter_overtimepattern_daily_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttype',
            name='overtime_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_types', to='master.overtimepattern', verbose_name='時間外算出パターン'),
        ),
    ]
