# Generated by Django 5.2.8 on 2025-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0027_employmenttype_overtime_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimepattern",
            name="calculate_midnight_premium",
            field=models.BooleanField(default=False, verbose_name="深夜割増を計算する"),
        ),
    ]
