# Generated by Django 5.2.6 on 2025-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0028_businesscontent_hakenresponsibilitydegree"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="is_manufacturing_dispatch",
            field=models.BooleanField(
                default=False,
                help_text="この職種が製造業務への労働者派遣に該当する場合にチェックします。",
                verbose_name="製造派遣該当",
            ),
        ),
    ]
