# Generated by Django 5.2.6 on 2025-10-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_jobcategory_is_manufacturing_dispatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpattern',
            options={'ordering': ['domain', 'display_order'], 'verbose_name': '契約書パターン', 'verbose_name_plural': '契約書パターン'},
        ),
        migrations.AlterField(
            model_name='contractterms',
            name='contract_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='master.contractpattern', verbose_name='契約書パターン'),
        ),
    ]
