# Generated by Django 5.2.8 on 2025-11-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_userparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimepattern',
            name='daily_overtime_minutes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='日単位時間外分'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='weekly_overtime_minutes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='週単位時間外分'),
        ),
    ]
