# Generated by Django 5.2.8 on 2025-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_add_overtime_minutes_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimepattern',
            name='variable_daily_overtime_minutes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='変形労働日単位時間外分'),
        ),
        migrations.AddField(
            model_name='overtimepattern',
            name='variable_weekly_overtime_minutes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='変形労働週単位時間外分'),
        ),
    ]
