# Generated by Django 5.2.6 on 2025-11-29 15:44

from django.db import migrations


def migrate_variable_fields_to_common(apps, schema_editor):
    """
    variable_*フィールドのデータを共通フィールドに移行する
    calculation_type='variable'のパターンのみ対象
    """
    OvertimePattern = apps.get_model('master', 'OvertimePattern')
    
    for pattern in OvertimePattern.objects.filter(calculation_type='variable'):
        # variable_*フィールドの値を共通フィールドにコピー
        if hasattr(pattern, 'variable_daily_overtime_enabled'):
            pattern.daily_overtime_enabled = pattern.variable_daily_overtime_enabled
        if hasattr(pattern, 'variable_daily_overtime_hours'):
            pattern.daily_overtime_hours = pattern.variable_daily_overtime_hours
        if hasattr(pattern, 'variable_daily_overtime_minutes'):
            pattern.daily_overtime_minutes = pattern.variable_daily_overtime_minutes
        if hasattr(pattern, 'variable_weekly_overtime_enabled'):
            pattern.weekly_overtime_enabled = pattern.variable_weekly_overtime_enabled
        if hasattr(pattern, 'variable_weekly_overtime_hours'):
            pattern.weekly_overtime_hours = pattern.variable_weekly_overtime_hours
        if hasattr(pattern, 'variable_weekly_overtime_minutes'):
            pattern.weekly_overtime_minutes = pattern.variable_weekly_overtime_minutes
        
        pattern.save()


def reverse_migrate_common_to_variable(apps, schema_editor):
    """
    ロールバック時: 共通フィールドのデータをvariable_*フィールドに戻す
    """
    OvertimePattern = apps.get_model('master', 'OvertimePattern')
    
    for pattern in OvertimePattern.objects.filter(calculation_type='variable'):
        # 共通フィールドの値をvariable_*フィールドにコピー
        if hasattr(pattern, 'daily_overtime_enabled'):
            pattern.variable_daily_overtime_enabled = pattern.daily_overtime_enabled
        if hasattr(pattern, 'daily_overtime_hours'):
            pattern.variable_daily_overtime_hours = pattern.daily_overtime_hours
        if hasattr(pattern, 'daily_overtime_minutes'):
            pattern.variable_daily_overtime_minutes = pattern.daily_overtime_minutes
        if hasattr(pattern, 'weekly_overtime_enabled'):
            pattern.variable_weekly_overtime_enabled = pattern.weekly_overtime_enabled
        if hasattr(pattern, 'weekly_overtime_hours'):
            pattern.variable_weekly_overtime_hours = pattern.weekly_overtime_hours
        if hasattr(pattern, 'weekly_overtime_minutes'):
            pattern.variable_weekly_overtime_minutes = pattern.weekly_overtime_minutes
        
        pattern.save()


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0031_add_flexible_overtime_minutes_fields'),
    ]

    operations = [
        # ステップ1: データ移行
        migrations.RunPython(
            migrate_variable_fields_to_common,
            reverse_migrate_common_to_variable,
        ),
        # ステップ2: フィールド削除
        migrations.RemoveField(
            model_name='overtimepattern',
            name='variable_daily_overtime_enabled',
        ),
        migrations.RemoveField(
            model_name='overtimepattern',
            name='variable_daily_overtime_hours',
        ),
        migrations.RemoveField(
            model_name='overtimepattern',
            name='variable_daily_overtime_minutes',
        ),
        migrations.RemoveField(
            model_name='overtimepattern',
            name='variable_weekly_overtime_enabled',
        ),
        migrations.RemoveField(
            model_name='overtimepattern',
            name='variable_weekly_overtime_hours',
        ),
        migrations.RemoveField(
            model_name='overtimepattern',
            name='variable_weekly_overtime_minutes',
        ),
    ]
