# Generated by Django 5.2.6 on 2025-10-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0031_defaultvalue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultvalue",
            options={
                "ordering": ["display_order", "target_item"],
                "verbose_name": "初期値マスタ",
                "verbose_name_plural": "初期値マスタ",
            },
        ),
        migrations.AddField(
            model_name="defaultvalue",
            name="display_order",
            field=models.IntegerField(default=0, verbose_name="表示順"),
        ),
    ]
