# Generated by Django 5.2.8 on 2025-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0032_consolidate_overtime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimepattern',
            name='calculation_type',
            field=models.CharField(choices=[('premium', '割増'), ('monthly_range', '月単位時間範囲'), ('variable', '1ヶ月単位変形労働'), ('flextime', '1ヶ月単位フレックス')], default='premium', max_length=20, verbose_name='計算方式'),
        ),
    ]
