# Generated by Django 5.2.6 on 2025-10-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0032_alter_defaultvalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpattern',
            name='employment_type',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='雇用形態'),
        ),
    ]
