# Generated by Django 5.2.8 on 2026-01-01 23:46

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0033_alter_overtimepattern_calculation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(help_text='時間丸め設定の名称', max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, help_text='設定の詳細説明', verbose_name='説明')),
                ('start_time_unit', models.IntegerField(choices=[(1, '1分'), (5, '5分'), (10, '10分'), (15, '15分'), (30, '30分')], default=15, help_text='開始時刻の丸め単位（分）', verbose_name='開始時刻丸め単位')),
                ('start_time_method', models.CharField(choices=[('round', '四捨五入'), ('floor', '切り捨て'), ('ceil', '切り上げ')], default='round', help_text='開始時刻の端数処理方法', max_length=10, verbose_name='開始時刻端数処理')),
                ('end_time_unit', models.IntegerField(choices=[(1, '1分'), (5, '5分'), (10, '10分'), (15, '15分'), (30, '30分')], default=15, help_text='終了時刻の丸め単位（分）', verbose_name='終了時刻丸め単位')),
                ('end_time_method', models.CharField(choices=[('round', '四捨五入'), ('floor', '切り捨て'), ('ceil', '切り上げ')], default='round', help_text='終了時刻の端数処理方法', max_length=10, verbose_name='終了時刻端数処理')),
                ('break_input', models.BooleanField(default=True, help_text='休憩時間を入力するかどうか', verbose_name='休憩入力')),
                ('break_start_unit', models.IntegerField(choices=[(1, '1分'), (5, '5分'), (10, '10分'), (15, '15分'), (30, '30分')], default=15, help_text='休憩開始時刻の丸め単位（分）', verbose_name='休憩開始時刻丸め単位')),
                ('break_start_method', models.CharField(choices=[('round', '四捨五入'), ('floor', '切り捨て'), ('ceil', '切り上げ')], default='round', help_text='休憩開始時刻の端数処理方法', max_length=10, verbose_name='休憩開始時刻端数処理')),
                ('break_end_unit', models.IntegerField(choices=[(1, '1分'), (5, '5分'), (10, '10分'), (15, '15分'), (30, '30分')], default=15, help_text='休憩終了時刻の丸め単位（分）', verbose_name='休憩終了時刻丸め単位')),
                ('break_end_method', models.CharField(choices=[('round', '四捨五入'), ('floor', '切り捨て'), ('ceil', '切り上げ')], default='round', help_text='休憩終了時刻の端数処理方法', max_length=10, verbose_name='休憩終了時刻端数処理')),
                ('is_active', models.BooleanField(default=True, help_text='この設定を有効にするかどうか', verbose_name='有効')),
                ('sort_order', models.IntegerField(default=0, help_text='一覧での表示順序', verbose_name='表示順')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '時間丸めマスタ',
                'verbose_name_plural': '時間丸めマスタ',
                'db_table': 'apps_master_time_rounding',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
