# Generated by Django 5.2.7 on 2025-10-14 10:09

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0035_alter_contractpattern_employment_type_to_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientRegistStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "クライアント登録状況",
                "verbose_name_plural": "クライアント登録状況",
                "db_table": "apps_master_client_regist_status",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="apps_master_is_acti_3bc65a_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="apps_master_display_3d3171_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffRegistStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ登録状況",
                "verbose_name_plural": "スタッフ登録状況",
                "db_table": "apps_master_staff_regist_status",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="apps_master_is_acti_bd92fc_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="apps_master_display_cbf8c9_idx"
                    ),
                ],
            },
        ),
    ]
