# Generated by Django 5.2.6 on 2026-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0035_alter_timepunch_break_end_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timepunch',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '勤怠打刻マスタ', 'verbose_name_plural': '勤怠打刻マスタ'},
        ),
        migrations.AlterField(
            model_name='timepunch',
            name='name',
            field=models.CharField(help_text='勤怠打刻設定の名称', max_length=100, verbose_name='名称'),
        ),
    ]
