# Generated by Django 5.2.6 on 2026-01-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0036_alter_timepunch_options_alter_timepunch_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timepunch',
            table='apps_master_time_punch',
        ),
    ]
