# Generated by Django 5.2.7 on 2025-10-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0037_alter_defaultvalue_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='is_agriculture_fishery_dispatch',
            field=models.BooleanField(default=False, help_text='この職種が農業・漁業への労働者派遣に該当する場合にチェックします。', verbose_name='農業漁業派遣該当'),
        ),
    ]
