# Generated by Django 5.2.6 on 2026-01-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0037_alter_timepunch_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepunch',
            name='punch_method',
            field=models.CharField(choices=[('punch', '打刻'), ('e-staffing', 'e-staffing'), ('hrmos', 'HRMOS'), ('kot', 'KING OF TIME'), ('tot', 'Touch On Time'), ('manual', '手入力')], default='punch', help_text='勤怠管理の打刻方法', max_length=20, verbose_name='打刻方法'),
        ),
    ]
