# Generated by Django 5.2.6 on 2026-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0038_timepunch_punch_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepunch',
            name='location_info',
            field=models.BooleanField(choices=[(True, '入力する'), (False, '入力しない')], default=True, help_text='勤怠打刻時に位置情報を取得するかどうか', verbose_name='位置情報取得'),
        ),
    ]
