# Generated by Django 5.2.7 on 2025-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0038_jobcategory_is_agriculture_fishery_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='is_specified_skilled_worker',
            field=models.BooleanField(default=False, help_text='この職種が特定技能外国人の受入れに該当する場合にチェックします。', verbose_name='特定技能外国人受入該当'),
        ),
    ]
