# Generated by Django 5.2.7 on 2025-10-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0039_jobcategory_is_specified_skilled_worker'),
        ('settings', '0005_menu_required_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='jobs_seirei',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'category': 'jobs_seirei'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_category_seirei', to='settings.dropdowns', verbose_name='派遣政令業務'),
        ),
    ]
