# Generated by Django 5.2.8 on 2026-01-10 11:32

import concurrency.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0039_timepunch_location_info"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerativeAiSetting",
            fields=[
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="record revision number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="キー",
                    ),
                ),
                (
                    "target_item",
                    models.CharField(max_length=255, verbose_name="対象項目"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("text", "テキスト"),
                            ("textarea", "テキストエリア"),
                            ("boolean", "真偽値"),
                            ("number", "数値"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="形式",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="値")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成AI設定",
                "verbose_name_plural": "生成AI設定",
                "db_table": "apps_master_generative_ai_setting",
                "ordering": ["display_order", "target_item"],
            },
        ),
    ]
