# Generated by Django 5.2.8 on 2026-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0040_generativeaisetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='generativeaisetting',
            name='ai_provider',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('gemini', 'Gemini')], max_length=10, null=True, verbose_name='生成AI'),
        ),
        migrations.AlterField(
            model_name='generativeaisetting',
            name='format',
            field=models.CharField(choices=[('text', 'テキスト'), ('textarea', 'テキストエリア'), ('boolean', '真偽値'), ('number', '数値'), ('choice', '選択肢')], default='text', max_length=10, verbose_name='形式'),
        ),
    ]
