# Generated by Django 5.2.8 on 2026-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0041_add_ai_provider_to_generativeaisetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="userparameter",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="形式が「選択肢」の場合に、カンマ区切りで「値:表示名」を入力します。",
                verbose_name="選択肢",
            ),
        ),
        migrations.AlterField(
            model_name="userparameter",
            name="format",
            field=models.CharField(
                choices=[
                    ("text", "テキスト"),
                    ("textarea", "テキストエリア"),
                    ("boolean", "真偽値"),
                    ("number", "数値"),
                    ("choice", "選択肢"),
                ],
                default="text",
                max_length=10,
                verbose_name="形式",
            ),
        ),
    ]
