# Generated by Django 5.2.8 on 2026-01-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0042_userparameter_choices_alter_userparameter_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generativeaisetting",
            name="ai_provider",
        ),
        migrations.AddField(
            model_name="generativeaisetting",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="形式が「選択肢」の場合に、カンマ区切りで「値:表示名」を入力します。",
                verbose_name="選択肢",
            ),
        ),
    ]
