# Generated by Django 5.2.8 on 2026-01-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0043_remove_generativeaisetting_ai_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userparameter",
            name="format",
            field=models.CharField(
                choices=[
                    ("text", "テキスト"),
                    ("textarea", "テキストエリア"),
                    ("boolean", "真偽値"),
                    ("number", "数値"),
                    ("choice", "選択肢"),
                    ("color", "色"),
                ],
                default="text",
                max_length=10,
                verbose_name="形式",
            ),
        ),
    ]
