# Generated by Django 5.2.8 on 2026-01-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0044_alter_userparameter_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="billbank",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="clientregiststatus",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="contractpattern",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="contractterms",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="defaultvalue",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="employmenttype",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="generativeaisetting",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="informationfile",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="jobcategory",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="mailtemplate",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="minimumpay",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="overtimepattern",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="phrasetemplate",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="phrasetemplatetitle",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffagreement",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="staffregiststatus",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="timepunch",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="userparameter",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="worktimepattern",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="worktimepatternbreak",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
        migrations.AddField(
            model_name="worktimepatternwork",
            name="tenant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="テナントID"
            ),
        ),
    ]
